// Ziproh Compliance — 2026 Expansion Set D (Group 6: Care Home, Catering & Domestic)
// All content original. Written tailoring-ready (generic base terms adapt per care setting).

import type { Document, DocumentContent } from "./documents";

export const EXPANSION_2026D_DOCS: Document[] = [
  {
    id: "ch-001",
    title: "Catering & Food Service Policy",
    category: "Effective", subcategory: "Catering & Nutrition", keyQuestion: "Effective",
    serviceTypes: ["Care & Nursing Home", "Residential", "Nursing Home", "Supported Living", "Hospice"],
    regulators: ["CQC", "CI", "CIW", "RQIA"],
    version: "1.0", lastUpdated: "2026-07-15", status: "updated", readTime: 12,
    tags: ["catering", "food service", "nutrition", "kitchen operations", "food provision", "choice"],
    summary: "The catering operation end to end: how food is planned, procured, prepared and served so that eating remains one of life's reliable pleasures — governance of the kitchen, choice that is real rather than theoretical, nutritional adequacy, and the interfaces every meal depends on.",
  },
  {
    id: "ch-002",
    title: "Food Safety & Hygiene Policy (HACCP)",
    category: "Safe", subcategory: "Catering & Nutrition", keyQuestion: "Safe",
    serviceTypes: ["Care & Nursing Home", "Residential", "Nursing Home", "Supported Living", "Hospice"],
    regulators: ["CQC", "CI", "CIW", "RQIA"],
    version: "1.0", lastUpdated: "2026-07-15", status: "updated", readTime: 14,
    tags: ["food safety", "HACCP", "temperature control", "food hygiene", "EHO", "safer food better business"],
    summary: "Food safety built on the HACCP disciplines: hazard-based controls from delivery to plate, the temperature rules that matter (cook, chill, hot-hold, reheat), personal hygiene and fitness to handle food, the documented system inspectors rate, and food safety in small domestic kitchens.",
  },
  {
    id: "ch-003",
    title: "Allergen Management Policy",
    category: "Safe", subcategory: "Catering & Nutrition", keyQuestion: "Safe",
    serviceTypes: ["All"], regulators: ["CQC", "CI", "CIW", "RQIA"],
    version: "1.0", lastUpdated: "2026-07-15", status: "updated", readTime: 12,
    tags: ["allergens", "14 allergens", "anaphylaxis", "cross-contamination", "allergen matrix", "food labelling"],
    summary: "Allergen control that treats every allergy as the emergency it can become: the person-level allergen record, the recipe-level matrix, cross-contamination discipline, communication across every handover and every plate, snacks and visitors' food, and the anaphylaxis response.",
  },
  {
    id: "ch-004",
    title: "Menu Planning & Special Diets Policy",
    category: "Effective", subcategory: "Catering & Nutrition", keyQuestion: "Effective",
    serviceTypes: ["Care & Nursing Home", "Residential", "Nursing Home", "Supported Living", "Hospice"],
    regulators: ["CQC", "CI", "CIW", "RQIA"],
    version: "1.0", lastUpdated: "2026-07-15", status: "updated", readTime: 13,
    tags: ["menu planning", "special diets", "texture modification", "IDDSI", "fortification", "cultural diets", "diabetes"],
    summary: "Menus planned for nutrition, choice and the people actually eating them: cycle menus with genuine alternatives, therapeutic and texture-modified diets delivered accurately (IDDSI), fortification for small appetites, cultural and religious diets as standard service not special favours, and the clinical interfaces.",
  },
  {
    id: "ch-005",
    title: "Mealtime Experience Policy",
    category: "Caring", subcategory: "Catering & Nutrition", keyQuestion: "Caring",
    serviceTypes: ["Care & Nursing Home", "Residential", "Nursing Home", "Supported Living", "Hospice"],
    regulators: ["CQC", "CI", "CIW", "RQIA"],
    version: "1.0", lastUpdated: "2026-07-15", status: "updated", readTime: 11,
    tags: ["mealtime", "dining experience", "protected mealtimes", "eating support", "dignity", "dementia dining"],
    summary: "Mealtimes as the social heart of the day: protected time with enough hands, dining environments that invite eating, support given at each person's pace with dignity, dementia-attuned dining, the monitoring that catches quiet decline, and flexibility for people whose day runs differently.",
  },
];

export const EXPANSION_2026D_CONTENT: Record<string, DocumentContent> = {
  "ch-001": {
    purpose: "This policy governs the catering operation so that food does its whole job: nourishing bodies, marking the day's rhythm, carrying culture and memory, and remaining — for people whose choices have narrowed — one of the pleasures still fully theirs. It sets the governance of how food is planned, bought, cooked and served, and holds the standard that a meal judged only on calories has been judged on a fraction of its work.",
    scope: "Covers the catering function in services that provide food: kitchen governance and staffing, procurement, food provision standards, choice and alternatives, drinks and snacks between meals, and the interfaces with Food Safety (ch-002), Allergens (ch-003), Menus & Special Diets (ch-004), Mealtimes (ch-005) and Nutrition & Hydration (eff-003).",
    responsibilities: [
      { role: "Registered Manager", duties: [
        "Resource the catering function: qualified cook/chef cover across the week including their absence, kitchen assistant support, and the budget honesty that keeps quality above the line",
        "Hold the interfaces together: kitchen informed of every dietary need and change the same day; care staff informed of what the kitchen is serving and why",
        "Ensure choice is real: genuine alternatives at every meal, and a kitchen culture that treats requests as service, not disruption",
        "Register the food business with the local authority and host EHO inspections as the audits they are",
        "Review food quality through the eyes that matter: residents' feedback, plate waste, and eating the food themselves regularly" ] },
      { role: "Catering Staff", duties: [
        "Cook to the menu and the dietary matrix accurately — a special diet delivered wrong is a clinical error made in a kitchen",
        "Keep the food safety and allergen disciplines (ch-002, ch-003) as the floor of everything",
        "Know the people they cook for: names, preferences, portions, and the feedback loop that turns waste into information",
        "Flag supply and budget pressures honestly rather than quietly downgrading quality" ] },
      { role: "Care Staff", duties: [
        "Feed the kitchen its intelligence: appetite changes, new dislikes, weight concerns, dietary changes — same day, through the agreed route",
        "Present food as it deserves: hot, attractive, correctly served, with the alternatives genuinely offered",
        "Know enough about every person's diet to serve safely (allergen and texture awareness is everyone's job)" ] },
    ],
    keyPoints: [
      "Food provision meets the whole standard: nutritionally adequate across the day (not just at main meals), sufficient in quantity with more available, varied across the menu cycle, culturally competent, attractive on the plate, and served at safe and pleasant temperatures — adequacy is the floor, enjoyment is the target",
      "Choice is structural, not ceremonial: at least two genuine options at main meals (both actually available, not one 'default' and one apology), a standing alternatives list (omelette, sandwich, salad, jacket potato or the service's equivalents) that never runs out, and the plated-versus-served choices (portion size, gravy on or off, vegetables separate) that dignity lives in",
      "The 24-hour food day is planned: breakfast that flexes with waking times, snacks and baking mid-morning and mid-afternoon, supper that closes the gap to breakfast (the long overnight fast harms frail people), night snacks available and offered — and drinks constantly: the hydration round is a care task with catering support (eff-003's territory, provisioned here)",
      "The kitchen knows its people: a live dietary and preference record per person (allergies via ch-003's matrix, textures via ch-004, likes, dislikes, portions, cultural requirements), updated same-day on any change, and new admissions' food conversation happening within their first day — hunger doesn't wait for the next menu cycle",
      "Procurement balances cost, quality and resilience: reputable suppliers with food-safety credentials (delivery checks per ch-002), seasonal buying that stretches budgets honestly, contingency arrangements for supply failure, and the budget conversation held at provider level when quality and funds genuinely conflict — the quiet degradation of portions and ingredients is a governance failure, not a kitchen economy",
      "Fresh cooking is the default: meals cooked on site from fresh ingredients where the service's model provides, with bought-in and cook-chill elements meeting the same nutritional and safety standards where used — and the distinction visible in governance, not blurred",
      "Feedback runs on every channel: residents' meetings and food committees with the kitchen present, comment routes at the point of eating, plate-waste watched as data (waste patterns are the menu telling the truth), and the manager and senior staff eating the actual food regularly and unannounced",
      "EHO ratings are owned at provider level: the food hygiene rating is displayed, a rating below the top prompts a recovery plan with dates, and the documented system (ch-002) is maintained as the living thing inspectors rate rather than a binder revived before visits",
    ],
    legislation: [
      "Food Safety Act 1990 and Food Hygiene Regulations 2013 (registration, standards)",
      "Regulation (EC) 852/2004 (retained — hygiene of foodstuffs)",
      "Health and Social Care Act 2008 (Regulated Activities) Regulations 2014 — Regulation 14 (nutritional needs)",
      "Care Act 2014 (wellbeing including nutrition)",
      "Equality Act 2010 (cultural and religious provision)",
    ],
    sections: [
      { heading: "Governance of the Kitchen", body: "The catering function is run as the clinical-adjacent operation it is. Staffing: qualified cooking cover across every day the service serves food — including the head cook's leave and sickness, which is planned for by trained relief rather than survived by improvisation — with food hygiene training levels matched to roles (ch-002) and the kitchen included in the service's supervision, appraisal and training systems rather than orbiting outside them. Information: the kitchen holds the live dietary record and receives changes the same day through a single agreed route (not corridor messages), attends or receives the output of relevant reviews (weight loss meetings, SALT changes), and its own intelligence — who left what, who asked for seconds, whose portions crept down — flows back to care staff through handover. Registration and inspection: the food business is registered with the local authority before trading, EHO inspections are hosted openly with findings actioned on the stated timescales, and the rating is displayed where honesty requires. Budget: the food spend per person per day is known at provider level, reviewed against quality indicators (not just cost), and protected from becoming the invisible balancing item of wider pressures — the governance review sees food quality data alongside food cost data, deliberately, in the same paper." },
      { heading: "Provision Standards and Choice", body: "The provision standard covers the whole eating day. Main meals offer genuine choice: at least two options seen or described (dementia-friendly menus use pictures and show-plates; verbal offers happen at the point of choosing, not the day before when the answer will be forgotten), both options actually cooked in sufficient quantity, and the standing alternatives available without ceremony for anyone whom neither option suits. Quantity is generous with seconds normalised; portion sizes flex to the person (the fortified small plate for the overwhelmed appetite is ch-004's craft). Presentation matters clinically: appetite in later life is led by the eyes, so plates are built with colour and care, texture-modified food is moulded and presented as real food (ch-004), and hot food arrives hot through service systems (heated trolleys, plate covers, staggered plating) that survive the building's geography. Between meals, the trolley rounds carry real choices — fresh fruit, home baking, cheese and biscuits, yoghurts — plus the constant availability that matters at night, and drinks provision supports the hydration schedule with variety (the person who won't drink water may drink squash, milky coffee, or soup). Cultural competence is provision, not exception: the kosher, halal, vegetarian, vegan and cultural-cuisine needs of the current residents shape the actual menu and sourcing (ch-004), and festival foods are cooked for the festivals the residents keep." },
      { heading: "Procurement and Resilience", body: "Suppliers are selected for safety and quality evidence: registered food businesses with acceptable hygiene ratings, delivery vehicles and practices that hold the cold chain (checked at the door per ch-002's delivery discipline), specification honesty (the meat content, the provenance where claimed), and the responsiveness that a kitchen feeding dependent people needs when orders fail. The supplier list is reviewed on a cycle with delivery-check data feeding it. Buying practice balances the triangle: seasonal and local where it serves quality and cost together; bulk where storage and turnover justify it (stock rotation per ch-002); and never the false economy of ingredients whose quality the plates will confess. Resilience is planned: minimum stock holdings that bridge supply interruption (linked to the business continuity policy's scenarios), alternative suppliers identified before they are needed, emergency menu plans that stay nutritious when deliveries fail, and — for the scenarios that close kitchens entirely (equipment failure, contamination, works) — the mutual-aid and bought-in arrangements that keep hot food arriving while repairs happen. Waste is managed at both ends: purchasing tuned by consumption data, and plate and production waste measured monthly as the menu-quality indicator it is, with the food-waste stream disposed per the Waste policy." },
      { heading: "Quality: The Eating Test", body: "Food quality is verified by eating, watching and asking — not by menu paperwork. The structured elements: residents' food forums or the food item in residents' meetings, with the cook present and actions minuted and done; comment mechanisms at the point of eating for those who won't wait for meetings; periodic satisfaction exercises that reach the quiet, the cognitively impaired (observation-based tools) and families; and plate-waste review that reads patterns (a dish that consistently returns half-eaten is a vote). The unstructured element carries equal weight: the manager and seniors eat the service's actual food — the same plates, unannounced, including texture-modified meals and the night supper — regularly enough to know it the way residents do, because no audit replaces the manager who can say from experience that Tuesday's fish needs work. Findings feed the menu cycle review (ch-004), the governance report (quality indicators beside cost), and the kitchen's own professional pride, which is the asset the whole policy ultimately protects: a kitchen that knows its work matters, cooks like it matters." },
    ],
    appendices: [
      { title: "Kitchen Communication Sheet (daily, both directions)", type: "template", body:
"TO KITCHEN (same-day, single route — no corridor messages):\nDietary changes: person | change (allergy/texture/therapeutic/preference) | source (SALT/dietitian/GP/person) | effective NOW [ ] | dietary record updated [ ]\nAdmissions: food conversation done (day 1) [ ] — allergies, textures, likes/dislikes, portions, cultural needs → record created\nAppetite intelligence: who ate poorly | who asked for more | weight-watch list changes\nNumbers for next meals (incl. visitors/day attendees): ______\nFROM KITCHEN (to handover):\nToday's meals & alternatives | who had what (exceptions) | plate-waste flags (dish-level) | supply substitutions affecting diets (checked vs allergen matrix [ ]) | stock/supply concerns\nWeekly: plate-waste pattern summary → menu review file" },
      { title: "Catering Quality Review (monthly)", type: "checklist", body:
"PROVISION: choice real at every main meal (both options cooked) [ ] standing alternatives never exhausted [ ] 24h food day working (breakfast flex/snacks/supper/night availability) [ ] hot food hot at the furthest point (temp at service — ch-002 log) [ ]\nPRESENTATION: plates seen at service (colour, portions, TM food moulded & presented) [ ] show-plates/picture menus in use where needed [ ]\nEATING TEST: manager/senior ate unannounced (dates, meals incl. TM & supper): ______ findings: ______\nFEEDBACK: residents' food forum held (actions done) [ ] point-of-eating comments reviewed [ ] plate-waste patterns → menu file [ ]\nKITCHEN: cook cover secured next month (incl. leave) [ ] training current [ ] supplier/delivery issues [ ] budget vs quality tension escalated? ______\nEHO: rating displayed ____ | below top → recovery plan (dates): ______" },
    ],
  },
  "ch-002": {
    purpose: "This policy keeps food from harming the people least able to survive its hazards. Frail and older people die from food poisoning that healthy adults shrug off, so the kitchen runs on the HACCP disciplines: hazards identified, controls at the points that matter, checks that prove the controls worked, and records that show it — every day, not inspection week.",
    scope: "Covers all food handling from delivery to plate in all settings where the service prepares or serves food: the documented food safety management system, temperature controls, personal hygiene and fitness rules, structural and equipment standards, and the adapted disciplines for small and domestic kitchens including supported living. The kitchen cleaning schedule detail sits with the Cleaning policy (saf-039) and this policy's appendix; allergens have their own policy (ch-003).",
    responsibilities: [
      { role: "Registered Manager", duties: [
        "Maintain the documented food safety management system (HACCP-based, or the recognised small-business format where appropriate) as a live system: current, followed, and checked",
        "Ensure food handlers are trained to the level their role requires and supervised until competent",
        "Provide the equipment the controls depend on: calibrated probes, working fridges and freezers with monitoring, hot-holding that holds",
        "Enforce the fitness-to-handle rules including the 48-hour exclusion without exception",
        "Act on every check failure as the near-miss it is: fix, record, and adjust the system" ] },
      { role: "All Food Handlers", duties: [
        "Perform and record the checks honestly: a temperature log filled in from memory at shift's end is a fiction that will eventually cost someone",
        "Keep the personal hygiene disciplines: handwashing at the trigger points, clean whites/aprons, hair covered, wounds covered with blue detectable plasters",
        "Report symptoms and exclusions honestly: vomiting or diarrhoea means out of food handling for 48 hours after symptoms end, and reporting it is protected behaviour",
        "Respect the separation rules: raw and ready-to-eat never share boards, knives, surfaces, cloths or fridge shelves in the wrong order" ] },
      { role: "Care Staff Who Serve or Prepare Food", duties: [
        "Apply the same rules scaled to the task: hand hygiene before serving, probe checks where the system requires, date labels respected, leftovers handled per the rules",
        "Never bypass the kitchen's controls — reheating a resident's plate 'quickly' outside the system is where the system leaks" ] },
    ],
    keyPoints: [
      "The system is documented and alive: a HACCP-based food safety management system (the recognised small-catering format is acceptable where scale fits) covering every process from delivery to service, with daily and weekly checks diaried, records completed in real time, and a review cycle that updates the system when menus, equipment or findings change",
      "Temperatures are the core controls, known by heart: fridges 0-5°C and freezers -18°C or below (checked and logged at least daily); cooking to 75°C core (or validated equivalent); hot holding at 63°C or above with the 2-hour rule for exceptions; cooling of cooked food fast (within the system's stated window, using shallow containers and cooling techniques, never the fridge-warming pan); reheating to 75°C core, once only; and probe thermometers cleaned, sanitised between uses and calibration-checked on schedule",
      "Delivery and storage discipline sets up everything downstream: deliveries checked at the door (temperature, packaging integrity, dates, vehicle condition) with rejection authority genuinely used; stock rotated first-in-first-out with day-labels on everything opened or prepared; raw stored below ready-to-eat; and the use-by rule absolute — use-by is safety, best-before is quality, and nobody's frugality overrides a use-by date",
      "Cross-contamination is engineered out: colour-coded boards and knives (raw meat/fish/veg/ready-to-eat per the service's scheme), separate or sequenced preparation areas with disinfection between, cloths single-use or colour-bound, and the raw-to-ready workflow running one direction",
      "People are controls too: food hygiene training by role (Level 2 for food handlers, Level 3 for those supervising, refreshed on cycle), induction before solo food handling, the handwashing trigger list displayed at every sink, jewellery/nails/hair rules per hr-023 applied in the kitchen at food-handling strength, and the fitness rules — 48-hour exclusion after GI symptoms, infected wounds covered or excluded, reporting protected",
      "The premises hold the standard: surfaces cleanable and maintained, the kitchen cleaning schedule (appendix) delivered and signed as done, pest vigilance per saf-040 at kitchen strength, waste out promptly (saf-036), and equipment maintained with failures escalated same-day (a broken fridge is an incident with a clock running)",
      "Small and domestic kitchens keep the principles at their scale: supported living and small-unit cooking uses the domestic-appropriate version — same temperature rules, same separation, same personal hygiene, simplified records — and staff cooking with people as enablement (teaching, supporting) hold the safety rails while sharing the task",
      "Failures are managed as incidents: check failures (fridge over temperature, undercooked core) trigger the stated response (assess, discard where the rules say discard, fix, record, review); suspected food poisoning triggers the outbreak interface (saf-045), sample retention where practicable, EHO cooperation, and honest notification — the reflex to explain away symptoms in frail people is the reflex this policy exists to override",
    ],
    legislation: [
      "Food Safety Act 1990",
      "Food Safety and Hygiene (England) Regulations 2013 (and devolved equivalents)",
      "Regulation (EC) 852/2004 (retained EU law — HACCP requirement)",
      "Health and Social Care Act 2008 (Regulated Activities) Regulations 2014 — Regulations 12 and 14",
      "RIDDOR 2013 / Health Protection Regulations (outbreak interfaces)",
    ],
    sections: [
      { heading: "The Documented System", body: "The service operates a written food safety management system built on HACCP thinking: the food journey mapped (delivery → storage → preparation → cooking → cooling → reheating → hot-holding → service), hazards identified at each step (bacterial growth, survival, contamination, physical and chemical hazards), the critical control points named with their limits (the temperature rules), monitoring defined (who checks what, when, with what, recorded where), corrective actions pre-decided (what happens when a check fails), and verification layered on top (supervisor reviews, the manager's spot checks, periodic full review). Small services may run the recognised pack-based format that embeds the same logic. The system lives in the kitchen, not the office: daily diary sheets completed as checks happen, weekly and monthly checks scheduled, records retained per the schedule, and the system reviewed — formally on its cycle, and immediately when menus add new processes (sous-vide, vacuum packing need specific validation), equipment changes, or a failure exposes a gap. The honesty rule is cultural and stated: records reflect what was measured when it was measured; retrospective completion is falsification and treated as the serious conduct matter it is, because a fictional log is more dangerous than a missing one." },
      { heading: "Temperature Life of Food", body: "Every stage has its numbers and its craft. Delivery: chilled at 8°C or below (target 5°C), frozen at -15°C or below (target -18°C), checked with the sanitised probe on a sampling basis and rejected on failure — rejection is praised, not questioned. Storage: fridges 0-5°C, freezers -18°C, logged at least daily from the display and verified periodically by probe; failures trigger the assess-and-act response (how long, how warm, what's affected — the discard decisions err toward frail immune systems, not stock value). Preparation: time out of refrigeration minimised, high-risk foods prepared last or in the cool part of the day in hot weather. Cooking: 75°C core (or the validated time-temperature equivalents) probed in the thickest part, in multiple items for batches, logged per the system's sampling. Cooling: the danger zone crossed quickly — cooked food cooled and refrigerated within the system's window using shallow trays, ice baths, stirring, portioning; never left ambient overnight, never fridge-warmed in bulk. Reheating: 75°C core, once, with leftovers governed by the day-label rules (cooled, labelled, used within the stated window or discarded). Hot-holding and service: 63°C or above, with the 2-hour exception rule known and clocked when used, and the last plate in the furthest room still arriving safe and warm — the service-system design point where safety and ch-001's quality meet." },
      { heading: "People, Premises and Separation", body: "Personal hygiene is trained as triggers, not sentiment: hands washed — properly, at the designated wash-hand basin, which is never used for food or equipment — on entering the kitchen, after raw food, after waste, after cleaning, after the toilet, after breaks, after touching face or hair, before serving; whites or aprons clean daily and changed when soiled; hair covered in preparation areas; nails, jewellery and wounds per the food-handling standard (blue detectable dressings). Fitness rules protect absolutely: gastrointestinal symptoms exclude from food handling until 48 hours symptom-free (mirroring hr-015's exclusion), certain diagnosed infections exclude until cleared, and skin infections on hands and arms are covered or excluded — with the reporting culture protected so nobody hides symptoms to protect a shift. Separation is physical and procedural: the colour-code scheme for boards and knives displayed and enforced, raw meat and fish handled in their zone or their time-slot with full disinfection between, cloths disposable or colour-dedicated and never migrating, fridge geography fixed (ready-to-eat above raw, everything covered and labelled), and the eggs, rice and other named-risk foods handled per their specific rules in the system. The premises carry their share: cleanable surfaces maintained (damage reported — cracked boards and chipped surfaces harbour), the cleaning schedule (appendix) done and signed with clean-as-you-go between, pest vigilance at kitchen strength (saf-040), chemicals stored away from food (COSHH), and equipment on planned maintenance with same-day escalation of failures — the broken fridge, the erratic oven and the dead dishwasher are all incidents with food-safety clocks attached." },
      { heading: "Small Kitchens, Enablement Cooking and When Things Go Wrong", body: "The principles scale without dilution. In supported living flats and small domestic units, staff cooking applies the same core rules — temperatures, separation, hygiene, date discipline — with records simplified to the format the setting sustains (a daily fridge check and cooking log rather than a commercial diary), and shared domestic kitchens risk-assessed for the multi-user hazards commercial kitchens don't have. Enablement cooking — supporting people to cook for themselves, a core of supported living and reablement — holds the rails while sharing the task: the person's right to cook, and to take culinary risks with their own food, is respected within MCA principles; staff maintain the safety-critical elements when cooking FOR someone; and teaching moments (probe use, date labels, handwashing) are support, not surveillance. Residents' and families' own food (the biscuit tin, the brought-in curry) is managed with respect: storage offered, labelling helped, high-risk items conversationally risk-managed, and ch-003's allergen implications for shared items watched. When things go wrong: check failures run their corrective actions and are logged with what-was-done; equipment failures trigger the continuity arrangements (ch-001's resilience); and suspected foodborne illness — symptoms clustering in eaters of a common meal — triggers the full response: care and clinical needs first, the outbreak policy (saf-045) engaged, food samples and records preserved, the EHO informed and cooperated with, notifications per the notifications policy, and an honest investigation whose findings change the system rather than the paperwork." },
    ],
    appendices: [
      { title: "Kitchen Daily/Weekly Check Sheets & Temperature Rules Card", type: "template", body:
"RULES CARD (display): Fridges 0-5°C | Freezers ≤ -18°C | Cook 75°C core | Hot-hold ≥63°C (2-hr rule clocked) | Cool fast (within system window, shallow trays) | Reheat 75°C once | Delivery: chilled ≤8°C (target 5), frozen ≤ -15 (target -18) | Use-by = safety, absolute | Probe: clean & sanitise between uses, calibration check (ice/boiling) monthly\nDAILY SHEET: fridge/freezer temps (AM/PM) | delivery checks (supplier, temp, condition, accepted/rejected) | cooking cores (dish/temp/time/initials) | cooling log (food/start/in-fridge time) | hot-hold temps at service | reheat cores | opened/prepared items day-labelled [ ] | corrective actions taken: ______\nWEEKLY: deep-clean items signed (schedule below) | probe calibration [ ] | stock rotation/date sweep [ ] | structural/equipment issues reported: ______\nRECORDS REAL-TIME ONLY — retrospective completion = falsification (conduct matter)." },
      { title: "Kitchen Cleaning Schedule & Fitness-to-Handle Card", type: "template", body:
"CLEANING SCHEDULE (sign as done — clean-as-you-go between):\nAFTER EACH USE: boards/knives (colour code), prep surfaces, slicers/mixers (stripped), probes\nDAILY: sinks & wash-hand basin, hobs/oven tops, microwaves, floors, bins (empty+clean), cloths replaced, fridge handles/touch points\nWEEKLY: fridges (rotate shelves), oven deep, canopy filters (per rota), storerooms, walls/splashbacks, dishwasher strip\nMONTHLY/PERIODIC: freezers (defrost per plan), high-level, behind equipment, ducting (contractor per cycle)\nCHEMICALS: per COSHH — food-area products, correct dilution, stored away from food\nFITNESS TO HANDLE FOOD: vomiting/diarrhoea → OUT of food handling until 48h symptom-free (report protected — hr-015) | infected cuts on hands/arms → blue detectable dressing or excluded | certain diagnosed infections → excluded until cleared (manager/OH) | visitors & maintenance in kitchen: minimum, supervised, hygiene rules apply" },
    ],
  },
  "ch-003": {
    purpose: "This policy treats every food allergy as the potential emergency it is. Allergic reactions in frail people escalate fast and present atypically; a person with dementia cannot check their own plate; and the distance between a kitchen substitution and an anaphylaxis call is one unread label. The policy builds the chain that keeps allergen information true from admission to plate — and the response that runs when the chain fails.",
    scope: "Covers the 14 regulated allergens and all individually significant allergies and intolerances, in all food the service provides or facilitates: main meals, snacks, drinks, supplements, activities involving food, visitors' contributions and outings. Applies to catering, care and activity staff alike. Read with ch-002 (Food Safety), eff-010 (Dysphagia — the other plate-level safety system) and the emergency response policies.",
    responsibilities: [
      { role: "Registered Manager", duties: [
        "Own the allergen information chain: person-level records accurate from day one, kitchen matrix current, and every link tested by audit",
        "Ensure the two-identifier discipline at service: the right plate reaches the right person by name-and-check, not seat memory",
        "Train everyone who touches food — catering, care, activities, volunteers — in the service's allergen system at their level",
        "Hold the emergency response ready: allergy action plans, adrenaline auto-injectors where prescribed (in date, accessible, staff trained), and the 999-first rule",
        "Investigate every allergen near-miss with the same seriousness as a reaction" ] },
      { role: "Catering Staff", duties: [
        "Maintain the recipe-level allergen matrix and update it the same day any recipe, ingredient or supplier changes — substitutions are re-checked before use, not after",
        "Control cross-contact in preparation: dedicated or fully decontaminated equipment and surfaces for allergen-free versions, preparation sequencing, and honest labelling of what cannot be guaranteed",
        "Label and identify special plates unmistakably through to service" ] },
      { role: "Care & Activity Staff", duties: [
        "Know the allergies of the people they support today — checked, not remembered",
        "Serve with the identification discipline, and never give food (including snacks, treats and activity foods) without knowing it is safe for this person",
        "Manage the informal food economy: visitors' gifts, residents sharing, the biscuit tin — kindly and safely",
        "Recognise reaction signs early and respond per the action plan: in frail people, deterioration may look like collapse, confusion or breathing change rather than textbook hives" ] },
    ],
    keyPoints: [
      "The person-level record is created before the first meal: allergies and intolerances established at pre-admission or day one from the person, family, GP records and transfer documents — distinguishing allergy (immune, potentially anaphylactic) from intolerance (unpleasant, dose-related) because the response differs, recording severity and reaction history, and flagging the record everywhere food decisions happen: kitchen, care plan, dining lists, medication record (drug-food interfaces), activities",
      "The kitchen matrix is recipe-level and living: every dish on the menu mapped against the 14 allergens and the service's additional flagged items, rebuilt when recipes change, re-checked when suppliers substitute (the same product from a different manufacturer is a different allergen profile until the label says otherwise), and available at service so any staff member can answer 'what's in this?' with evidence rather than confidence",
      "Cross-contact is controlled like contamination: allergen-free versions prepared first or in dedicated space with cleaned-and-sanitised equipment, separate utensils and fryers where the allergen demands it (fried gluten and nut oils are classic failures), storage sealed and segregated, and the honest boundary stated — where a kitchen cannot guarantee absence (airborne flour, shared fryers), it says so rather than promising what it cannot deliver",
      "Service is the last line and runs on identification: special plates visibly identified (covers, flags, colour systems) from kitchen to table, matched to the person by positive identification, handovers between kitchen and dining staff naming the plates aloud, and agency and new staff briefed before they serve a single meal — the classic tragedy is the covering staff member and the unlabelled plate",
      "The informal food economy is managed, not ignored: snack trolleys stocked with allergen information, visitors asked about food gifts through a standing conversation (welcome, and here's how we keep everyone safe), residents' sharing watched where cognition makes generosity dangerous, activity and festival foods run through the same matrix, and outings carrying the person's allergy information with them",
      "Emergency response is planned per person: allergy action plans for significant allergies (signs specific to this person, response steps, medication), adrenaline auto-injectors where prescribed stored accessibly (not locked away from the emergency), in-date and staff-trained; the response sequence is position, adrenaline per plan, 999 stating anaphylaxis, second device per plan if no improvement, and nobody stands someone up mid-reaction",
      "Frail presentations are taught explicitly: anaphylaxis in older people may present as sudden collapse, confusion, incontinence or breathing difficulty without dramatic skin signs — the teaching point is that sudden deterioration after eating is treated as possible anaphylaxis until excluded, engaging the deterioration policy's escalation reflexes",
      "Near-misses are gold: the wrong plate intercepted, the substitution caught at the label, the visitor's chocolates spotted — reported without blame, investigated for the chain link that bent, and fed back so the system hardens; a service whose allergen near-miss log is empty is not safe, it is unobservant",
    ],
    legislation: [
      "Food Information Regulations 2014 (allergen information duties, the 14 allergens)",
      "Food Safety Act 1990",
      "Health and Social Care Act 2008 (Regulated Activities) Regulations 2014 — Regulations 12 and 14",
      "Human Medicines (Amendment) Regulations (auto-injector provisions as applicable)",
      "Mental Capacity Act 2005 (choice and risk where capacitous people take dietary risks)",
    ],
    sections: [
      { heading: "The Information Chain", body: "Allergen safety is a chain of custody for information, and the policy names every link. Link one — establishment: the allergy history taken at pre-admission or within the first day, triangulated (the person, family, GP summary, transfer paperwork — which disagree often enough that disagreement is checked, not averaged), severity and past reactions recorded, allergy distinguished from intolerance and from preference (all respected; differently managed), and the record created in the dietary system with review on any new reaction or clinical advice. Link two — distribution: the record propagates same-day to everywhere food decisions happen — the kitchen's person list, the dining room lists, the care plan, handover sheets, the activities team, the medication record where relevant — through the single-route communication discipline (ch-001's sheet), and changes propagate the same way with confirmation. Link three — the kitchen matrix: every recipe mapped against the 14 (celery, cereals containing gluten, crustaceans, eggs, fish, lupin, milk, molluscs, mustard, nuts, peanuts, sesame, soya, sulphites) plus locally significant items, maintained by the cook, verified when ingredients or suppliers change, and consulted — not remembered — when questions arise. Link four — the plate: production matching the matrix, identification travelling with the plate, and positive identification at service. The audit walks the whole chain quarterly: pick a person, trace their allergy from record to today's actual plate, and see where the information bent." },
      { heading: "Kitchen Controls", body: "Production controls make the matrix true on the plate. Ingredients: delivered goods checked against expected labels (supplier substitutions are the classic silent failure — the same-looking product with a new 'may contain'), open ingredients stored sealed and labelled, and the 'may contain' precautionary labels taken at face value for significant allergies rather than risk-assessed away by optimism. Preparation: allergen-free versions cooked first in the day's sequence or in dedicated space, on surfaces and with equipment cleaned and sanitised for the purpose (allergen proteins survive a wipe that would satisfy micro-hygiene — proper wash), utensils dedicated or decontaminated, fryers honest (shared oil is shared allergens), and garnish and finishing disciplined (the pastry brush of egg wash, the scattered nuts, the sauce ladle that visits every plate are all documented failure modes). Labelling and identification: the special plate identified in a way that survives the journey — named cover, flag system, colour code per the service's scheme — with the identification applied at plating, not at the door. And the honesty boundary: where the kitchen cannot guarantee an absence (airborne flour environments for the most sensitive, shared equipment it cannot dedicate), it says so explicitly to the manager, the record notes it, and provision is arranged differently (bought-in sealed products, dedicated preparation) rather than served on a promise the environment cannot keep." },
      { heading: "Service, Daily Life and the Edges", body: "The plate's last metre is the chain's weakest and the policy's strongest teaching point. At service: dining lists at the point of service naming who has what restriction; special plates called through by name between kitchen and dining staff; positive identification before the plate lands (name and check against the list — seat-memory fails on the day the seating changes); and the absolute rule for anyone unsure — hold the plate and ask, because a delayed meal embarrasses nobody into an ambulance. Agency, bank and new staff serve only after the allergen briefing (hr-011's orientation carries it), and volunteers and activity staff follow the same rule for anything edible their sessions involve. Daily life edges are managed with warmth: the visitor conversation is standing and friendly (food gifts welcomed through staff so they can be checked and stored); the resident who shares generously is supported so generosity stays safe; trolley snacks carry their allergen information; festivals and baking activities run their ingredients through the matrix; and outings pack the person's allergy summary with their medication. Capacity threads through: a capacitous person may choose to eat against their intolerance (documented conversation, their right); an allergy with anaphylaxis risk is different territory — the conversation is clinical, the risk is explained, and best-interests machinery engages where capacity is absent. The informal economy cannot be banned, only made visible — and visibility is the policy's realistic target." },
      { heading: "Reaction Response and Learning", body: "Every significant allergy carries an action plan: this person's known triggers, their previous reaction pattern, early signs to watch, the response steps, medication (antihistamines for mild-per-plan; adrenaline auto-injector where prescribed), and the escalation line. Auto-injectors are stored where seconds count — accessible to staff, not locked in the CD cupboard across the building — in date (expiry-tracked like all medicines), and staff are trained on the devices in use, including the practical points (through clothing, hold time, second device timing) and the position rule: lying flat (or seated if breathing demands), legs raised where tolerated, and never stood up or walked mid-reaction, which has killed people whose reaction was otherwise survivable. The response sequence is drilled: recognise (including the frail atypical presentations — sudden collapse, confusion, breathing change after food), position, adrenaline per plan, 999 stating suspected anaphylaxis, stay and monitor, second device per plan if no improvement in the stated window, and hospital assessment always follows adrenaline even when recovery looks complete (biphasic reactions arrive hours later). Afterwards: the incident process with clinical follow-up (GP/allergy service referral for new or changed reactions), notifications per thresholds, the family conversation, and the investigation that walks the chain to find the bent link — record, propagation, matrix, production, or plate — and fixes the system, not just the shift. Near-misses run the same walk with lighter paperwork and equal seriousness, and the governance review reads the log quarterly for the pattern the single events hide." },
    ],
    appendices: [
      { title: "Allergen Chain Audit (quarterly) & Service Identification Rules", type: "checklist", body:
"CHAIN AUDIT (per sampled person — trace end to end):\n[ ] Record: allergies established day 1, triangulated (person/family/GP/transfer), severity & history, allergy vs intolerance distinguished\n[ ] Propagation: kitchen list / dining lists / care plan / handover / activities / meds record all match & current\n[ ] Matrix: today's menu items mapped vs 14 allergens; last supplier-substitution check date; 'may contain' honoured\n[ ] Production: prep sequence/dedicated space & wash standard for allergen-free version; fryer/garnish/finishing discipline\n[ ] Plate: identification applied at plating, survives to table; POSITIVE ID at service (name+list, not seat memory)\n[ ] People: agency/new/volunteers briefed before serving [ ] 'hold and ask' rule known [ ]\nSERVICE RULES CARD: dining list at point of service | special plates called through by name | unsure = HOLD THE PLATE AND ASK | seating changes = list, not memory\nNEAR-MISS LOG reviewed (empty log = unobservant, not safe): findings → chain fix: ______" },
      { title: "Allergy Action Plan & Anaphylaxis Response Card", type: "form", body:
"PERSON: ______  ALLERGENS: ______  Severity/history: ______\nEARLY SIGNS (this person, incl. atypical frail presentations — sudden collapse/confusion/breathing change after food): ______\nMEDICATION: antihistamine (mild, per plan): ____ | ADRENALINE AUTO-INJECTOR prescribed [ ] — location (accessible, NOT locked away): ____ expiry: ____ device type (staff trained [ ])\nRESPONSE SEQUENCE:\n1. Recognise — sudden deterioration after eating = possible anaphylaxis until excluded\n2. POSITION: lie flat (sit if breathing demands), legs raised — NEVER stand/walk them\n3. ADRENALINE per plan (through clothing, hold per device) — time given: ____\n4. 999 — say 'suspected anaphylaxis'\n5. No improvement in ____ min → second device per plan\n6. Stay, monitor, reassure. Hospital ALWAYS follows adrenaline (biphasic risk).\nAFTER: incident process | GP/allergy referral | family | chain investigation (which link bent) | notifications per thresholds\nPlan agreed with (person/family/GP): ______  Review: ______" },
    ],
  },
  "ch-004": {
    purpose: "This policy plans menus for the people actually eating them: nutritionally sound across the cycle, genuinely chosen rather than endured, accurate to every therapeutic and texture prescription, and faithful to the cultures and faiths at the table. It exists because menu planning in care is clinical work wearing an apron — the fortified pudding and the correctly textured meal prevent more admissions than most medications.",
    scope: "Covers menu cycle design and review, therapeutic diets (diabetic-appropriate, renal, low-sodium and others as prescribed), texture-modified food and thickened fluids to IDDSI, fortification and small-appetite strategies, cultural and religious provision, and the clinical interfaces with dietitians, SALT and the nutrition policies (eff-003, eff-010, eff-029).",
    responsibilities: [
      { role: "Registered Manager", duties: [
        "Ensure the menu cycle is planned with nutritional competence — in-house skills, dietetic input, or recognised menu-planning tools — and reviewed on schedule with residents' voices in the review",
        "Hold the accuracy chain for special diets: every prescription (texture, therapeutic, allergen) translated into kitchen instructions and delivered on every plate, every day",
        "Resource fortification properly: the ingredients and time food-first approaches need",
        "Ensure cultural and religious provision is planned into the cycle for the current residents, not improvised around it" ] },
      { role: "Catering Staff", duties: [
        "Cook the cycle with the substitution discipline: changes checked against allergens, textures and therapeutic requirements before the pan, not after the plate",
        "Prepare texture-modified food to the IDDSI level prescribed — tested, not eyeballed — and presented as food, not process",
        "Deliver fortification invisibly: enriched, not obviously medicalised",
        "Know the therapeutic diet rules well enough to catch errors upstream" ] },
      { role: "Care Staff", duties: [
        "Serve the right diet to the right person (ch-003's identification discipline covers textures and therapeutic diets equally)",
        "Report intake honestly (eff-030's records) — menu planning runs on true data",
        "Support choice at the point of eating for people whose decisions live in the moment" ] },
    ],
    keyPoints: [
      "The cycle is planned, varied and honest: a menu cycle (commonly 4 weeks, seasonal variants) covering all meals and snacks, nutritionally checked against recognised standards for older adults in care (energy and protein density mattering more than general-population 'healthy eating' for most residents), varied enough that week three doesn't taste like week one, and built from dishes the population actually eats — heritage cooking, familiar formats, and the modern tastes younger cohorts bring",
      "Older-adult nutrition inverts the leaflets: for most care populations the risk is undernutrition, so menus default to energy-and-protein density (whole milk, butter, cream, fortified baking) with 'healthy eating' restrictions applied only where clinically indicated for the individual — the low-fat spread on a losing-weight 90-year-old's toast is a clinical error, not a virtue",
      "Therapeutic diets are prescriptions: diabetic-appropriate provision (regular carbohydrate, no 'diabetic products', hypo-treatment interface), renal, low-sodium, gluten-free (coeliac is not a preference), and the rest arrive with clinical authority, are translated into kitchen rules, and are delivered with the same accuracy discipline as medication — and liberalisation is real too: end-of-life and quality-of-life decisions properly made can relax therapeutic restrictions, documented through the clinical route",
      "IDDSI is the texture language and it is exact: levels 0-7 for fluids and foods per the SALT prescription, kitchen-tested with the recognised methods (flow, fork, spoon tests) rather than judged by eye, prepared without cross-level drift (the 'slightly thick soup' that is actually thin is an aspiration event), and every texture change flowing from SALT review, not kitchen convenience or care-floor improvisation",
      "Texture-modified food keeps its dignity: moulded and presented as recognisable food (the pureed roast shaped as roast, not three beige scoops), seasoned like real cooking, served with the same choice as standard meals — the level 4 eater gets two options too — and fortified by default, because texture modification strips energy density exactly when eating is hardest",
      "Fortification is food-first and systematic: enrichment built into cooking (milk powder into milk, cream and butter into mash, cheese into sauces, fortified puddings and milkshakes as standard offer) for everyone flagged by MUST (eff-029), with oral nutritional supplements as the clinical addition where food-first isn't closing the gap — prescribed, recorded, and reviewed rather than parked on the trolley forever",
      "Culture and faith are menu features, not exceptions: kosher, halal (sourced and handled credibly, not just labelled), vegetarian and vegan provision as full menus rather than the daily omelette, fasting seasons (Ramadan meal timing shifts) planned with the person, and festival foods cooked for the festivals the residents keep — with the person's own definition of their observance governing, established at admission",
      "The clinical loop closes monthly: menu planning meets the nutrition data — MUST scores, weight trends, intake records, plate waste, SALT and dietetic changes — so the cycle evolves with the population rather than outliving it",
    ],
    legislation: [
      "Health and Social Care Act 2008 (Regulated Activities) Regulations 2014 — Regulation 14",
      "Food Information Regulations 2014 (interfaces with ch-003)",
      "Equality Act 2010 (religious and cultural provision)",
      "Mental Capacity Act 2005 (choice, liberalisation and best-interests decisions)",
      "NICE guidance on nutrition support in adults (CG32 principles)",
    ],
    sections: [
      { heading: "Designing the Cycle", body: "The cycle is designed as a piece of clinical and cultural engineering. Inputs: the current population's profile (ages, cultures, therapeutic diets, texture levels, the MUST caseload), preference data (admission conversations, food forum output, plate-waste patterns), seasonal produce and budget reality, and kitchen capacity (a menu the kitchen cannot execute on its worst-staffed day is a fiction). Standards: nutritional adequacy checked against recognised older-adult care standards — energy and protein density led — with the day's whole provision counted (the 24-hour food day of ch-001, snacks and supper included, because the gap analysis that only counts lunch misses where undernutrition lives). Structure: commonly four weeks with seasonal editions; two genuine choices at main meals plus the standing alternatives; puddings twice daily where custom expects them (pudding is a fortification vehicle wearing a treat's clothes); and the fortified baseline cooked in rather than added after. Every dish is written with its recipe, portion guide, allergen mapping (ch-003's matrix is built here) and its texture-modification derivative — designing the level 4 version at menu stage, not improvising it at lunch. Review: the cycle is reviewed on schedule (at least twice yearly) and event-driven (population change, waste patterns, clinical input), with residents in the review through the forum and the taste tests that make review honest." },
      { heading: "Therapeutic Diets Done Properly", body: "Therapeutic diets run on a prescription chain: clinical origin (GP, dietitian, specialist team) → dietary record and care plan → kitchen instruction translated into dish-level rules → plate-level delivery with identification (ch-003's service discipline covers all special plates). The house rules for the common prescriptions are written into the kitchen file: diabetes — regular, consistent carbohydrate across meals, no 'diabetic' specialty products (outdated and gastro-punishing), normal puddings in managed portions rather than exclusion (exclusion drives the secret biscuit economy), and the interface with hypo treatment and monitoring (eff-021); renal and low-sodium — the restriction lists and the flavour craft that stops restricted food tasting like punishment; gluten-free — coeliac rigour with cross-contact controls borrowed from allergen practice; low-potassium, fluid restrictions and the rarer prescriptions — per the clinical instruction, with the kitchen asking rather than guessing at edges. Two disciplines protect the whole chain: substitutions in cooking are checked against every active prescription before use; and liberalisation is honoured as clinical practice — where end-of-life care, advanced dementia or a documented quality-of-life decision relaxes a restriction, the relaxation is recorded and served without moral commentary, because the 92-year-old's unrestricted éclair can be the best clinical decision on the ward." },
      { heading: "Texture Modification and IDDSI", body: "Texture safety runs from SALT prescription to plate with no improvisation in between. Prescriptions: every texture-modified eater has a current SALT recommendation in IDDSI terms (drinks 0-4, foods 3-7 including transitional), recorded in the dietary system, communicated to the kitchen through the single route, and reviewed on the clinical cycle or on any swallowing change — with the care floor's observations (coughing at meals, wet voice, prolonged meals) feeding the eff-010 escalation that triggers review, and never triggering DIY texture changes. Preparation: the kitchen prepares to level using tested methods — thickeners dosed per product instructions and checked with flow/fork/spoon testing, not appearance; blended foods passed to smoothness where the level requires; particle sizes measured against the level's definitions for minced and soft-bite; bread and high-risk formats handled per the level's rules — and batch consistency verified because the second ladle from a settling pot is not the first. Presentation: moulds, layering and piping that keep pureed food looking like the meal everyone else is having, seasoning as craft, fortification as default (see above), and the same two-choice offer as the standard menu. Fluids: thickened drinks prepared to level, labelled, and fresh (thickness drifts over time), with the drinks round trained on levels and the danger of the well-meant 'normal' cup. The audit tests plates, not paperwork: quarterly, sampled texture-modified meals and drinks are level-tested at the point of service." },
      { heading: "Small Appetites, Culture and the Closing Loop", body: "For the shrinking appetite, strategy replaces exhortation: fortification as the invisible baseline (energy added to what the person already accepts beats new products they refuse); little-and-often as a service pattern (the six small opportunities of the 24-hour day outperform three large confrontations); finger foods for people who walk, graze or refuse cutlery (a designed finger-food menu is a dementia-care tool, not a compromise); favourite-food licence for the person for whom anything eaten is a win; and the eating-environment and support factors that ch-005 owns. Supplements enter clinically: when food-first strategies are delivering their maximum and the gap persists, prescribed ONS with recording, review, and exit criteria — not as a permanent trolley fixture that replaces cooking effort. Cultural and religious provision is engineered into the cycle: sourcing with credible certification where faith requires it (halal, kosher — supplier evidence held), preparation respecting the rules that matter (separation, utensils where applicable), fasting observances planned individually (Ramadan's shifted meal times, the clinical conversation where fasting and frailty conflict, the person's own choice governing within capacity), festival menus cooked as celebrations, and the admission conversation establishing each person's own observance level rather than assuming from a name. The loop closes monthly: the nutrition meeting reads MUST movement, weight trends, intake records, waste data, SALT/dietetic changes and forum feedback against the current cycle — and the cycle changes, because a menu that never learns is a menu slowly going wrong." },
    ],
    appendices: [
      { title: "Special Diet Prescription-to-Plate Record", type: "form", body:
"PERSON: ______\nTHERAPEUTIC: prescription (source/date): ____ | kitchen rules (dish-level): ____ | liberalisation decision (clinical route, date): ____\nTEXTURE (IDDSI): drinks level ____ foods level ____ (SALT, date: ____) | review cycle/trigger review on swallowing change [ ] | kitchen method (thickener dose/tests used): ____ | presentation standard (moulded/choice offered) [ ] | fortified by default [ ]\nALLERGENS: see ch-003 matrix & plan (ref: ____)\nFORTIFICATION/SMALL APPETITE: MUST score/trend: ____ | food-first strategies (fortified baseline/little & often/finger foods/favourites): ____ | ONS (prescribed, exit criteria, review): ____\nCULTURE/FAITH: person's OWN observance (admission conversation): ____ | sourcing (certification evidence): ____ | fasting plan: ____\nIDENTIFICATION AT SERVICE: method: ____ (ch-003 discipline)\nMonthly nutrition meeting review (date/changes): ______" },
      { title: "IDDSI Kitchen Card & Menu Cycle Review", type: "template", body:
"IDDSI CARD (display in kitchen):\nDRINKS: 0 thin | 1 slightly | 2 mildly | 3 moderately (liquidised) | 4 extremely thick — dose thickener per product, verify by FLOW TEST, fresh (thickness drifts), label cup\nFOODS: 3 liquidised | 4 pureed (spoon tilt test, no lumps, moulded & presented) | 5 minced & moist (4mm, fork test) | 6 soft & bite-sized (15mm, fork-mash) | 7 easy chew/regular\nRULES: SALT prescription only — NO kitchen/floor improvisation | batch consistency checked (stir before second ladle) | bread & high-risk formats per level rules | fortify TM food by default | 2 choices at TM levels too\nQUARTERLY PLATE AUDIT: sampled TM meals/drinks level-tested at service (date/results): ______\nMENU CYCLE REVIEW (2x yearly + event-driven): population profile change | MUST/weight trends | intake & waste data | SALT/dietetic changes | forum & taste tests | cultural provision current | kitchen executability | → cycle changes made: ______" },
    ],
  },
  "ch-005": {
    purpose: "This policy protects the two or three hours a day when the whole service gathers around food — because mealtimes done well deliver nutrition, society, rhythm and joy in one sitting, and mealtimes done badly deliver undernutrition, indignity and the loneliest moments of an institutional day. The plate matters (ch-001 to ch-004 govern it); this policy governs everything around the plate.",
    scope: "Covers the dining environment, mealtime organisation and staffing, protected mealtimes as this service operates them, eating and drinking support, dementia-attuned dining, monitoring and escalation of eating changes, and flexibility for people whose needs or preferences run differently. Read with eff-003 (Nutrition & Hydration), eff-010 (Dysphagia), eff-030 (Food & Fluid Recording) and cop-006 (Choking).",
    responsibilities: [
      { role: "Registered Manager", duties: [
        "Staff mealtimes as the care peak they are: enough hands for the support needs at the table, rosters and break patterns built around meal service, and no avoidable interruptions scheduled against food",
        "Set the dining standard — environment, table settings, pace, noise — and walk it at real mealtimes regularly",
        "Operate protected mealtimes intelligently: interruptions minimised, but families who help at meals welcomed as the asset they are",
        "Ensure eating-support needs are assessed, planned and delivered per person, and monitored for change" ] },
      { role: "All Staff", duties: [
        "Treat mealtime duty as care delivery, not supervision: sitting, engaging, supporting, noticing",
        "Give eating support at the person's pace — the fed person sets the tempo, the supporter matches it, and no fork moves faster than the person's swallow",
        "Notice and report the quiet signals: portions declining, the meal taking longer, coughing at drinks, the person who stopped coming to the dining room",
        "Protect dignity in every support decision: clothing protection chosen with the person, discreet help, adult language — 'apron' not 'bib', support not 'feeding'" ] },
    ],
    keyPoints: [
      "The environment invites eating: tables laid properly (cloths, real crockery and glassware within risk sense, condiments present), lighting and contrast that ageing and dementia-affected eyes can use (food visible against plate, plate against table), noise managed (television off as default at meals, music if residents choose it), smells of cooking allowed to do their appetite work, and the room arranged so wheelchairs and walking aids fit without ceremony",
      "Mealtimes are staffed as the care peak of the day: support needs mapped per table per sitting (who needs full support, prompting, cutting-up, encouragement), staffing rostered to the map, breaks scheduled around service, and everyone — including seniors and managers — available to the dining room at the peak",
      "Protected mealtimes are applied with sense: non-urgent clinical tasks, visits from professionals, cleaning and maintenance are kept off the mealtime; families and volunteers who help someone eat are welcomed in — the target is interruption, not company",
      "Eating support is assessed, personal and paced: each person's support level in their plan (independent with the right equipment / prompting and encouragement / partial help / full support), adaptive equipment provided and maintained (plate guards, angled cutlery, two-handled and spouted-when-chosen cups, non-slip mats), one supporter per person during full support (not alternating spoonfuls between two people), seated at eye level, offering choice within the meal (the fork asks: this or that first?), and never rushing — the unfinished meal rushed away is a portion of malnutrition served by the rota",
      "Dementia dining has its own craft: contrasting crockery (plain, coloured plates beat patterned white), one course at a time to reduce overwhelm, show-plates and visible choice at the point of decision, finger-food menus for people who walk or won't sit (ch-004), eating together (staff eating alongside normalises and cues), tolerance of unconventional eating as success rather than mess, and the walking eater fed by opportunity — the sandwich offered on the move counts",
      "Positioning and swallow safety frame every supported meal: upright, supported, chin per SALT guidance, in the chair the assessment names (eating in bed only where unavoidable and then positioned properly), alertness checked before the first mouthful (the drowsy person is not fed until awake), textures per prescription (ch-004), pace per the person, and the choking response (cop-006) known by everyone in the room",
      "Change is noticed at the table first: falling intake, slowing pace, new coughing or throat-clearing, food pocketed in cheeks, weight visibly shifting, the social eater gone quiet — all reportable observations feeding eff-030's records, MUST reviews (eff-029), SALT referrals (eff-010) and the deterioration lens (eff-023), because the dining room is the service's best early-warning system",
      "Flexibility is the dignity backstop: breakfast when people wake (not when the trolley dictates), the lie-in honoured with a late breakfast that is a real one, meals in rooms by genuine choice (with the isolation risk watched, not ignored), the night owl's supper, second sittings and kept-warm plates for the person whose morning ran differently — the service fits mealtimes to people, not people to mealtimes",
    ],
    legislation: [
      "Health and Social Care Act 2008 (Regulated Activities) Regulations 2014 — Regulations 9, 10, 14",
      "Mental Capacity Act 2005 (eating choices, support decisions)",
      "Human Rights Act 1998 (Article 8 — dignity in intimate support)",
      "NICE guidance on nutrition support (CG32 principles)",
      "Care Act 2014 (wellbeing)",
    ],
    sections: [
      { heading: "The Room and the Rhythm", body: "The dining experience is designed like the care intervention it is. Before service: tables laid with intention — cloths or quality settings, real crockery (adapted where needed, but adapted crockery can still be attractive), glasses rather than universal beakers (beakers by assessment and choice, not by default), condiments and sauces on the table because seasoning one's own food is agency; the room ventilated, lit for ageing eyes (bright, even, glare-managed), and quiet enough for conversation — the television off unless residents genuinely want it, since a room shouting news at itself is not company. The rhythm: mealtimes anchored at familiar hours with genuine flexibility at the edges (the late riser's real breakfast); a pre-meal pause that lets the room settle (toileting and hand-washing offered, hands cleaned, glasses on, dentures in, hearing aids working — the ready-to-eat checklist that turns out to be half of intake); service paced so courses arrive as people finish rather than stacking; and the meal allowed its full length — the room is not cleared around the last eaters, and pudding is not withheld from the slow. Staff presence is hospitable: seated at tables where culture and ratios allow, eating alongside where the service adopts it (powerful modelling in dementia care), and never talking over heads about residents as though the table were furniture." },
      { heading: "Support at the Table", body: "Every person's eating support is assessed into their plan and delivered as written. The support spectrum: full independence honoured (help not imposed on the slow-but-managing — struggle with dignity beats efficient dependence, and intervention is offered, not inflicted); enabling support (the right cutlery, the plate guard, the cut-up done in the kitchen so the plate arrives ready rather than being dismembered at the table); prompting and cueing (verbal encouragement, the demonstrated first bite, hand-under-hand guidance where welcomed); and full support, which is the most intimate care of the day and treated accordingly — one supporter per person, seated at eye level and to the person's stronger side, introducing the meal ('it's the fish today — shall we start with that or the potatoes?'), loading the fork with proper mouthfuls, matching the person's rhythm with genuine pauses, offering drinks through the meal, conversation as part of the service (mealtime chat is the point, not a distraction from throughput), and stopping when the person indicates enough — with refusals reported, not overridden. Dignity details are policy: clothing protection in adult forms chosen with the person; wiping done gently and asked-first; dentures, glasses and hearing aids checked as pre-meal routine; and language throughout — support, not feeding; the person's name, not the diet's ('table two's puree' is a phrase this policy bans from the dining room)." },
      { heading: "Dementia and the Different Eaters", body: "Dining with dementia rewards craft over correction. Perception: contrast is intake — plain crockery in colours that separate food from plate and plate from table measurably improves eating; patterned plates scatter attention; one course at a time prevents the overwhelm that ends meals early. Decision: choice is offered at the moment of eating with the options visible (show-plates, both plates brought, the pointing menu), because the choice made yesterday is gone and the menu read aloud may not land. Initiation: some people need the cue — the first bite guided, the mirror of a staff member eating the same thing, the fork placed in hand; some eat socially who will not eat alone; some eat walking who will not sit, and the finger-food menu (ch-004) exists exactly for them, served by opportunity through the day. Tolerance: eating with hands, mixing foods, unconventional orders and pace are all success when the calories land — the mess is laundry, the intake is life, and staff are trained to read it that way. The different eaters beyond dementia get their versions: the person who eats in their room by real choice (respected, with the isolation question kept live and the tray standard equal to the dining room's); the breakfast-at-ten riser; the couple who dine together; the person fasting for faith; the end-of-life eater for whom taste, comfort and preference outrank targets entirely (eff-004's territory, honoured at the table)." },
      { heading: "Watching, Escalating and Governing", body: "The dining room is the service's richest observation post, and the policy makes watching a duty. Table-level vigilance: intake watched and recorded honestly where records are prescribed (eff-030 — 'ate well' is not a record; halves and quarters are), pace and effort noticed, swallow signals (coughing, throat-clearing, wet voice, pocketing) reported same-day into the eff-010 route, alertness and mood at meals tracked as the clinical signals they are, and the social map watched — the regular who stopped coming to lunch is a welfare flag, not a rota relief. Escalation runs on the established rails: MUST and weight review (eff-029), SALT referral on swallow signals, GP and deterioration escalation (eff-023) where decline is broader, and the mealtime observations feeding each. Governance walks the floor: the manager and seniors present at real mealtimes weekly at minimum — eating the food (ch-001), watching the support quality, counting the interruptions protected mealtimes should have prevented — and a structured mealtime observation audit runs quarterly (environment, staffing versus the support map, support quality and pace, dignity details, dementia craft, recording honesty), with findings owned and re-walked. The closing standard is the visitor test, stated plainly: if a daughter watching Tuesday lunch would go home reassured, the policy is working; if she would go home and phone the safeguarding line, no audit score matters." },
    ],
    appendices: [
      { title: "Mealtime Support Map & Ready-to-Eat Checklist", type: "template", body:
"SUPPORT MAP (per sitting/table — rostered against): person | support level (independent / equipment (list) / prompting / partial / FULL — 1:1) | texture & diet flags (IDDSI/therapeutic/allergen refs) | positioning & chair | preferences (pace, order, company) | supporter allocated\nSTAFFING CHECK: peak-hands rostered [ ] breaks off-peak [ ] seniors/manager available at peak [ ]\nREADY-TO-EAT (pre-meal, per person): toileting offered | hands cleaned | glasses ON | dentures IN | hearing aids working | positioned upright per plan | ALERT before first mouthful (drowsy = wait)\nPROTECTED MEALTIME: non-urgent clinical/professional/cleaning tasks OFF the mealtime [ ] | helping families & volunteers WELCOMED [ ]\nDIGNITY CARD: adult clothing protection, chosen with person | ask-first wiping | eye-level seated support | person's name, never the diet's | no talking over heads | meal takes the time it takes" },
      { title: "Mealtime Observation Audit (quarterly)", type: "checklist", body:
"ENVIRONMENT: tables laid (cloths/crockery/glasses/condiments) [ ] lighting & contrast (dementia crockery in use) [ ] noise (TV off default) [ ] room accessible [ ]\nSTAFFING vs SUPPORT MAP: hands match needs [ ] full-support 1:1 honoured [ ] breaks not at peak [ ]\nSUPPORT QUALITY: pace matches person (no fast forks) [ ] choice offered at point of eating (visible options) [ ] prompting/cueing before takeover [ ] refusals respected & reported [ ] drinks through the meal [ ]\nDEMENTIA CRAFT: one course at a time | show-plates | finger foods served by opportunity | eating-alongside used | unconventional eating tolerated as success\nSAFETY: positioning per plans | alertness checked | textures verified at table (spot vs ch-004) | choking response known (ask 2 staff) [ ]\nWATCHING: intake recorded honestly (fractions, not 'ate well') | swallow signals reported (route known) | absent regulars flagged [ ]\nFLEX: late breakfasts real | room trays equal standard | second sittings work [ ]\nVISITOR TEST verdict + actions owned: ______" },
    ],
  },
};
