// Ziproh Compliance — 2026 Expansion Set E (Group 7: Domiciliary Care & Supported Living)
// All content original. Written tailoring-ready (generic base terms adapt per care setting).

import type { Document, DocumentContent } from "./documents";

export const EXPANSION_2026E_DOCS: Document[] = [
  {
    id: "dc-001",
    title: "Access to People's Homes Policy",
    category: "Safe", subcategory: "Community Care Operations", keyQuestion: "Safe",
    serviceTypes: ["Domiciliary Care", "Supported Living"], regulators: ["CQC", "CI", "CIW", "RQIA"],
    version: "1.0", lastUpdated: "2026-07-15", status: "updated", readTime: 11,
    tags: ["home access", "entry", "consent", "doorstep identification", "refused entry", "security"],
    summary: "Entering people's homes as guests with duties: agreed entry arrangements documented per person, doorstep identification every visit, what staff may and may not do inside someone's home, refused entry handled with respect and escalation, and the security of the home protected on every departure.",
  },
  {
    id: "dc-002",
    title: "Keysafe & Keys Management Policy",
    category: "Safe", subcategory: "Community Care Operations", keyQuestion: "Safe",
    serviceTypes: ["Domiciliary Care", "Supported Living"], regulators: ["CQC", "CI", "CIW", "RQIA"],
    version: "1.0", lastUpdated: "2026-07-15", status: "updated", readTime: 10,
    tags: ["keysafe", "keys", "codes", "key log", "security breach", "code changes"],
    summary: "The keys to people's homes held with bank-vault discipline: the key and code register, code confidentiality rules that survive staff turnover, physical keys signed in and out, code changes on triggers, breach response when a code or key may be compromised, and the audit that proves custody.",
  },
  {
    id: "dc-003",
    title: "Missed & Late Calls Policy",
    category: "Safe", subcategory: "Community Care Operations", keyQuestion: "Safe",
    serviceTypes: ["Domiciliary Care", "Supported Living"], regulators: ["CQC", "CI", "CIW", "RQIA"],
    version: "1.0", lastUpdated: "2026-07-15", status: "updated", readTime: 12,
    tags: ["missed calls", "late calls", "call monitoring", "welfare checks", "criticality ratings", "notifications"],
    summary: "The safety net under every scheduled visit: criticality ratings that know whose 8am call is insulin and whose is company, real-time lateness detection and communication, the missed-call response ladder through to welfare checks, honest notification when the service fails, and pattern analysis that fixes rosters rather than apologising repeatedly.",
  },
  {
    id: "dc-004",
    title: "Electronic Call Monitoring (ECM) Policy",
    category: "Well-Led", subcategory: "Community Care Operations", keyQuestion: "Well-Led",
    serviceTypes: ["Domiciliary Care", "Supported Living"], regulators: ["CQC", "CI", "CIW", "RQIA"],
    version: "1.0", lastUpdated: "2026-07-15", status: "updated", readTime: 11,
    tags: ["ECM", "call monitoring", "logging", "data protection", "commissioner reporting", "system failure"],
    summary: "Call monitoring run as a safety system first and a billing system second: accurate logging in and out as the trigger for the missed-call net, honest data (no remote logging, no gaming), proportionate use of workforce location data, system-failure fallbacks, and ECM data used to improve rosters rather than merely surveil staff.",
  },
  {
    id: "dc-005",
    title: "Travel Between Calls Policy",
    category: "Well-Led", subcategory: "Community Care Operations", keyQuestion: "Well-Led",
    serviceTypes: ["Domiciliary Care", "Supported Living"], regulators: ["CQC", "CI", "CIW", "RQIA"],
    version: "1.0", lastUpdated: "2026-07-15", status: "updated", readTime: 10,
    tags: ["travel time", "rostering", "call cramming", "driving safety", "mileage", "working time"],
    summary: "Travel time as the honesty test of a community roster: realistic travel built into every run (rushed travel becomes clipped calls and dangerous driving), working-time and pay treatment stated plainly, winter and rural adjustments, vehicle standards for work driving, and the roster analytics that catch call-cramming before staff burn out.",
  },
];

export const EXPANSION_2026E_CONTENT: Record<string, DocumentContent> = {
  "dc-001": {
    purpose: "This policy governs the moment community care becomes intimate: crossing someone's threshold. Staff enter homes as guests carrying professional duties — invited by arrangement, identified at the door, respectful of the household's rules, and leaving the home as secure as they found it. The policy protects both directions: the person from intrusion and the worker from misunderstanding.",
    scope: "Covers entry arrangements for every person supported at home: agreed access methods, doorstep identification, conduct inside the home, other household members, refused and failed entry, emergency entry considerations, and departure security. Keys and keysafes have their own policy (dc-002); missed-call escalation is dc-003's; personal safety is hr-026/saf-007's.",
    responsibilities: [
      { role: "Registered Manager", duties: [
        "Document each person's entry arrangement at assessment — how staff get in, who else may be present, household rules — and keep it current in the care plan and the roster system",
        "Issue photo ID to all community staff and publish the verification line households can call",
        "Ensure refused-entry and no-answer responses are trained and followed (dc-003's ladder for no-answer; this policy's respect-and-escalate for refusal)",
        "Review entry arrangements when circumstances change: new household members, cognitive change, safeguarding concerns, tenancy changes" ] },
      { role: "Community Staff", duties: [
        "Identify themselves at the door every visit — ID shown, name given — regardless of familiarity, and support the household's right to check",
        "Enter only by the agreed method: no improvised entries, no climbing through windows, no borrowed keys from neighbours outside the plan",
        "Respect the home: the household's rules (shoes, smoking, rooms not entered), possessions untouched beyond care need, privacy of everything seen",
        "Secure the home on leaving: doors locked per arrangement, keys returned per dc-002, alarms set where agreed, and vulnerable people never left with the door swinging" ] },
    ],
    keyPoints: [
      "Entry is by agreement, documented: each person's arrangement — answers the door themselves, keysafe (dc-002), key held (dc-002), door left unlocked by choice (recorded with the risk conversation), family lets in, warden/scheme access — is recorded at assessment, reviewed on change, and visible to every worker on the run including covering staff",
      "Identification is every visit, not first visits: photo ID presented at the door with name and service given, new workers introduced by phone or in person ahead where the person's anxiety or cognition benefits, and the service's verification number printed on the ID so a doubtful household can phone and check — with staff coaching the habit ('you can always ring to check it's really us') rather than resenting it",
      "The doorstep pause is a safety habit both ways: before entering, a moment's read — is the door damaged, is a stranger answering, does something feel wrong (hr-026's withdrawal rule applies at the threshold, not just inside) — and for the household, time to verify before the threshold is crossed",
      "Inside, staff are guests with a job: the household's rules honoured (shoes off, the front room not used, the dog shut away by them not us), movement limited to the rooms care requires plus what the person invites, cupboards and drawers opened only for care tasks and with narration ('I'm getting your towels'), nothing borrowed, nothing moved without reason, and the home's contents — however they strike the visitor — respected as choices unless they become the safeguarding or environment-risk conversation the proper policies own",
      "A capacitous refusal at the door is respected and escalated in one motion: the person's right to say 'not today' is honoured without argument, the offered care is documented as declined, the critical elements (medication due, insulin, pressure care) trigger the same-day clinical escalation the care plan names, patterns trigger review (is the refusal free, engineered by someone, or a symptom?), and the door is never forced by persuasion-pressure that shades into coercion",
      "No-answer is never walked away from: the dc-003 ladder runs (knock-and-wait protocol, phone, listen and look — the milk on the step, the curtains, the sounds — contacts, escalation to welfare check), because the difference between 'not in' and 'on the floor' is invisible from a closed door",
      "Other people in the home are managed by plan: household members and regular visitors noted in the arrangement, care delivered with the person's privacy protected even from family where they wish, workers never left alone with children as a service function, and new or concerning presences (the stranger who answers, the 'friend' who controls the door) reported same-day as the safeguarding-relevant observations they are",
      "Departure is a security checklist: the person settled as the visit plan intends, door secured per arrangement, keys/codes handled per dc-002, alarms and telecare re-armed where agreed, and the next contact confirmed with the person where cognition benefits ('Sarah comes at teatime')",
    ],
    legislation: [
      "Human Rights Act 1998 (Article 8 — home and private life)",
      "Mental Capacity Act 2005 (entry and refusal decisions)",
      "Health and Social Care Act 2008 (Regulated Activities) Regulations 2014 — Regulations 9, 10, 12",
      "Care Act 2014 (wellbeing, safeguarding)",
      "Criminal Law Act 1977 (the entry boundary — staff have no right of forced entry)",
    ],
    sections: [
      { heading: "The Entry Arrangement", body: "Every person's file answers the door question before the first visit: the method (self-answer, keysafe with code custody per dc-002, held key, family or scheme access, or the person's documented choice to leave the door unlocked — recorded with the risk conversation and revisited as vulnerability changes), the approach (which door, parking that doesn't block the neighbour, the knock-then-bell rhythm that gives a slow walker time), who else lives there or may be present, household rules the person sets, pets and their arrangements, and the no-answer information dc-003's ladder will need (nearest contacts, telecare provider, GP surgery, known routines — the day centre on Tuesdays that explains the empty house). The arrangement is agreed with the person (and family where they're involved), written into the care plan, surfaced in the roster system so covering workers see it before they arrive, and reviewed at care plan reviews and on trigger events: cognitive change (the person who now can't answer needs a new method before the crisis, not after), new household members, safeguarding concerns, or the person's own request. Staff never invent access: the window left ajar, the neighbour's spare key outside the plan, the back door 'we always use' that nobody documented — every improvised entry is an incident waiting for its day in a serious case review." },
      { heading: "The Doorstep", body: "Identification discipline holds at every door, every time: ID worn and shown, name and service spoken ('Morning Mrs A, it's James from [service]'), and the pace set by the person's needs — the anxious household gets the phone-ahead ('James is five minutes away, blue jacket'), the new face gets introduced on a shared visit or by photo in advance where the plan says so, and cognitive impairment gets the same script every visit because familiarity lives in rhythm. The verification habit is actively taught: at assessment the service explains the ID, gives the office number for checking, and normalises suspicion ('never let anyone in who won't show ID or wait while you phone — including us'), because the people this service supports are the exact demographic distraction burglars target with fake gas boards and fake carers. The doorstep works both ways: staff pause and read before entering — damage to the door, an unfamiliar answerer, sounds of conflict, the gut-feel wrongness hr-026 protects — and the withdrawal rule applies at the threshold: conduct the doorstep conversation, step back, phone the office, and let the service solve what the lone worker shouldn't. Refusals at the door are met with respect and process: no argument, no foot in the door, the visit's purpose gently stated once ('I've got your lunchtime tablets — shall I leave them?'), the refusal documented with the person's state noted, critical-care elements escalated same-day per the plan's clinical flags, and repeated refusals triggering review rather than roster-relief — a pattern of refusals is a message needing decoding: depression, a controlling household member, a worker mismatch, or a service the person no longer wants, each with its own proper response." },
      { heading: "Inside the Home", body: "Conduct inside is guest-discipline with professional edges. Territory: staff work in the rooms care requires and those the person invites them into; bedrooms and bathrooms are workplaces during care and private rooms otherwise; and searches of any kind (the missing purse, the hidden medication) happen with the person or their authority, never solo initiative. Possessions: touched for care purposes with narration where capacity clouds understanding, never borrowed or used (the phone call on the person's phone, the toilet used without asking — small trespasses that corrode trust), and damage owned immediately per ch-009's honesty. Household rules: kept as given — the shoes, the smoking rules (staff never smoke in any client home regardless of the household's own habits, hr-025/saf-042), the rooms not entered, the way she likes the milk bottles — because compliance with small rules is how respect is performed daily. The environment itself: observed but not judged — clutter, cold, dilapidation and hoarding are recorded and escalated through the home-environment risk and wellbeing routes (Group 7's later policies) rather than 'tidied' unilaterally, and staff opinions about how people live stay professional: the home is theirs, the standards conversation belongs to assessment and care planning, not to sighs and rearrangement. Other people: care delivered with the person's chosen privacy (the daughter asked to step out during personal care if that's the person's wish — the person's, not the daughter's), unfamiliar presences noted and reported, any door-controller or answer-preventer treated as a safeguarding flag, and staff protecting their own boundaries per the conduct policies (no personal errands for household members, no cash handling outside ch-006-style arrangements, no private arrangements)." },
      { heading: "Leaving, and the Edge Cases", body: "Departure has its checklist because the last two minutes secure the next twelve hours: the person left as the visit plan intends (positioned, call bell or phone in reach, drink placed, the fire risks of the visit's activities closed — the hob, the candle); the record made before or immediately after leaving per the recording rules; the door secured by the arrangement (locked and checked, keysafe closed and scrambled per dc-002, alarms re-armed); and the next-visit anchor given where it helps ('teatime, it'll be Priya'). The edge cases get pre-decided answers. Emergency entry: staff have no right of forced entry — where the ladder reaches genuine emergency (the person visible on the floor, calls for help heard), 999 takes the decision and the door (police and ambulance hold the powers and the shoulders), with staff supporting entry rather than performing it save in the immediate-life-threat judgement call the law's necessity principles would defend and the debrief will review kindly. Locked-out and lost-key events run dc-002's breach machinery. The person found in crisis behind an opened door runs the emergency and clinical policies with the home secured behind the ambulance. And the visit that ends with staff unable to leave safely — the aggressive relative arriving, the dog loose in the hall — runs hr-026's withdrawal and escalation with the office solving the exit, because the guest-with-duties frame holds to the last: staff owe the household respect, and the service owes its staff a way home." },
    ],
    appendices: [
      { title: "Entry Arrangement Record (per person)", type: "form", body:
"PERSON: ______  Address: ______  Review due / triggers: cognitive change, new household member, safeguarding, person's request\nENTRY METHOD: self-answers (knock rhythm/time to reach door: ____) | keysafe (dc-002 ref) | held key (dc-002 ref) | family/scheme access: ____ | unlocked by person's choice (risk conversation recorded: date ____)\nAPPROACH: door to use | parking notes | phone-ahead? [ ] | new-worker introduction method (shared visit/photo/phone): ____\nHOUSEHOLD: who lives here/regular visitors | rules the person sets (shoes/rooms/pets arrangement): ____ | privacy wishes during care (incl. from family): ____\nNO-ANSWER INFO (dc-003 ladder): contacts | telecare provider | GP | known routines (day centre days etc.): ____\nCRITICAL-CARE FLAGS (refusal/no-answer escalation same-day): meds due (incl. insulin) | pressure care | feeds | other: ____\nDEPARTURE: leave person (position/call bell/drink): ____ | secure (lock/keysafe scrambled/alarm): ____ | next-visit anchor helps? [ ]\nAgreed with person (date/signature where able): ______" },
      { title: "Doorstep & Departure Habits Card (community staff)", type: "template", body:
"EVERY DOOR, EVERY VISIT:\n1. PAUSE & READ: door damage? stranger answering? sounds wrong? gut says no? → step back, phone office (withdrawal rule applies at the threshold)\n2. ID: shown + name + service — every visit, however familiar. Coach the checking habit: 'you can always ring to verify — never let anyone in without ID.'\n3. ENTER by the agreed method ONLY — no improvised entries, ever\nREFUSED ENTRY: respect it — no argument, no pressure. State purpose once, gently. Document (person's state noted). CRITICAL elements (meds/insulin/pressure/feeds) → escalate same-day per plan. Patterns → review (free refusal? controlled? symptom?)\nNO ANSWER: never walk away — run the dc-003 ladder (knock protocol, phone, look & listen: milk, curtains, sounds → contacts → welfare check)\nINSIDE: guest with a job — household rules kept | rooms care requires | narrate cupboards/drawers | nothing borrowed | never smoke | privacy of everything seen | new/controlling presences reported same-day\nLEAVING: person settled (position/reach/drink/hob-candle check) | record made | door per arrangement | keysafe closed & SCRAMBLED | alarm re-armed | next-visit anchor given\nEMERGENCY ENTRY: not our shoulder — 999 holds the powers. Support entry; immediate-life-threat judgement calls will be reviewed kindly." },
    ],
  },
  "dc-002": {
    purpose: "This policy treats the keys and codes to people's homes as what they are: the physical trust of the service's most vulnerable clients, and the first thing a lawyer, a journalist or a burglar would ask about after an incident. Custody is provable at all times, confidentiality survives staff turnover, and compromise triggers response within hours, not audits within months.",
    scope: "Covers keysafe codes, physical keys held by the service, fobs and electronic access credentials, door codes for schemes and buildings, custody and issue systems, code changes, breach response, and audit. The entry arrangement itself is dc-001's; this policy is pure custody.",
    responsibilities: [
      { role: "Registered Manager", duties: [
        "Maintain the key and code register: every key, fob and code the service holds or knows, per person, with custody status live",
        "Operate issue discipline for physical keys: signed out per shift or visit run, signed back, never home overnight without documented arrangement",
        "Change codes on the trigger events — staff departure, suspected compromise, person's request — within the stated timescale",
        "Run the breach response when custody fails: containment, the person informed, locks or codes changed at the service's cost where the service failed, incident and notification machinery",
        "Audit custody monthly: register versus reality, spot checks, and the annual full reconciliation" ] },
      { role: "Community Staff", duties: [
        "Hold codes in the approved means only: the secured roster app or the service's approved method — never written in personal phones' notes, on paper in the car, or in message threads",
        "Handle keysafes properly: code entered discreetly (shielded from the street), safe closed and scrambled after every use, and never quoted aloud on the doorstep",
        "Sign keys in and out honestly and report loss or possible compromise the same hour — the lost key reported at once is a managed incident; concealed until Monday it is a betrayal",
        "Never share codes or keys with anyone — family members ask, tradespeople ask, colleagues out-of-process ask — the answer routes through the office, always" ] },
    ],
    keyPoints: [
      "The register is total: every physical key (which door, how many copies, where each lives), every keysafe code, every scheme door code, every fob and electronic credential the service holds or knows — per person, with issue history and the custody trail that answers 'who could open this door this month?' on demand",
      "Codes live in secured systems only: the roster app's secured field or the service's approved equivalent, displayed to the worker at need, never in personal notes apps, paper crib sheets, texts or WhatsApp — because the lost phone with a notes file of codes is a mass breach, and the register can't manage what it doesn't know exists",
      "Physical keys have a home and a log: held in the office key cabinet (locked, access-controlled), signed out for the run or shift with time and signature, signed back the same day, with overnight holding only under documented standing arrangements (the 6am first call) reviewed periodically — and unexplained key absence treated as a live incident, not a note for the next audit",
      "Keysafe discipline is trained as habit: approach checked (who's watching), code entered shielded, key used, key returned, safe CLOSED and SCRAMBLED — the unscrambled safe is an open door with extra steps — and safes themselves police-preferred models where the service advises on installation, sited with thought (not lit by the streetlamp beside the front path)",
      "Code changes run on triggers with timescales: staff departure (all codes the leaver knew, within the stated days — hours where departure was hostile), suspected or known compromise (same day), the person's or family's request (honoured promptly), periodic rotation where the service adopts it — with changes coordinated so the person, family, other agencies (district nurses share these safes) and the register all move together, because the code changed but not communicated is a locked-out care crisis at the next visit",
      "Compromise response is a drill, not a debate: possible compromise (lost key, lost phone with app access, code overheard, ex-staff concern, burglary in the area using keysafe methods) triggers containment first — code changed or lock changed at the service's cost where the service's custody failed — the person and family informed honestly, heightened watchfulness arranged, the incident recorded with the data-breach and safeguarding interfaces assessed, and the police involved where criminality is apparent",
      "Third parties are managed inside the system: district nurses, family, telecare responders and others who legitimately use the same keysafe are noted on the register (custody is shared, so is the suspect pool when things go wrong), tradespeople and one-off access are arranged through the person or family rather than by staff sharing codes, and the service never gives its held codes or keys to anyone outside the documented arrangement — the plausible caller ('I'm her nephew, just give me the code') is a social-engineering classic",
      "Audit proves custody: monthly register-versus-cabinet checks and sampled code verifications, every discrepancy investigated to explanation, the annual full reconciliation touching every person's arrangement, and the audit trail itself retained — because when the question comes (and in community care it eventually comes), 'we can show every hand that key passed through' is the only good answer",
    ],
    legislation: [
      "Data Protection Act 2018 / UK GDPR (codes as personal data; breach duties)",
      "Health and Social Care Act 2008 (Regulated Activities) Regulations 2014 — Regulations 12, 13, 17",
      "Care Act 2014 (safeguarding)",
      "Theft Act 1968 (the criminal frame around key misuse)",
      "Human Rights Act 1998 (Article 8)",
    ],
    sections: [
      { heading: "The Register and Code Custody", body: "The register is the policy's spine: one controlled record (within the roster/care system or the service's secured equivalent) listing, per person — the entry method (from dc-001), every code the service knows (keysafe, door, alarm, scheme entrance), every physical key or fob held (which lock, copy count, storage location), the third parties known to share access (district nursing, family, telecare response — with their own custody noted), the issue and change history, and the review date. Access to the register itself is role-limited and logged. Codes reach workers through the secured channel only: displayed in the roster app at need (per-visit, not exportable lists), or issued by the office verbally for the day's exceptions — and the prohibited forms are named in training because they are what people actually do under time pressure: the notes app file titled 'codes', the photographed page, the laminated crib card in the car door, the WhatsApp to the covering worker. Each is a breach of every household on the list at once, and the discipline is enforced with the same seriousness as medication custody. Alarm codes and telecare interactions are recorded with the same rigour, and scheme/building codes (sheltered housing entrances) are treated as shared-custody items coordinated with the scheme manager." },
      { heading: "Physical Keys and Keysafes", body: "Held keys are the highest-custody tier: accepted only where the entry assessment justifies them (keysafes are generally preferable — self-documenting, changeable, no physical object to lose), recorded on acceptance (signed for with the person/family, copy count agreed and minimised), stored in the locked, access-controlled key cabinet with anonymous tagging (a code linking to the register, never the address on the fob — the lost labelled key is a burglary invitation with directions), signed out and in per run with times and signatures, and counted at the cabinet check. Overnight and standing arrangements (the early first call, the rural round) are documented exceptions with named holders and periodic review, not habits that grew. Keysafe practice is trained as a physical drill: situational check before approaching (the watcher across the road), body-shielded code entry, immediate key return after door opening (not pocketed through the visit — the pocketed key leaves with the distracted worker), safe closed and scrambled before leaving the doorstep, and the same drill on departure. Where the service advises on keysafe installation (it often effectively chooses), it recommends police-preferred/accredited models, thoughtful siting, and family understanding of who will hold the code. Fobs and electronic credentials follow key rules (registered, issued, returned, deactivated on loss — with deactivation's speed being their advantage), and the leaver's checklist (hr interfaces) collects keys, fobs and app access on the last day, with the code-change trigger running behind them." },
      { heading: "Changes, Breaches and Third Parties", body: "Code changes are choreography: the trigger events (leaver — all codes known to them, within the stated timescale, same-day for hostile departures or dismissals with trust dimensions; compromise — same day; person's request — promptly; periodic rotation where adopted) start a coordinated sequence — new code set (with the person/family doing the physical change or the service arranging it), every legitimate sharer informed through their proper channels (the district nursing team's coordinator, not a note under the safe), the register updated, the roster system's display updated, and the first visit after the change confirmed successful — because the failure mode of code hygiene is the carer locked out at 8am while insulin waits. Breach response runs the containment-first drill: on any possible compromise, the exposure is assessed (which homes, which codes, what window), changes are made at the speed the risk demands, the person and family are told honestly (dignity includes knowing your door may not be secure), locks are changed at the service's cost where the service's custody failed, watchfulness is raised (staff alert to signs of entry, telecare providers informed where relevant), and the machinery engages: incident record, data-breach assessment (igr-003 — codes are personal data), safeguarding thresholds, police where criminality is apparent or suspected, and notification duties per the notifications policy. Third-party requests for access are routed, never granted at the doorstep: family members, tradespeople, new agencies and plausible phone callers are directed to the person, their authority-holders, or the office's verification process — and staff are trained on the social-engineering patterns (urgency, authority claims, distress performance) that make kind people share codes with strangers." },
      { heading: "Audit and Culture", body: "Custody is proven on a cycle: monthly, the key cabinet is reconciled against the register (every key present or signed out to a named person on a live run) and a sample of code arrangements is verified (register matches the roster display, the person's current safe, the sharers' knowledge); discrepancies are investigated to explanation the same week, however small — the key that 'must have been signed back but wasn't logged' is either a records failure or a custody failure, and both matter; and annually the full reconciliation touches every arrangement, retiring dead entries (the person who moved, the safe that was removed) and refreshing review dates. The audit trail is retained per the records schedule because its existence is the deterrent. Culture carries the rest: reporting a lost key or a possible slip within the hour is praised in the debrief however inconvenient the consequences, because the alternative culture — quiet hoping — converts recoverable incidents into betrayals discovered by burglary; and the induction message is the policy in one sentence: we hold the keys to the homes of people who cannot always answer their doors — there is no such thing as being too careful with them." },
    ],
    appendices: [
      { title: "Key & Code Register (per person) + Issue Log", type: "template", body:
"PERSON: ______  Entry method (dc-001 ref): ______\nCODES KNOWN: keysafe ____ | door/alarm ____ | scheme ____ (change history: date/reason/all-sharers-informed [ ])\nKEYS/FOBS HELD: lock | copies | cabinet tag (anonymous — NEVER address) | accepted (signed, date) | standing overnight arrangement? (named holder, review date)\nTHIRD-PARTY SHARERS: district nursing / family / telecare / other — contact route for change coordination\nISSUE LOG: date | key tag | out (time/signature) | in (time/signature) | exceptions escalated same day\nCODE CHANGE TRIGGERS & TIMESCALES: leaver (all known codes, ____ days; SAME DAY if hostile/trust-related) | compromise (same day) | person's request (prompt) | rotation (if adopted): ____\nFIRST-VISIT-AFTER-CHANGE confirmed successful [ ]\nMONTHLY AUDIT: cabinet vs register | code sample verified | discrepancies investigated (same week) | ANNUAL full reconciliation (date): ______" },
      { title: "Keysafe Drill & Breach Response Card", type: "template", body:
"KEYSAFE DRILL (every use):\n1. CHECK surroundings (who can see?)\n2. SHIELD the code entry with your body\n3. Key out → door open → key BACK IN SAFE immediately (never pocketed through the visit)\n4. Safe CLOSED + SCRAMBLED — before you leave the doorstep, arriving AND leaving\nNEVER: code aloud on the doorstep | codes in personal notes/photos/texts/WhatsApp | codes or keys given to ANYONE (nephew on the phone, tradesperson at the door) → route to the office, always\nLOST KEY / LOST PHONE / CODE POSSIBLY EXPOSED → REPORT WITHIN THE HOUR (praised, not punished)\nBREACH RESPONSE (office): assess exposure (homes/codes/window) → change codes/locks at the speed risk demands (service's cost where our custody failed) → person & family told honestly → sharers informed via proper channels → register updated → watchfulness raised → incident + data-breach (igr-003) + safeguarding + police thresholds assessed → first-visit-after confirmed\nSOCIAL ENGINEERING TELLS: urgency | authority claims | distress performance | 'just this once' — kind people share codes with strangers; route it to the office." },
    ],
  },
  "dc-003": {
    purpose: "This policy is the safety net under the scheduled visit — the unit of community care and the unit of its failure. A missed call is not an admin lapse: for the person whose 8am visit is insulin, hoisting out of bed, or the only human contact of the day, it is a clinical event, and the service that cannot detect its own missed calls within minutes has no safety system, only luck. This policy deepens the base No Reply & Missed Call procedure (cop-004) with the full operational machinery.",
    scope: "Covers late calls, missed calls, and the detection-and-response system behind both: call criticality ratings, real-time monitoring (with dc-004's ECM as the sensor), communication with people and families, the response ladder through to welfare checks, notifications when the service fails, and the pattern analysis that prevents recurrence. The no-answer-at-the-door ladder is shared with dc-001/cop-004.",
    responsibilities: [
      { role: "Registered Manager", duties: [
        "Rate every commissioned call for criticality at assessment — and build the response timescales from the rating, not from a one-size window",
        "Staff the monitoring function: someone (coordinator in hours, on-call out of hours) watching the live picture with authority to act",
        "Ensure lateness is communicated forward: the person told, the critical needs bridged, the run re-sequenced where clinical priority demands",
        "Own the failures: missed calls investigated same-week, notified honestly (person, family, commissioner, regulator per thresholds), and patterned monthly",
        "Fix the causes: rosters that generate lateness are re-engineered, not re-apologised" ] },
      { role: "Care Workers", duties: [
        "Log in and out accurately (dc-004) — the monitoring system is blind without honest data",
        "Report emerging lateness as it happens: the overrun, the traffic, the crisis at the previous call — a ten-minute warning lets the office bridge what a silent lateness lets fail",
        "Never self-cancel or self-shorten calls: re-sequencing decisions belong to the coordinator who can see the whole board and the criticality ratings",
        "Run the doorstep no-answer ladder in full, every time (dc-001 card), and never record a call as delivered that wasn't" ] },
      { role: "Coordinators / On-Call", duties: [
        "Watch the exceptions in real time and act on the criticality clock: a late red-rated call is escalating within minutes, not at end of shift",
        "Bridge critical needs when lateness is unavoidable: phone the person, dispatch the nearest worker for the insulin, engage family or telecare per the plan",
        "Run the missed-call ladder to resolution and document every rung" ] },
    ],
    keyPoints: [
      "Criticality ratings drive everything: every call rated at assessment (e.g. RED — time-critical clinical: insulin and time-sensitive meds, catheter/stoma/PEG needs, hoisting someone off a pressure area, feeds; AMBER — care-critical within a window: personal care, meals, most medication; GREEN — flexible: domestic, social, shopping) with the rating visible on the roster, reviewed as needs change, and the response clock scaled to it — a red call's 'late' is measured in minutes, and the ratings are clinical judgements made with the care plan, not admin labels",
      "Detection is real-time or it is fiction: the ECM/roster system flags the un-logged call at rating-scaled thresholds (e.g. red: 15 minutes; amber: 30; green: 60 — the service sets and states its own), the monitoring role sees the flag as it fires, and the out-of-hours picture is watched by on-call with the same clocks — a missed call discovered next morning is a detection failure compounding a delivery failure",
      "Lateness is managed forward, not absorbed: the worker reports the overrun as it emerges; the coordinator re-reads the run (can the green call slide to bridge the red one?), phones the waiting person with honesty and a new time ('Maria's running 25 minutes behind — will you be alright until quarter past, or shall I check on the tablets?'), bridges critical elements (nearest worker diverted for the insulin, family or telecare engaged per the plan), and records the communication — the person told is a person still safe and still respected; the person left waiting in silence is the complaint, the harm, and the headline",
      "The missed-call ladder runs to certainty: flag fires → worker contacted (where are you? — the log-in failure and the genuinely missed call look identical at first) → person phoned → no contact: the dc-001/cop-004 doorstep-and-contacts ladder (attend or divert nearest worker, knock protocol, look and listen, phone contacts, telecare provider check) → welfare check escalation (family attends, or police welfare check with the information pack) — with the whole ladder time-bounded by the criticality rating and every rung logged with times",
      "Cancellations are managed as planned events: the person's own cancellation is confirmed, recorded, and critical elements checked ('you'll take the tablets yourself? — I'll note that'); service-initiated changes are communicated ahead with equivalent cover arranged for critical calls; and the un-agreed 'cancellation' (the worker who couldn't get in and marked it cancelled) is a falsification issue, not a category",
      "Failures are owned out loud: a missed critical call is disclosed to the person and family with apology and the bridging action taken (duty of candour thresholds honoured), reported to the commissioner per contract, notified to the regulator where thresholds are met, investigated same-week (roster maths, sickness cover, communication chain, worker conduct — the cause named honestly), and logged for pattern",
      "Patterns get engineering, not apology-management: monthly analysis reads lateness and misses by run, worker, time-band, day and cause — the 7-9am runs that are mathematically impossible, the double-up calls that single workers keep absorbing, the rural loop that winter breaks — and the fixes are structural: travel time honestly rostered (dc-005), runs rebuilt, recruitment targeted, commissioners engaged where the commissioned volume exceeds the deliverable",
      "The person's experience is the metric: 'was I told, was I safe, was it put right' — reliability data is reported to governance alongside the complaints and the compliments, because a service can hit 98% delivery and still be the service whose 2% was always the same isolated, red-rated woman",
    ],
    legislation: [
      "Health and Social Care Act 2008 (Regulated Activities) Regulations 2014 — Regulations 9, 12, 17, 18, 20 (duty of candour)",
      "Care Act 2014 (safeguarding — neglect includes organisational failure to deliver planned care)",
      "Mental Capacity Act 2005 (cancellation and refusal decisions)",
      "Data Protection Act 2018 (monitoring data — with dc-004)",
      "Contract/commissioning frameworks (reporting duties)",
    ],
    sections: [
      { heading: "Rating the Calls", body: "Criticality rating happens at care planning with clinical eyes: what does this visit actually deliver, and what happens if it is late or lost? Time-critical clinical elements (insulin and other time-sensitive medication, PEG feeds, catheter care with retention risk, repositioning off pressure damage, the person hoisted out of bed at 8 who is otherwise in it until noon) rate red with tight clocks; care-critical elements with tolerance windows (personal care, meals for the person who cannot self-serve, most medication rounds) rate amber; genuinely flexible support (domestic, shopping, social) rates green — and mixed visits take their highest element's rating. The rating lives on the roster where every coordinator and covering worker sees it, drives the detection thresholds and response clocks, and is reviewed at care plan reviews and on change (the new insulin start upgrades the morning call the same day). The rating conversation includes the person and family — what matters most about this visit, what could bridge it (a neighbour who could microwave the lunch, the telecare pendant, the daughter who works nearby) — because the bridging plan is written when calm, not improvised at 8:20 with the coordinator's phone hot. Double-handed calls carry their own flag (one worker arriving is a moving-and-handling incident waiting), and the first-call-of-the-day and last-call flags mark the visits where a miss means a person stranded in bed at either end of the day." },
      { heading: "Watching the Board", body: "The monitoring function is a staffed reality with the tools to see: the live ECM exception screen (dc-004) showing un-commenced calls against their thresholds, the day's runs with criticality colouring, and the communication channels to workers, people and families. In hours the coordinator owns it; out of hours the on-call holder does, with the same screens (remote access) and the same authority — and handovers transfer the live picture (the run already wobbling at 5pm is tomorrow's 8am problem unless handed over). The discipline is exception-response at the clock: a red call un-commenced at threshold gets the worker's phone rung within minutes, not noted for later; the amber stack is triaged; and the system's own health is watched (the ECM outage per dc-004's fallback turns the board manual — paper runs and check-in calls — rather than dark). Workers feed the board: the emerging overrun reported by the two-minute call ('Mrs K has had a fall, I'll be 40 minutes, her 12:30 needs bridging'), which converts a future missed call into a managed re-sequence — and the culture point is enforced kindly: reporting lateness early is praised, because the worker who hides an overrun to avoid a conversation has chosen the service's blindness over the next client's insulin." },
      { heading: "The Ladder and the Bridge", body: "When a call goes late or silent, two parallel tracks run. The bridge (for known lateness): the coordinator phones the waiting person with honesty and options, re-reads the run for re-sequencing (greens slide, reds don't), diverts the nearest capable worker for time-critical elements (competency-checked per hr-027 — the diverted worker must be signed off for the insulin), engages the plan's bridging assets (family, neighbour arrangement, telecare check-in), and records what was done and said. The ladder (for silence): threshold fires → worker contacted (the honest possibilities triaged: log-in failure, phone dead, crisis at the previous call, or the genuine miss — each with its next step) → person contacted by phone → no answer: nearest worker or coordinator attends, runs the full doorstep protocol (dc-001: knock rhythm, look and listen, the milk and the curtains), phones the contacts and the telecare provider (has the pendant been used? when was the last activity?) → genuine concern: welfare check — family attends if close and willing, police welfare request with the information pack (address, access per dc-002, medical summary, what the concern is) where urgency or absence of family demands — with the criticality clock bounding the whole climb (a red call's ladder completes within the hour; nobody discovers at 6pm that the 8am insulin visit never happened). Every rung is logged with times as it happens, and resolution closes the loop: the person found safe (visit delivered late, records honest), the person found in need (clinical response, incident machinery), or the false alarm (the day centre trip nobody told the roster about — which updates dc-001's routines note so the ladder doesn't cry wolf twice)." },
      { heading: "Owning Failures and Fixing Systems", body: "When the service misses a call — genuinely misses it, not delivers-late — the response is candour and repair in that order: the person and family told what happened and what's being done (not discovered by them at the empty teatime), the immediate harm assessed and met (the clinical check after missed medication, the pressure-area inspection after the missed reposition, the meal delivered late but delivered), duty of candour formalities honoured where the harm threshold is met, the commissioner told per contract terms, and the regulator notified where the notification thresholds bite. The same-week investigation names the cause honestly from the standard taxonomy: roster arithmetic (the run was never deliverable — dc-005's territory), cover failure (sickness with no bridge), communication failure (the change nobody told the worker), system failure (ECM outage without fallback), or conduct (the falsified log, the self-cancelled call — disciplinary territory) — because the fix differs entirely by cause, and 'the worker was late' is a description, not a cause. Monthly, the pattern analysis reads the whole picture — lateness distribution by run/time/day/worker/cause, near-miss ladder activations, bridging frequency (a call bridged weekly is a roster confession) — and the outputs are structural: runs rebuilt with honest travel (dc-005), criticality re-weighted, recruitment and retention actions where the maths needs people, and the commissioner conversation where commissioned volumes exceed deliverable reality — put formally, in writing, because quietly absorbing an undeliverable contract is how services drift into the neglect they would never choose. Governance sees reliability as a headline metric: delivery rates by criticality, time-to-detection, ladder completion times, repeat-affected people (the same person missed twice is a different order of failure), and the candour record — the numbers that say whether the net actually holds.", },
    ],
    appendices: [
      { title: "Call Criticality & Bridging Plan (per person/visit)", type: "form", body:
"PERSON: ______  Visit: ____ (time/duration/single or DOUBLE-HANDED [ ])\nRATING: RED (time-critical clinical: insulin/time-sensitive meds/PEG/catheter/repositioning/hoist-dependent) | AMBER (care-critical window: personal care/meals/most meds) | GREEN (flexible: domestic/social) — mixed visits take highest element\nDetection threshold: RED ____ min | AMBER ____ | GREEN ____ (service-stated)  Ladder completion clock: ______\nWHAT THIS VISIT DELIVERS (the 'what fails if missed'): ______\nBRIDGING PLAN (written calm, used hot): person can be phoned? [ ] | nearest-worker divert needs competency: ____ (hr-027) | family/neighbour bridge: ____ | telecare: provider/pendant ____ | meds self-manage option (recorded): ____\nFLAGS: first-call-of-day [ ] last-call [ ] double-handed [ ]\nReview: care plan reviews + same-day on clinical change (new insulin = same-day upgrade)\nRating agreed with (person/family/clinical source): ______" },
      { title: "Missed/Late Call Log & Monthly Pattern Review", type: "template", body:
"LIVE LOG (per event, times on every rung): call (person/rating/scheduled) | threshold fired | worker contacted (finding: log-in failure/phone/overrun/miss) | person phoned | LATE TRACK: person told + new time | re-sequence | critical bridge (what/who/competency checked) | SILENT TRACK: attendance + doorstep protocol | contacts + telecare check | welfare check (family/police + info pack) | RESOLUTION: safe-late / found-in-need (clinical + incident refs) / false alarm (routines note updated)\nFAILURE OWNERSHIP (genuine miss): person & family told (candour, not discovery) | harm assessed & met (med check/pressure/meal) | DoC threshold [ ] | commissioner (per contract) [ ] | regulator (thresholds) [ ] | same-week investigation — CAUSE (taxonomy): roster arithmetic / cover / communication / system / conduct → FIX matched to cause\nMONTHLY PATTERN: lateness by run/time/day/worker/cause | ladder activations & completion times | bridging frequency (weekly-bridged call = roster confession) | repeat-affected people (flagged) | STRUCTURAL FIXES: runs rebuilt (dc-005) / re-rating / recruitment / commissioner letter (in writing) | → governance headline metrics" },
    ],
  },
  "dc-004": {
    purpose: "This policy runs electronic call monitoring as what it should be: the sensor layer of the missed-call safety net (dc-003), the honesty layer of the care record, and the fairness layer of pay and billing — in that order. ECM done badly becomes surveillance theatre that staff game and nobody trusts; done well it is the difference between a service that knows what happened and one that believes its own paperwork.",
    scope: "Covers the ECM system in use (app-based, telephony, or device-based logging), logging disciplines, exception monitoring, the data's uses (safety, records, pay, billing, commissioner reporting) and their limits, staff privacy and location data, system failures and fallbacks, and data governance. dc-003 owns the response to what ECM detects.",
    responsibilities: [
      { role: "Registered Manager", duties: [
        "Run ECM as a safety system: the exception screen staffed (dc-003), thresholds set by criticality, and detection performance reviewed",
        "State the data's uses plainly to staff and people supported: what is collected, what it drives (safety response, records, pay, billing), who sees it, and what it will never be used for",
        "Keep the data honest: no remote or retrospective logging by office staff without documented cause, investigation of gaming patterns, and reconciliation disciplines",
        "Maintain the fallback: the system fails sometimes, and the safety net must not fail with it",
        "Use the analytics for system improvement — run design, travel honesty, visit-length reality — before individual performance management" ] },
      { role: "Care Workers", duties: [
        "Log in on arrival and out on departure, from the doorstep not the car, every visit — the log is the safety net's eyes and the record's spine",
        "Log honestly: no early log-ins from outside, no colleague logging for colleague, no calls closed from home — gaming the system blinds it, and blinded systems miss the day someone is on the floor",
        "Report system problems (app failures, signal blackspots, device faults) so fallbacks engage and blackspots get mapped",
        "Record care within the visit per the recording policies — ECM timestamps frame the visit; they don't replace its content" ] },
    ],
    keyPoints: [
      "Safety first is a design decision: the ECM's primary output is the live exception screen dc-003 watches — un-commenced calls flagged at criticality-scaled thresholds — and the system's performance is measured on detection (time from threshold to human eyes) before it is measured on billing accuracy",
      "Logging discipline is simple and absolute: in at the door on arrival, out at the door on departure, every visit, by the worker who is actually there — with the named prohibitions trained: no logging in from the car or the street corner (the log says 'with the person'), no logging colleagues in or out, no office-side remote logging except under the documented-cause procedure (system failure reconciliation, with reason recorded), and no closing calls after the fact to tidy the day",
      "The data's uses are stated and bounded: safety monitoring (primary), the care record's visit frame (arrival/departure times feeding the legal record), pay accuracy (where pay is time-based, the log protects workers from underpayment as much as it protects the service), billing and commissioner reporting (honest data or none), and roster improvement analytics — with the bounds equally stated: no covert tracking between visits where the system offers it (location data proportionate to safety need, per the lone-working policy's transparency), no league-tables-by-log published to shame, and no disciplinary use of aggregate patterns without proper investigation of cause first",
      "Visit-length data is read with care intelligence: the log that shows 20-minute deliveries of 30-minute commissioned calls is a finding requiring diagnosis — call-cramming rosters (dc-005's fix), genuine efficiency, or care clipping (a quality and contract failure) — and the diagnosis conversation starts with the run's arithmetic, not the worker's character; equally, consistent overruns are workload data the roster must absorb, not goodwill to bank silently",
      "People supported know the system exists: explained at assessment in plain terms (the phone tap that tells the office your carer has arrived — it's how we'd know if anyone didn't turn up), consent handled per the system's basis (telephony systems using the person's landline especially), and the reassurance made real — the system watches the service's reliability for them, not them",
      "Staff privacy is engineered: location data collected at the minimum the safety function needs, retention per the schedule and no longer, access role-limited and logged, the workforce told exactly what supervisors can see, and the monitoring-at-work legal frame (data protection, the employment relationship's fairness) respected in policy and practice — hr-026's lone-worker location transparency and this policy speak with one voice",
      "Failures have a rehearsed fallback: app outage, platform failure or mass signal loss flips the board to manual — paper run sheets, workers phoning in/out to the coordinator, the exception clock kept by hand — with the flip decision made by the coordinator at defined triggers (not each worker improvising), the outage logged, reconciliation done when the system returns (documented-cause remote corrections), and blackspot workarounds (offline logging modes, SMS fallbacks) configured where the geography demands",
      "Reconciliation keeps everyone honest: the weekly sweep matches logs against rosters and records — unmatched visits, impossible sequences (two homes at once), systematic anomalies — with discrepancies resolved by asking before assuming (signal? device? genuine issue?), gaming patterns investigated properly when the innocent explanations fail, and falsified logs treated as the records falsification they are (conduct machinery, with the safeguarding lens where phantom visits left people uncared for)",
    ],
    legislation: [
      "Data Protection Act 2018 / UK GDPR (worker and service-user data; monitoring at work)",
      "Human Rights Act 1998 (Article 8 — proportionate monitoring)",
      "Health and Social Care Act 2008 (Regulated Activities) Regulations 2014 — Regulations 12, 17",
      "Employment Rights Act 1996 / National Minimum Wage Regulations (time and pay interfaces)",
      "Fraud Act 2006 (falsified billing's criminal frame)",
    ],
    sections: [
      { heading: "The System as Safety Sensor", body: "ECM's architecture serves dc-003's net: every rostered call exists in the system with its time, duration, criticality rating and worker; log-in events clear flags and log-out events close visits; and the exception engine raises un-commenced calls at the rating-scaled thresholds to the staffed screen — with escalating alerts (screen, then coordinator's phone, then on-call cascade) so a flag never waits politely in an unwatched queue. Detection performance is itself monitored: time-from-threshold-to-action sampled monthly, out-of-hours detection tested (the deliberate test-miss with a cooperating worker, hr-026-style), and the system's blind spots mapped — the signal blackspots where offline modes or call-in fallbacks substitute, the telephony gaps where the person's landline is the logging device and the person is deaf to its politics. Configuration is a management duty: thresholds reviewed with the criticality framework, new clients live in the system before their first visit (the un-rostered first visit is invisible to the net), schedule changes propagated same-day, and the roster-ECM-care-record triangle kept consistent so one truth exists, not three approximations." },
      { heading: "Honest Data", body: "The log's value is exactly its honesty, so honesty is engineered and enforced. The logging moment is defined physically: at the door on arrival (after the doorstep drill, dc-001), at the door on departure (after the departure checklist) — not the car, because minutes of sat-in-car log time are minutes the record claims care that didn't happen, and not after leaving, because the reconstruction is where fiction starts. Remote and retrospective corrections are the office's controlled exception: system-failure reconciliation and genuine error correction under the documented-cause procedure (who, what, why, evidence), logged as corrections rather than overwrites, and audited — the office that silently 'tidies' logs teaches the workforce the data is negotiable. Gaming patterns are watched for with fairness: the weekly reconciliation surfaces anomalies (impossible travel sequences, calls closing in round numbers from one device, log-ins clustering at shift-start from one location), the first response is diagnostic (device faults, signal, misunderstanding of the rules), and the proven cases — phantom visits above all — run the conduct machinery with the seriousness the underlying harm demands: a phantom visit is a missed call wearing a delivered call's clothes, which defeats the net, defrauds the funder, and abandons the person, all in one tap. Workers are protected by the same honesty: time-based pay is paid on the log (underpayment disputes resolved by the data), overruns visible in the system are workload evidence for dc-005's roster fixes, and no worker is disadvantaged for honest logging of an inconvenient truth." },
      { heading: "Proportionate Monitoring and the People in the Data", body: "Two constituencies live inside ECM data and both get transparency. Staff: told at induction exactly what the system collects (log events, and location at logging moments or continuously per the system — stated precisely), who can see what (the coordinator's live screen, the manager's reports, the payroll extract), retention periods, and the stated non-uses (no covert between-visit tracking beyond what the lone-worker safety function transparently requires per hr-026, no shame-boards, no aggregate-pattern discipline without investigated cause) — with the monitoring-at-work fairness principles honoured: the least intrusive configuration that serves the safety and integrity purposes, documented in the data protection records (wl-005/igr territory), and revisited when the platform adds shinier surveillance the service doesn't need. People supported: the system explained at assessment in human terms, its basis documented (contract/legitimate interests with the balancing done, or consent where the configuration needs it — telephony logging on the person's own line handled with particular care), their access rights honoured (the daughter asking 'was anyone actually there Tuesday?' gets an honest answer through the proper access routes), and the reassurance kept true: the data watches the service's promise-keeping, and its most important reader is the coordinator making sure nobody was forgotten." },
      { heading: "Failure, Reconciliation and Improvement", body: "The fallback drill assumes the system will fail because it will: at defined triggers (platform outage confirmed, app failure reports clustering, signal event) the coordinator declares manual mode — the day's runs printed or read out, workers phone in and out to the office (or text per the stated fallback), the exception clock kept by hand with the same criticality thresholds, and on-call briefed if the outage spans shifts. The outage and the declaration are logged; restoration triggers reconciliation (documented-cause corrections matching the manual record); and repeated platform failures become a supplier and contingency conversation, not a normalised degradation. The weekly reconciliation is the system's hygiene: logs vs rosters vs care records, unmatched and anomalous events resolved by inquiry, corrections documented, and the output feeding three streams — the integrity stream (gaming and falsification, handled as above), the operational stream (dc-003's pattern analysis: lateness, bridging, the runs that never work), and the strategic stream: visit-length reality versus commissioned time (the systematic 22-minute delivery of 30-minute calls is a finding for the commissioner conversation or the roster rebuild, dc-005), travel-time truth (log gaps between visits mapping actual journey times for dc-005's honest rostering), and capacity reality for growth decisions. Governance reads ECM quarterly as a safety system first: detection performance, fallback activations, integrity findings, and the one-line test — when a call was missed, did this system know before the person's family did?" },
    ],
    appendices: [
      { title: "ECM Logging Rules & Fallback Card", type: "template", body:
"LOGGING RULES (every visit):\n✓ IN at the door on arrival (after doorstep drill) | ✓ OUT at the door on departure (after departure checklist)\n✗ Never from the car/street | ✗ Never for a colleague | ✗ Never close calls later from home | Office remote corrections: documented-cause procedure ONLY (who/what/why/evidence, logged as corrections)\nSignal blackspot? Use offline mode/SMS fallback + report it (blackspots get mapped)\nSystem problem? Report immediately — fallbacks exist so the net doesn't go dark\nWHY IT MATTERS: the log is how we'd know if anyone was forgotten. Gaming it blinds the net. Phantom visits = missed call + fraud + abandonment in one tap (conduct + safeguarding machinery).\nFALLBACK (coordinator declares at triggers: platform outage/app failure cluster/signal event): manual mode — printed runs | workers phone/text in & out | exception clock by hand, same criticality thresholds | on-call briefed | outage logged | reconciliation on restore\nYOUR DATA: what's collected, who sees it, retention — stated at induction. Time-based pay follows the log (protects you). Overruns in the data = workload evidence, not banked goodwill." },
      { title: "Weekly Reconciliation & Quarterly ECM Governance", type: "template", body:
"WEEKLY RECONCILIATION: logs vs rosters vs care records | unmatched visits | impossible sequences (two places at once) | round-number/cluster anomalies | resolution by INQUIRY first (device/signal/misunderstanding) | corrections documented | findings → integrity / operational (dc-003 patterns) / strategic streams\nINTEGRITY: gaming patterns investigated fairly | falsified logs & phantom visits → conduct machinery + safeguarding lens + funder-fraud assessment\nSTRATEGIC: visit-length reality vs commissioned time (systematic gap → commissioner letter or roster rebuild dc-005) | travel-time truth (log gaps → honest rostering) | capacity reality\nQUARTERLY GOVERNANCE (safety system first): detection time (threshold→human action, sampled) | OOH detection tested (test-miss drill, date: ____) | fallback activations & performance | blackspot map current | integrity findings | staff transparency current (config changes re-notified) | THE TEST: when a call was missed, did the system know before the family did?" },
    ],
  },
  "dc-005": {
    purpose: "This policy makes travel time honest — because every dishonest roster pays for its fiction somewhere: in the clipped call (the person's 30 minutes becomes 22), in the dangerous drive (the worker doing 50 in a 30 to hold the fiction together), or in the burned-out worker who leaves. Travel is work, it takes the time it takes, and a roster that pretends otherwise has chosen which of the three someone will pay.",
    scope: "Covers travel time in community rostering: run design and travel allowances, the pay and working-time treatment stated plainly, driving standards for work journeys (with hr-025's device rules and ch-010's vehicle standards), non-driving travel, weather and seasonal adjustments, and the analytics that keep rosters honest. Journeys WITH people supported are ch-010's; lone-worker safety in transit is hr-026's.",
    responsibilities: [
      { role: "Registered Manager", duties: [
        "Roster real travel: journey times from actual data (ECM gap analysis, mapping tools with local honesty) between every consecutive call, adjusted for time-of-day, season and area",
        "State the pay and working-time treatment in writing: how travel time is paid, how mileage is reimbursed, and how the National Minimum Wage calculation includes travel — and keep the arithmetic lawful",
        "Design runs geographically: clustering that respects continuity preferences while cutting criss-cross waste",
        "Watch the indicators of travel fiction: chronic lateness cascades, clipped calls, speeding complaints, worker feedback — and rebuild rather than exhort",
        "Set the weather protocols: winter timings, the snow-day priority plan, and the explicit permission to be late rather than dangerous" ] },
      { role: "Care Workers", duties: [
        "Drive legally and safely always: speed limits regardless of schedule pressure, hr-025's absolute phone rules, seatbelts, and fitness to drive (fatigue after long runs is a declared issue, not a private struggle)",
        "Report travel reality: the runs that don't work, the journey the roster gives 5 minutes that takes 15, the blackspot, the parking desert — the roster is fixed with data workers provide",
        "Keep vehicle basics for work use: licence, insurance for business use, MOT and roadworthiness per the declarations (ch-010's gateway)",
        "Never absorb travel fiction into care time: the call gets its commissioned minutes, and the impossible schedule is escalated, not silently self-managed" ] },
    ],
    keyPoints: [
      "Travel time is rostered between every pair of calls from real data: mapping estimates sanity-checked against ECM gap analysis (dc-004's log gaps are the ground truth of actual journeys), with time-of-day honesty (the school-run 8:45 differs from the 2pm), seasonal adjustment (winter darkness and weather), area knowledge (the estate with no parking, the farm track), and mode honesty (the walker's and bus-user's times are not the driver's) — zero-travel back-to-backs are permitted only for same-building or genuinely adjacent calls, and the roster system enforces the minimums",
      "The pay position is stated and lawful: how travel time between calls is paid (and it must be — travel between assignments is working time for National Minimum Wage purposes, and the service's pay model demonstrates NMW compliance across the whole shift including travel, audited periodically), how mileage is reimbursed (rate, claim process, prompt payment), and how the working-time picture (rest breaks across long runs, maximum realistic run lengths) is protected — because underpaid travel is both a legal exposure and the sector's quiet wage theft, and this service does neither",
      "Runs are designed geographically with continuity intelligence: calls clustered by area to cut dead miles, continuity preferences honoured within the geography (the person's preferred workers weighted against the map, with the trade-offs made consciously), double-handed calls synchronised so neither worker waits unpaid in the car, and new-client placement decisions including the travel question at acceptance ('can we actually serve this postcode at this time?') rather than after",
      "Schedule pressure never buys speed: the policy states it in terms — workers are expected to arrive late rather than drive dangerously, lateness caused by honest travel is the roster's failure and never the worker's disciplinary issue, and the office's communication culture (hr-025: no calls answered at the wheel, no criticism of driving-delayed replies) backs the words with behaviour",
      "Weather flips the plan, not the standard: winter protocols pre-planned (longer timings applied globally, daylight-priority sequencing for rural runs), the severe-weather day runs the criticality triage (dc-003's red calls prioritised, greens rescheduled with the person told, 4x4 volunteers and walkable local pairings mapped in advance), and the stand-down decision — roads genuinely impassable — made by the service with alternative bridging (family, neighbours, telecare, emergency services for the truly critical) rather than by each worker's private courage",
      "Non-driving travel is planned as its own mode: walking rounds designed at walking pace with weather reality, public-transport runs built on actual timetables with connection honesty, cycling per the worker's choice with the safety basics supported, and the mode never assumed — the roster knows how each worker travels and times accordingly",
      "Vehicle standards ride on ch-010's gateway: for any work driving — business insurance confirmed, licence checked, roadworthiness declared — even when no client is ever carried, because the worker driving for work is at work; and breakdown reality is planned (breakdown cover encouraged/provided per the service's offer, the broken-down worker's run redistributed by the coordinator, hr-026's net covering the stranded worker)",
      "The analytics close the loop monthly: ECM gap analysis versus rostered travel (the systematic 5-rostered-15-actual journey is found and fixed), lateness cascade tracing (which run's arithmetic collapses by 10am), clipped-call correlation (travel fiction's signature is call-length erosion at run's end), mileage claims versus rostered miles (divergence means the map is wrong somewhere), and worker feedback gathered actively — with the output being rebuilt runs, adjusted standards, and where the commissioned volume simply exceeds the geography's physics, the commissioner conversation in writing",
    ],
    legislation: [
      "National Minimum Wage Act 1998 and Regulations (travel between assignments as working time)",
      "Working Time Regulations 1998 (rest, maximum hours)",
      "Road Traffic Act 1988 (driving standards; employer duties for work driving)",
      "Health and Safety at Work etc. Act 1974 (work-related road risk)",
      "Employment Rights Act 1996 (pay statement clarity)",
    ],
    sections: [
      { heading: "Honest Arithmetic", body: "Roster travel standards are built from evidence and maintained against drift. The baseline: mapping-tool estimates for every recurring journey pair, corrected by local knowledge (parking reality, one-way systems, the door-to-door walk at each end — the journey is doorstep to doorstep, not kerb to kerb) and validated against ECM gap data, which records what journeys actually take across hundreds of repetitions. The adjustments: time-of-day bands (peak school-run and commute corrections), day-type (market day in the market town), season (winter global uplift, rural daylight weighting), and mode (each worker's actual transport). The floor rules: minimum travel allowances between non-adjacent calls that the rostering system physically enforces (the coordinator cannot book the impossible without an override that names itself in the audit trail), zero-travel permitted only for same-site pairs, and run-length maximums that keep the day's arithmetic inside working-time and human reality. Standards are reviewed on the analytics cycle and when the geography changes (the new bypass, the closed bridge, the new client cluster). And the design honesty extends to acceptance decisions: a referral whose postcode and time-band the service cannot reach without fiction is negotiated (different time window) or declined — taking undeliverable work is how travel fiction enters the roster wearing growth's clothes." },
      { heading: "Pay, Working Time and the Law's Floor", body: "The pay treatment is written where every worker can read it: travel time between assignments paid (per the service's model — actual time, standardised allowances, or salaried arrangements — but paid, and demonstrably so), mileage reimbursed at the stated rate with a claim process that pays promptly and doesn't make workers subsidise the service's fuel, and the National Minimum Wage arithmetic done properly: across each pay reference period, total pay divided by total working time — including travel between calls, which the law counts — meets or exceeds NMW, with the calculation audited periodically and after pay or roster model changes, because care providers fail this test chronically and the failures are both unlawful and discovered eventually. Working time protections ride alongside: rest breaks rostered realistically within long runs (the break that exists only on paper because travel ate it is a working-time failure), daily rest respected between late finishes and early starts (the 10pm-to-7am turnaround is watched), and the fatigue interface with safe driving (hr-021/hr-025) treated as the safety-critical loop it is: tired driving between calls is work-related road risk, and the roster is its first cause or first control. Where workers use public transport or walk, the same principles translate: journey time is working time between assignments, and the standards reflect the mode's reality." },
      { heading: "The Drive Itself", body: "Work driving standards compress into one sentence — legal, safe, and never traded for the schedule — and the policy builds the supports that make the sentence true. Vehicle gateway per ch-010: business-use insurance (the commuting-only policy voids on the first work journey between calls), licence verification on cycle, roadworthiness declared with MOT/service honesty, and the declined-to-drive option always available (the worker whose car died serves a walking or paired run while it's fixed, not a guilt trip). Behavioural absolutes per hr-025: no handheld use ever, hands-free minimised, navigation set before moving, and the office culture audited against its own rules — the coordinator who phones a driving worker and expects an answer is the policy's saboteur. The pressure valve stated in policy terms: late-because-safe is always defensible, lateness from honest travel is escalated as roster data not worker failing, and any manager found pressuring speed (explicitly or by arithmetic) answers for it. Weather protocols: the winter uplift applied by date not debate; severe-weather days triaged on dc-003's criticality (reds prioritised and bridged, ambers sequenced by need, greens rescheduled with communication), the pre-mapped assets deployed (4x4 owners, walkable local pairings, family bridges), and the stand-down call made centrally with alternative coverage arranged — the service never outsources the do-I-risk-the-ice decision to individual workers' consciences. Breakdown and incident: hr-026's net covers the stranded worker, the coordinator redistributes the run by criticality, and the incident machinery captures anything reportable." },
      { heading: "Watching the Fiction Indicators", body: "Travel fiction announces itself in patterns before it announces itself in tragedy, and the monthly analytics read for its signatures. The direct measures: ECM gap analysis versus rostered allowances per journey pair (systematic shortfalls fixed at the standard, not the worker); lateness cascades traced to their arithmetic origin (the run that fails at the same junction of calls daily); call-length erosion correlated with run position (calls clipped at run's end are travel debt being paid by clients); and mileage claims versus rostered geography (divergences meaning unrecorded journeys or wrong maps). The human measures: worker feedback actively gathered (the run review question in supervision: 'which journeys don't work?'), turnover and exit themes read for schedule pressure, and complaint patterns (the 'always late' complaints clustering on one run are a design confession). The responses are structural in order of honesty: rebuild the run (resequence, recluster, add travel), adjust the standards (the map was wrong), add capacity (the geography needs another worker), renegotiate or return work (the commissioned volume exceeds physics — put to the commissioner in writing with the data, because a service that silently absorbs undeliverable volume is choosing clipped calls on its clients' behalf). Governance sees the travel-honesty picture quarterly alongside dc-003's reliability data — the two are one system: the roster's arithmetic is the safety net's foundation, and every fiction in the first is a hole in the second." },
    ],
    appendices: [
      { title: "Run Design & Travel Standards Sheet", type: "template", body:
"RUN: ____ Worker mode (car/walk/bus/cycle — roster knows): ____\nPER JOURNEY PAIR: from→to | mapping estimate | local corrections (parking/door-to-door walk) | ECM actual (median) | ROSTERED ALLOWANCE (system-enforced minimum) | time-band adjustments (peak/school-run) | season uplift (winter, from date ____)\nRULES: zero-travel = same-building/adjacent ONLY | override names itself in audit trail | run-length max (working time + human reality): ____ | double-handed calls synchronised (no unpaid car-waiting) [ ]\nACCEPTANCE CHECK (new referrals): postcode+time-band reachable without fiction? negotiate window / decline — growth never imports fiction\nPAY STATEMENT (displayed to workers): travel-between-calls paid (model: ____) | mileage rate ____ claim process (prompt) | NMW check: total pay ÷ total working time INCL. travel ≥ NMW — audited (last: ____)\nWEATHER: winter uplift by date | severe-day triage (dc-003 reds bridged, greens rescheduled & told) | pre-mapped: 4x4 volunteers ____ walkable pairings ____ | stand-down decided CENTRALLY" },
      { title: "Travel-Fiction Indicator Dashboard (monthly)", type: "template", body:
"DIRECT SIGNATURES: ECM gaps vs rostered allowances (systematic shortfall pairs): ____ | lateness cascades (run/junction origin): ____ | call-length erosion by run position (clipped ends): ____ | mileage claims vs rostered miles (divergence): ____\nHUMAN SIGNALS: supervision run-review feedback ('which journeys don't work?') | exit/turnover themes (schedule pressure) | 'always-late' complaint clusters by run\nDRIVING SAFETY: speeding complaints/incidents | office phoned drivers mid-journey? (culture audit) | fatigue flags (late-finish→early-start turnarounds)\nRESPONSES (in order of honesty): rebuild run | fix standards (map wrong) | add capacity | COMMISSIONER LETTER with data (volume exceeds physics — never silently absorb)\nWorker protections check: late-because-safe never disciplined [ ] honest-travel lateness treated as roster data [ ] breakdown cover/redistribution worked [ ]\n→ Governance quarterly, read WITH dc-003 reliability (one system: roster arithmetic = safety net foundation)" },
    ],
  },
};
