// Ziproh Compliance — 2026 Expansion Set C (Group 5: Workforce & HR)
// All content original. Written tailoring-ready (generic base terms adapt per care setting).

import type { Document, DocumentContent } from "./documents";

export const EXPANSION_2026C_DOCS: Document[] = [
  {
    id: "hr-008",
    title: "DBS & Barred List Checking Policy",
    category: "Well-Led", subcategory: "Workforce & HR", keyQuestion: "Well-Led",
    serviceTypes: ["All"], regulators: ["CQC", "CI", "CIW", "RQIA"],
    version: "1.0", lastUpdated: "2026-07-15", status: "updated", readTime: 13,
    tags: ["DBS", "barred list", "safer recruitment", "disclosure", "update service", "referrals"],
    summary: "Criminal record and barred list checking done properly: the right level of check for each role, timing and renewal, risk-assessing disclosures rather than blanket-rejecting, the barred list duties that carry criminal liability, and the duty to refer.",
  },
  {
    id: "hr-009",
    title: "Right to Work Policy",
    category: "Well-Led", subcategory: "Workforce & HR", keyQuestion: "Well-Led",
    serviceTypes: ["All"], regulators: ["CQC", "CI", "CIW", "RQIA"],
    version: "1.0", lastUpdated: "2026-07-15", status: "updated", readTime: 11,
    tags: ["right to work", "immigration", "share codes", "sponsorship", "repeat checks"],
    summary: "Establishing and maintaining every worker's right to work: compliant checks before day one, online share codes and manual documents, the statutory excuse, follow-up checks for time-limited permission, sponsorship basics, and doing it all without discrimination.",
  },
  {
    id: "hr-010",
    title: "References & Employment History Verification Policy",
    category: "Well-Led", subcategory: "Workforce & HR", keyQuestion: "Well-Led",
    serviceTypes: ["All"], regulators: ["CQC", "CI", "CIW", "RQIA"],
    version: "1.0", lastUpdated: "2026-07-15", status: "updated", readTime: 11,
    tags: ["references", "employment history", "gaps", "verification", "safer recruitment", "Schedule 3"],
    summary: "The verification layer of safer recruitment: a full employment history with every gap explored, references that are actually verified rather than merely received, the most-recent-care-employer rule, conduct questions the regulations require, and giving references responsibly.",
  },
  {
    id: "hr-011",
    title: "Agency & Temporary Workers Policy",
    category: "Well-Led", subcategory: "Workforce & HR", keyQuestion: "Well-Led",
    serviceTypes: ["All"], regulators: ["CQC", "CI", "CIW", "RQIA"],
    version: "1.0", lastUpdated: "2026-07-15", status: "updated", readTime: 12,
    tags: ["agency staff", "temporary workers", "profiles", "induction", "continuity", "supervision"],
    summary: "Agency and bank workers held to the same standard as employed staff: agency vetting and contracts, per-worker profile verification before the first shift, a real orientation rather than a corridor briefing, supervision and feedback, and managing continuity so people are not cared for by strangers.",
  },
  {
    id: "hr-012",
    title: "Volunteers Policy",
    category: "Well-Led", subcategory: "Workforce & HR", keyQuestion: "Well-Led",
    serviceTypes: ["All"], regulators: ["CQC", "CI", "CIW", "RQIA"],
    version: "1.0", lastUpdated: "2026-07-15", status: "updated", readTime: 11,
    tags: ["volunteers", "vetting", "roles", "boundaries", "induction", "support"],
    summary: "Volunteers as a valued, managed part of the service: defined roles that never substitute for staff in regulated activity, proportionate vetting including DBS where eligible, induction and boundaries, named supervision, expenses, and ending arrangements well.",
  },
];

export const EXPANSION_2026C_CONTENT: Record<string, DocumentContent> = {
  "hr-008": {
    purpose: "This policy ensures no one works in this service without the criminal record and barred list checks the law and safer recruitment require — at the right level, at the right time, renewed on a sensible cycle, and interpreted with judgement rather than reflex. It also holds the two duties that carry criminal liability: never knowingly allowing a barred person to work in regulated activity, and referring to the Disclosure and Barring Service when the referral conditions are met.",
    scope: "Applies to all employees, bank workers, volunteers in eligible roles, and (via verification rather than direct application) agency workers and contractors with unsupervised access to people we support. Covers check levels, timing, the Update Service, handling disclosures, renewals, portability, referrals and record-keeping.",
    responsibilities: [
      { role: "Registered Manager", duties: [
        "Determine the correct check level for every role — enhanced with barred list check for regulated activity; and never downgrade to save time or cost",
        "Ensure checks are complete before unsupervised work begins, and that any exceptional supervised start pending a check is formally risk-assessed, time-limited and documented",
        "Risk-assess positive disclosures individually and fairly, documenting the decision and its reasoning",
        "Operate the renewal cycle and Update Service arrangements so checks do not silently age into meaninglessness",
        "Make DBS referrals when the statutory conditions are met — dismissal or removal (or would have dismissed had the person not left) because they harmed or posed a risk of harm to a person at risk" ] },
      { role: "All Staff", duties: [
        "Declare cautions and convictions as the role's disclosure requirements and the law on spent/unspent convictions require, including new matters arising during employment",
        "Report immediately if they become subject to investigation, arrest or charge for matters relevant to their role — concealment is itself a conduct issue",
        "Cooperate with renewals and Update Service status checks",
        "Never allow or cover for an unchecked or barred colleague working in regulated activity" ] },
    ],
    keyPoints: [
      "The check level follows the role, not the habit: roles in regulated activity with adults (or children) require an enhanced DBS check with the appropriate barred list check; roles with access but not regulated activity may qualify only for lower levels — eligibility is assessed per role and recorded, because over-checking is unlawful and under-checking is dangerous",
      "Barred means barred, absolutely: allowing a person barred from regulated activity to engage in it is a criminal offence by the service as well as the person — barred list information is acted on the day it is known, whatever the operational cost",
      "Checks come before unsupervised work: the clean sequence is offer conditional on checks, checks complete, then start; where a start genuinely cannot wait, the exceptional route is a documented risk assessment, genuine supervision arrangements, defined restrictions and a short time limit — never a quiet waiver",
      "A positive disclosure is a decision, not a verdict: cautions and convictions are risk-assessed individually — the offence, its age, its relevance to the role, patterns, the person's account and evidence of change — with the assessment documented and the decision made by the manager (with provider-level input for serious matters); blanket rejection is as poor a practice as blanket acceptance",
      "Checks age: a DBS certificate is a snapshot of one day — the service operates a renewal cycle (commonly three-yearly) or the DBS Update Service (with the worker's consent to status checks), plus the in-employment duty on staff to declare new matters, so currency is maintained rather than assumed",
      "Portability has rules: an existing certificate may be accepted only via the Update Service with a status check, at the right level and workforce, with identity verified — a paper certificate from a previous employer is history, not evidence",
      "The referral duty is real and personal: when the service dismisses or removes someone from regulated activity (or they resign first) because they harmed or posed a risk of harm to an adult or child at risk, a DBS referral is a legal duty — it is made even where the person left quietly, and failure to refer is an offence",
      "Confidentiality wraps the whole process: disclosure information is stored securely, seen only by those who need it for the decision, retained only as long as guidance allows, and never discussed casually — a person's past is data of the most sensitive kind",
    ],
    legislation: [
      "Safeguarding Vulnerable Groups Act 2006",
      "Protection of Freedoms Act 2012",
      "Rehabilitation of Offenders Act 1974 (Exceptions Order 1975)",
      "Police Act 1997 (Part V)",
      "Health and Social Care Act 2008 (Regulated Activities) Regulations 2014 — Regulation 19 and Schedule 3",
      "Data Protection Act 2018 / UK GDPR (criminal offence data)",
    ],
    sections: [
      { heading: "Check Levels, Eligibility and Timing", body: "Every role is mapped to its lawful check level and workforce before recruitment begins: enhanced with adults' barred list check for regulated activity with adults (personal care, health care, and the other defined activities); enhanced with children's barred list where the role includes regulated activity with children; enhanced without barred list, standard, or basic where the role's access justifies only those — the mapping is recorded so the service can show why each level was chosen, since applying for a higher check than the role permits is itself unlawful. Timing follows the safer recruitment sequence: conditional offer, identity verification to DBS standards, application, certificate seen (the original or digital result), barred list information confirmed clear, and only then unsupervised work. The exceptional supervised-start route — used sparingly, for genuine operational need — requires a documented risk assessment, real and rostered supervision, restrictions matched to the risk (no personal care alone, no lone shifts), a defined expiry, and manager review; it is never available where barred list information is outstanding for a regulated activity role." },
      { heading: "Handling Disclosures", body: "When a certificate discloses cautions, convictions or other relevant information, the service assesses rather than reacts. The structured risk assessment (Appendix A) considers: what the matter was and what it involved; how long ago and at what age; its relevance to this role and this population (an offence involving dishonesty reads differently for a finance role than a driving matter does; anything involving harm to vulnerable people reads gravely for every role); whether it is isolated or a pattern; the person's openness — a self-declared matter weighs differently from a concealed one; and evidence of change since. The conversation with the candidate is held with dignity, their account recorded, and the decision — appoint, appoint with conditions, or decline — documented with reasons and made by the manager with provider-level involvement for serious or borderline matters. The same structure governs matters arising in-employment: staff must declare new investigations, arrests, charges or convictions relevant to their role, and the service assesses with the added dimensions of suspension-pending-assessment where risk requires, the disciplinary interface, and safeguarding or regulator notifications where thresholds are met. Concealment of a declarable matter is treated as a serious conduct issue in its own right." },
      { heading: "Renewals, the Update Service and Portability", body: "Currency is maintained by design: the service either re-checks on a defined cycle (commonly every three years, recorded on the workforce compliance tracker with forward visibility) or uses the DBS Update Service — with the worker's registration maintained, written consent for status checks held, and status checks performed on the cycle and at any point of concern. In-employment declaration duties bridge the gaps between checks, and the two mechanisms together mean the service never relies on a stale snapshot. Portability of a certificate from elsewhere is accepted only through the Update Service route: the certificate is at the right level and workforce for this role, identity is verified, the original certificate is seen, and a status check confirms nothing has changed — anything less restarts the application. Agency workers are checked by their agency, but this service verifies rather than trusts: the agency profile must confirm the check level, date, certificate number and barred list status, per the Agency Workers policy, before the first shift." },
      { heading: "Referrals, Records and Confidentiality", body: "The referral duty is discharged without flinching: when the conditions are met — the service withdrew a person from regulated activity (dismissal, removal, redeployment away from it) or would have done had they not resigned, retired or been made redundant first, because they harmed or posed a risk of harm to a person at risk — a referral is made to the DBS with the evidence, regardless of whether the person left quietly, regardless of any agreed reference, and alongside (not instead of) any safeguarding, police or regulator notifications the facts require. Legal advice is sought where the conditions are unclear, but silence to avoid awkwardness is not an option the law allows. Records: the compliance tracker holds certificate numbers, dates, levels and renewal dates (not routinely the certificates themselves); disclosure detail and risk assessments are held securely with access restricted to those involved in the decision; retention follows DBS guidance and the records schedule; and destruction is secure. Criminal offence data is handled under its own lawful basis with an appropriate policy document per data protection law — the DBS process protects people precisely because it is itself handled with discipline." },
    ],
    appendices: [
      { title: "Disclosure Risk Assessment Form", type: "form", body:
"Candidate/staff member: ______  Role: ______  Check level & workforce: ______  Certificate date/no: ______\nMATTER(S) DISCLOSED: what, when, age at the time, disposal (caution/conviction/other relevant information)\nSELF-DECLARED in advance? [ ] yes / [ ] no (weight accordingly)\nASSESSMENT:\n– Relevance to THIS role & population (access, authority, lone working, finances, personal care): ______\n– Time elapsed & age at offence: ______\n– Isolated or pattern: ______\n– Candidate's account (meeting date, dignity maintained): ______\n– Evidence of change (work record, references, circumstances): ______\n– Any harm/vulnerable-person dimension (grave weight): ______\nDECISION: appoint [ ] / appoint with conditions: ______ [ ] / decline [ ]\nReasoning: ______\nDecided by (manager; provider input for serious/borderline [ ]): ______  Date: ______\nStorage: secure, restricted access, retention per DBS guidance & records schedule." },
      { title: "DBS Compliance Tracker & Referral Prompt", type: "template", body:
"TRACKER (per worker): name | role | regulated activity? | check level & workforce | certificate no & date | barred list checked (adults/children) [ ] | Update Service registered [ ] (consent held [ ]) | renewal/status-check due | in-employment declarations (date/outcome)\nEXCEPTIONAL SUPERVISED START (rare): risk assessment ref | restrictions | supervisor | expiry date | review\nNEW MATTER ARISING: declared (date) | risk assessment ref | suspension considered [ ] | safeguarding/regulator notifications assessed [ ]\nREFERRAL PROMPT — ask both questions whenever someone is dismissed/removed/resigns during concerns:\n1. Did we withdraw them from regulated activity (or would we have, had they not left)?\n2. Was it because they harmed or posed a risk of harm to a person at risk?\nBOTH yes → DBS referral is a LEGAL DUTY. Made (date/ref): ______ | Safeguarding/police/regulator notifications: ______\nNever traded away in settlement or reference agreements." },
    ],
  },
  "hr-009": {
    purpose: "This policy ensures every person who works for the service has, and keeps, the legal right to do that work in the UK — established by a compliant check before employment begins, maintained by follow-up checks where permission is time-limited, and conducted in a way that treats every candidate identically so that compliance never curdles into discrimination.",
    scope: "Applies to all employees and bank workers, with verification duties for agency workers and volunteers as their arrangements require. Covers pre-employment checks, online and manual checking routes, the statutory excuse, follow-up checks, sponsored workers, and record-keeping.",
    responsibilities: [
      { role: "Registered Manager / HR", duties: [
        "Ensure a compliant right to work check is completed and recorded before the first day of work — for every candidate, every time, with no exceptions for nationality, accent or familiarity",
        "Use the correct route for each person: the online share code service where applicable, manual document checks where permitted, or an identity service provider route where adopted",
        "Diary and complete follow-up checks before time-limited permission expires, and act lawfully when permission ends",
        "Understand sponsorship duties where the service holds a sponsor licence, or the boundaries of employing sponsored workers where it does not",
        "Keep the records that sustain the statutory excuse for the full retention period" ] },
      { role: "All Staff", duties: [
        "Provide genuine, current evidence of their right to work and inform the service of any change in their immigration status",
        "Cooperate with follow-up checks in good time before permission expires",
        "Raise concerns confidentially if they believe someone may be working without permission — this protects colleagues from exploitation as much as the service from penalty" ] },
    ],
    keyPoints: [
      "Everyone is checked, identically: the same check at the same stage for every candidate regardless of nationality or appearance — checking selectively is race discrimination, and the policy's answer to that risk is uniformity, not guesswork",
      "The check happens before work begins: a compliant check completed and recorded before day one establishes the statutory excuse against a civil penalty; a check done late protects nothing that happened before it",
      "The route matters: holders of digital immigration status are checked via the online share code service (viewing the profile, matching the photograph, retaining the result); documents from the permitted lists are checked manually in the prescribed way (original documents, in the person's presence, checked for consistency, copied and dated); and the service uses each route only where it is valid for that person's status",
      "The statutory excuse is only as good as the record: the dated copy or online check result, retained for the duration of employment plus the prescribed period, is what stands between the service and a penalty — the check that cannot be evidenced did not happen",
      "Time-limited permission is diarised: where a person's right to work expires, the follow-up check is scheduled and completed before expiry; the conversation is opened early and supportively, because renewals and applications take time and the person's livelihood is inside the timeline",
      "Pending applications are handled through the proper route: where a person has an outstanding in-time application, the Employer Checking Service route provides the verification and a time-limited excuse — assumption in either direction (working on, or dismissal in panic) is the error",
      "Sponsorship is its own discipline: where the service sponsors workers, the licence duties — record-keeping, reporting changes, monitoring — are met in full and on time (and the exploitation-prevention dimension is taken seriously: sponsored workers are never treated as captive labour); where the service does not sponsor, it is honest with candidates about that early",
      "Loss of the right to work is managed lawfully and humanely: verified facts first, the person heard, urgent advice where the position is unclear, and where employment must end it ends through fair process — with the distinction between someone who deceived and someone whose application failed reflected in how they are treated",
    ],
    legislation: [
      "Immigration, Asylum and Nationality Act 2006 (civil penalty regime)",
      "Immigration Act 2016 (offence of illegal working; employer offences)",
      "Equality Act 2010 (race discrimination in checking practice)",
      "Home Office Code of Practice on Preventing Illegal Working (current edition)",
      "Health and Social Care Act 2008 (Regulated Activities) Regulations 2014 — Regulation 19",
    ],
    sections: [
      { heading: "The Check", body: "The check is built into the recruitment sequence so no start date can precede it: at conditional offer, the candidate is told what evidence the check requires; before day one, the check is completed by a trained person using the correct route. Online checks (required for those with digital-only status, including most visa holders now): the candidate provides a share code, the checker views the Home Office online profile, confirms the photograph is the candidate, confirms the work permitted covers the role (hours, role restrictions for students and certain visas), and retains the dated profile result. Manual checks (for those whose status is evidenced by permitted physical documents): original documents from the current permitted lists, examined in the person's presence for authenticity and consistency (names, dates, photographs across documents), copied clearly, and the copy dated and signed as checked. Identity service provider routes, where the service adopts them for eligible document holders, follow the provider's certified process with the same recording discipline. Whichever route: the same process for every candidate, at the same stage, recorded the same way — uniformity is the discrimination defence, and the file shows it." },
      { heading: "Follow-Up Checks and Pending Applications", body: "Where permission is time-limited, the expiry enters the workforce compliance tracker at the point of hire with reminders far enough ahead to act — the follow-up conversation opens months, not days, before expiry, supportively: what application is planned or in flight, what the person needs, what the timeline looks like. The follow-up check is completed before expiry via the appropriate route. Where the person has made an in-time application, extension or appeal and their old permission has expired, the service uses the Employer Checking Service: a Positive Verification Notice provides a time-limited statutory excuse, diarised for re-check before it lapses. What the service does not do: allow work past expiry on optimism, or dismiss reflexively while a lawful route exists — both are failures, one of compliance, one of fairness. Where permission genuinely ends with no lawful basis to continue, employment is ended through fair process with the reasoning documented; where deception is discovered, the conduct route applies alongside; and in either case the human being in the process is treated with the dignity a livelihood decision deserves." },
      { heading: "Sponsorship and Overseas Workers", body: "Where the service holds a sponsor licence (skilled worker route for care roles), the licence is operated as the serious legal undertaking it is: certificates assigned only for genuine vacancies meeting the route's requirements; the reporting duties met on time (non-starts, absences, role or salary changes, terminations); record-keeping per the sponsor guidance; right to work checks still performed in full (sponsorship does not replace them); and the licence's health protected because the workers depend on it. The exploitation-prevention dimension is explicit: sponsored workers are never charged prohibited fees, never threatened with sponsorship withdrawal to suppress complaints or extract unpaid work, and have the same access to grievance, whistleblowing and support as any colleague — the service's conduct toward sponsored workers is a safeguarding and modern slavery matter as well as a licence one (see the Modern Slavery policy). Where the service does not sponsor, candidates are told at the earliest stage so no one builds plans on a route that is not there. Agency workers' right to work is checked by their agency, but the service's contract requires it and the profile confirms it — and any doubt on a live shift is resolved by verification, not assumption." },
      { heading: "Records and Assurance", body: "The right to work file for each worker holds: the check evidence (dated document copies or online check results), the route used, the checker, any Positive Verification Notices, follow-up check history, and — for sponsored workers — the sponsorship records the guidance requires. Retention runs for the duration of employment plus the prescribed post-employment period, then secure destruction. The workforce compliance tracker gives the manager forward visibility of every time-limited permission and follow-up due date, reviewed monthly, so nothing expires unnoticed. Assurance is periodic: an internal audit samples files for check completeness, route correctness, copy quality (an illegible copy defends nothing) and follow-up discipline, and the findings feed the governance review. The audit also checks the uniformity that guards against discrimination: every file, same process, same stage — because the strongest evidence that no one was singled out is a system that visibly treats everyone alike." },
    ],
    appendices: [
      { title: "Right to Work Check Record", type: "form", body:
"Candidate: ______  Role: ______  Start date (must be AFTER check): ______\nROUTE: [ ] Online share code (code: ____, profile viewed, photo matched, work conditions cover role incl. hours/restrictions)  [ ] Manual documents (originals seen in person; list & doc refs: ____)  [ ] IDSP (provider/ref: ____)  [ ] Employer Checking Service (PVN ref: ____, expires: ____)\nCONSISTENCY: names/dates/photo consistent across documents [ ] | discrepancies explored & resolved: ____\nEVIDENCE RETAINED: dated copy/online result on file [ ] | checked by (name/signature/date): ______\nPERMISSION: [ ] no time limit  [ ] time-limited — expiry: ______ → entered on tracker with early reminder [ ]\nSPONSORED WORKER? [ ] (sponsor duties applying — see sponsorship record)\nSame process applied at same stage as all candidates [ ] (uniformity = discrimination defence)\nRetention: duration of employment + prescribed period." },
      { title: "Time-Limited Permission & Follow-Up Tracker", type: "template", body:
"Per worker: name | role | permission type | expiry date | early conversation opened (date — months ahead) | application status (planned/in-time/decided) | ECS PVN (ref/expiry) if applicable | follow-up check completed (date/route/outcome) | next action\nMONTHLY REVIEW: all expiries next 6 months sighted [ ] | reminders working [ ] | no worker past expiry without PVN/lawful basis [ ]\nSPONSORSHIP (if licensed): reporting events log (non-starts, absences, changes, terminations — dates reported) | records per sponsor guidance [ ] | no prohibited fees/threats — exploitation check [ ] (link: Modern Slavery policy)\nAUDIT (periodic): files sampled | copies legible & dated | correct route used | uniform process evidenced | findings → governance review" },
    ],
  },
  "hr-010": {
    purpose: "This policy makes the paper trail of a person's working life tell the truth before they are trusted with people at risk. References that are requested but never verified, and employment histories with unexplored gaps, are how unsuitable people move quietly between care employers. This policy closes that route: full history, every gap explained, references verified at source, and the specific conduct questions the regulations require asked and answered.",
    scope: "Applies to all prospective employees and bank workers, with proportionate application to volunteers in eligible roles. Covers employment history collection, gap exploration, reference requesting and verification, the regulated-sector conduct questions, decisions on adverse or missing references, and the service's own practice when giving references.",
    responsibilities: [
      { role: "Registered Manager / HR", duties: [
        "Obtain a full employment history in the application — dated, complete, and signed as true — and explore every gap at interview with the outcome recorded",
        "Obtain a minimum of two references before unsupervised work, one of which is the most recent employer, and — for candidates who have worked in care or with vulnerable people — the most recent such employer, with the conduct questions asked",
        "Verify references at source: confirm the referee is who and what they claim, via independently sourced contact details, with verbal verification where authenticity is in doubt",
        "Assess adverse, lukewarm or missing references with judgement, documenting decisions and any compensating measures",
        "Ensure the service's own outgoing references are accurate, fair and never traded away in exit negotiations" ] },
      { role: "Recruiting Staff", duties: [
        "Never treat references as a formality: read them, compare them against the application, and pursue discrepancies",
        "Ask the gap questions at interview plainly and respectfully, and record the answers",
        "Escalate anything that does not add up — dates that conflict, referees who cannot be traced, care employers omitted from the history — before any offer is confirmed" ] },
    ],
    keyPoints: [
      "Full history means full: the application requires every role since leaving education (or across the period the regulations require), with dates, employers and reasons for leaving — a CV's highlights are not a history, and the history is signed as complete and true so a material omission is later a conduct matter",
      "Gaps are explored, not skipped: every gap is asked about at interview — most have innocent answers (caring responsibilities, travel, study, illness), and the point is not suspicion but completeness; the answer is recorded, and a gap that shifts under questioning is a flag pursued before offer",
      "Two references minimum, and the right ones: the most recent employer always; and where the candidate has ever worked in a care, health or vulnerable-persons setting, the most recent such employer as well — a candidate steering references away from their last care job is the classic warning sign, and this policy does not permit it",
      "References are verified, not just received: referee identity and role confirmed, contact details sourced independently (the organisation's switchboard or official domain, not only the number the candidate supplied), written references confirmed verbally where anything raises doubt — a forged reference passes the unverifying employer every time",
      "The conduct questions are asked explicitly: referees from care settings are asked whether the person was subject to disciplinary action or concerns involving the safety or welfare of people at risk, and why they left — satisfying the regulatory requirement for evidence of conduct in previous relevant employment",
      "Personal references have a defined, limited place: acceptable as supplements (a first job, a long absence from employment) but never as substitutes for obtainable employer references, and never from family members",
      "Adverse and missing references get judgement, not reflex: a lukewarm reference is discussed with the candidate; an adverse one is weighed with its context and the referee's reliability; a genuinely unobtainable one (employer dissolved) is documented with compensating checks — and 'we couldn't get it so we skipped it' appears nowhere in this service's files",
      "Giving references is done with the same integrity: accurate, fair, evidence-based, within the agreed format, never omitting safeguarding-relevant facts to ease someone's exit — a settlement agreement never buys silence about harm (see DBS referral duty), and the person giving the reference is authorised to do so",
    ],
    legislation: [
      "Health and Social Care Act 2008 (Regulated Activities) Regulations 2014 — Regulation 19 and Schedule 3",
      "Employment Rights Act 1996 and common law (negligent misstatement in references)",
      "Equality Act 2010 (fair treatment in verification practice)",
      "Data Protection Act 2018 / UK GDPR (reference data, candidate access rights)",
      "Safeguarding Vulnerable Groups Act 2006 (interface with referral duties)",
    ],
    sections: [
      { heading: "Employment History and Gaps", body: "The application form — not a CV substituted for it — collects the full history: every employer, role, dates to the month, and reason for leaving, plus periods of self-employment, education, unemployment and other activity, so the timeline has no unexplained space. The candidate signs the history as complete and true, converting omission from oversight into misrepresentation. At interview, the panel walks the timeline: each gap is asked about openly ('talk us through what you were doing between X and Y'), each answer recorded on the interview record, and each material discrepancy between application, CV and interview answers resolved before the process advances. The tone is professional and respectful — most gaps are life, not concealment — but the discipline is absolute, because the histories that matter are precisely the ones engineered to discourage the walking of the timeline. Care-sector omissions are treated with particular seriousness: a care role that surfaces in conversation but not on the form reopens the whole verification exercise." },
      { heading: "Requesting and Verifying References", body: "References are requested on conditional offer (or earlier with consent), in writing, on the service's structured form — which asks for dates, role, attendance and performance in factual terms, the regulated-sector conduct questions (disciplinary action, safeguarding concerns, reason for leaving, would you re-employ), and the referee's own name, role and relationship to the candidate. The minimum is two employer references including the most recent employer, plus the most recent care/vulnerable-persons employer where that differs; more are sought where the history warrants. Verification is the step that gives references their value: the referee's organisation and role are confirmed; contact details are obtained independently (official switchboard, published domain — a reference answered from a personal email address is verified by phone); and a short verbal confirmation call is made whenever authenticity, tone or content raises any question, with a note of the call filed. Open-ended delays are chased actively; the file shows requested, chased, received, verified for each reference, and no one starts unsupervised work ahead of that trail." },
      { heading: "Assessing What Comes Back", body: "References are read against the application, not merely filed: dates and roles are cross-checked, and discrepancies pursued with the candidate and the referee. An adverse reference is assessed with structure — what exactly is alleged or stated, how reliable and well-placed is the referee, what does the candidate say when given fair opportunity to respond, does anything corroborate either account — and the decision (proceed, proceed with conditions or heightened supervision, or withdraw) is documented with its reasoning. Lukewarm or minimal references ('dates only' policies are common) prompt the verbal call and, where substance cannot be obtained, additional referees. Genuinely unobtainable references — dissolved employers, overseas roles beyond reach — are documented as such with the efforts made, and compensated: an additional referee, extended probation objectives, closer early supervision, all recorded. Missing or unverified references are never quietly waived: the file for every appointed person shows either the completed trail or a documented, risk-assessed decision by the manager explaining precisely what could not be obtained and what was done instead — the standard an inspector, and a serious case review, will look for." },
      { heading: "Giving References", body: "The service's outgoing references meet the standard it demands of others: factually accurate, fair in overall impression (accuracy in fragments can still mislead), evidence-based (drawn from records, not memory or grievance), and provided by an authorised person — individual staff do not give organisational references, and personal references given by staff are labelled as such. Where concerns exist, they are stated factually and fairly: disciplinary findings and safeguarding outcomes that were established are disclosable facts; allegations that were investigated and not upheld are handled with care and usually not included; and investigations still open at departure are described factually as unresolved where the conduct questions require an answer. What is never done: trading a clean reference for a quiet exit where safeguarding-relevant findings exist — that practice moves risk to the next employer's service users, may breach the negligent misstatement duty to the recipient, and sits alongside the DBS referral duty (hr-008) which no agreement can contract away. Reference content is retained, disclosed to the subject on request per data protection law with third-party balancing applied, and reviewed for consistency so the service speaks with one honest voice." },
    ],
    appendices: [
      { title: "Structured Reference Request Form (regulated sector)", type: "template", body:
"To: (referee name, role, organisation — verified independently)  Re: (candidate, role applied for: work with adults at risk)\n1. Dates employed (from/to) & role(s): ______\n2. Reason for leaving: ______\n3. Attendance/reliability (factual): ______\n4. Performance & conduct (factual): ______\nREGULATED-SECTOR QUESTIONS:\n5. Was this person subject to any disciplinary action, current or expired? Details: ______\n6. Were there any concerns, allegations or investigations relating to the safety or welfare of adults or children at risk (including unresolved at departure)? Details: ______\n7. Would you re-employ? If not, why: ______\n8. Anything else relevant to work with people at risk: ______\nReferee declaration: name, role, relationship to candidate, signature/date\nSERVICE USE: received (date) | verified at source (how/date/by) | verbal confirmation (if made — note ref) | discrepancies vs application: ______" },
      { title: "Employment History Gap & Reference Decision Record", type: "form", body:
"Candidate: ______  Role: ______\nHISTORY: full history on application form (signed complete & true) [ ] | CV cross-checked [ ]\nGAPS WALKED AT INTERVIEW: gap (dates) | candidate's account | corroboration if pursued | resolved [ ]\n(repeat per gap)\nCARE-SECTOR ROLES: all included? [ ] | most recent care employer identified: ______\nREFERENCES: #1 most recent employer (req/chased/received/verified dates) | #2 most recent care employer or second employer (dates) | additional: ____\nADVERSE/LUKEWARM/MISSING: issue | referee reliability | candidate's response | corroboration | DECISION (proceed / conditions: ____ / withdraw) | reasoning | decided by/date\nUNOBTAINABLE reference: efforts made | compensating measures (extra referee / probation objectives / heightened supervision): ______\nNo unsupervised work before trail complete or documented risk-assessed decision [ ]  Manager sign-off: ______" },
    ],
  },
  "hr-011": {
    purpose: "This policy ensures that a person who arrives through an agency is held to the same standard as one the service recruited itself — vetted, oriented, supervised and answerable — because the people we support experience one workforce, not two. It also manages the quieter risks of temporary staffing: strangers delivering intimate care, orientation compressed to a corridor conversation, and continuity dissolving into a rota of new faces.",
    scope: "Covers all agency, temporary and externally-supplied workers, and the service's own bank workers where noted. Addresses agency selection and contracts, per-worker profile verification, booking practice, orientation, supervision and feedback, and continuity management.",
    responsibilities: [
      { role: "Registered Manager", duties: [
        "Contract only with agencies that evidence their vetting: the written agreement specifies the checks, training and occupational health confirmations the agency must hold and supply per worker",
        "Ensure a compliant profile is received and verified before any worker's first shift — DBS level/date/number, right to work, training, and registration (NMC or equivalent) where the role requires it",
        "Ensure every agency worker receives the documented orientation before working unsupervised, sized to the role and the setting",
        "Set booking practice to protect continuity: preferred-worker arrangements, block bookings, and limits on the proportion of agency staff on any shift",
        "Feed performance issues back to the agency formally, and bar individual workers or agencies where standards fail" ] },
      { role: "Shift Leaders & Staff", duties: [
        "Check on arrival: identity against the profile, the orientation record, and any restrictions (no lone working until X, medication competence not confirmed, etc.)",
        "Deliver and document the orientation for first-time workers — never waive it because the shift is busy",
        "Allocate work within the worker's confirmed competence: an unfamiliar worker does not take the medication round or the most complex care on trust",
        "Supervise proportionately, complete the end-of-shift feedback where required, and report concerns about any agency worker the same day" ] },
    ],
    keyPoints: [
      "The agency is vetted before its workers are: a written agreement (or framework terms) requires the agency to hold and evidence enhanced DBS with barred list checks at the right workforce, right to work, identity, references, training to the service's specified list, occupational health clearance, and professional registration where relevant — and to notify the service of anything that changes",
      "The profile gates the first shift: no agency worker starts without a per-worker profile verified by the service — DBS certificate number, date and level; right to work confirmed; training dates against the required list; registration PIN checked at source for registered professionals — and photographic identity is matched on arrival, because the profile protects nothing if a different person walks in",
      "Orientation is real and recorded: before unsupervised work, every first-time worker gets the documented orientation — fire and emergency procedures for this building, the people they will support (care plan headlines, risks, communication needs), medication arrangements and the limits of their role in them, safeguarding reporting routes, keys/codes/security, and who is in charge — repeated in condensed form after long absence or when the setting changes",
      "Competence is confirmed, not assumed: tasks with specific competence requirements (medication, PEG, catheter care, complex moving and handling) are allocated to agency workers only where the profile or in-house assessment confirms the competence — 'they're a nurse' is a registration, not a competence statement for this service's tasks",
      "Continuity is managed as a quality issue: preferred and returning workers are requested by name, block bookings favoured over shift-by-shift novelty, agency proportion per shift is capped so a shift is never majority-strangers, and people we support are told who is coming where that matters to them — familiarity is a safety control, not a luxury",
      "Supervision and feedback close the loop: agency workers are supervised proportionate to familiarity, end-of-shift or end-of-booking feedback is recorded for first-time and flagged workers, and structured feedback goes to the agency — praise as well as problems, because agencies staff the services that engage with them",
      "Problems are acted on formally: concerns about an agency worker trigger the same incident, safeguarding and (via the agency) disciplinary interfaces as for employed staff — the worker can be barred from the service, the agency is required to act, and safeguarding referrals and regulatory notifications are made by this service directly, never delegated to the agency's discretion",
      "Bank workers ride the same rails: the service's own bank staff meet identical vetting, training, orientation and competence standards — the flexibility is in the engagement, never in the checks",
    ],
    legislation: [
      "Health and Social Care Act 2008 (Regulated Activities) Regulations 2014 — Regulations 12, 18, 19 (provider retains responsibility for suitability)",
      "Conduct of Employment Agencies and Employment Businesses Regulations 2003",
      "Agency Workers Regulations 2010",
      "Safeguarding Vulnerable Groups Act 2006",
      "Working Time Regulations 1998",
    ],
    sections: [
      { heading: "Agency Selection and the Agreement", body: "The service maintains an approved list of agencies, each admitted through due diligence: evidence of the agency's vetting processes (sample profiles, policy documents), its complaint and disciplinary handling, its training provision against the service's required list, insurance, and references from comparable services. The written agreement converts expectations into obligations: the checks the agency must hold per worker and evidence in the profile; the required training list with refresher currency; occupational health confirmation; registration checks for professionals; notification duties (new DBS information, investigations, restrictions arising mid-engagement); the service's right to refuse or remove any worker; feedback and escalation routes; and rates and cancellation terms that make good practice commercially survivable. Framework or master-vendor arrangements are held to the same substance. The list is reviewed on a cycle informed by the feedback data — an agency whose profiles arrive late, incomplete or inaccurate is an agency being managed out." },
      { heading: "Profiles, Verification and Arrival", body: "The profile is the per-worker gate: received in advance of the first shift, checked by the service against the agreement's requirements — enhanced DBS with the correct barred list at the correct workforce (certificate number and date recorded; concerns about currency escalated to the agency), right to work confirmed by the agency, identity photograph, required training with dates in currency, occupational health confirmation, and for registered professionals a registration check the service repeats at source (NMC or equivalent register) rather than accepting on paper. Gaps hold the booking: an incomplete profile is an unfilled shift, and the roster plans accordingly rather than accepting degradation under pressure. On arrival, the loop closes physically: identity checked against the profile photograph, the orientation record checked or created, restrictions noted at handover, and the worker signed in so the fire roll call is true. Repeat workers are re-verified on a proportionate cycle and whenever the agency notifies a change — and the service's tracker holds the profile data so verification is an audit trail, not a memory." },
      { heading: "Orientation, Allocation and Supervision", body: "First-time orientation is a defined, documented process sized to the setting and role — typically covering: fire, evacuation and emergency procedures for this building including the worker's role in them; the layout, keys, codes and security expectations; the people the worker will support tonight — care plan essentials, risks (choking, falls, behaviours, communication), and what good support looks like for each; medication arrangements and precisely what this worker may and may not do within them; recording expectations; safeguarding recognition and this service's reporting routes; who leads the shift and how to escalate. It happens before unsupervised work, takes the time it takes, and is signed by both parties. Allocation then follows confirmed competence: the shift leader assigns work the profile and orientation support, holds back competence-gated tasks until confirmation exists, and pairs unfamiliar workers with experienced staff for the early hours. Supervision is proportionate and honest — closer for first-timers, lighter for known returners — and the end-of-shift feedback for first-time and flagged workers records what the next shift leader needs to know." },
      { heading: "Continuity, Feedback and Managing Failure", body: "Continuity is engineered: the service requests preferred workers by name, uses block bookings for sustained needs, caps the agency proportion on any shift (and the proportion unfamiliar with the setting), schedules agency use away from the most sensitive care where possible, and tells people we support who is coming when that matters to their wellbeing — because for a person with dementia or anxiety, a rotating cast of strangers is not a staffing inconvenience but a harm. Feedback flows both ways on a structured basis: worker-level feedback to the agency (competence, conduct, punctuality — commendation included), and service-level review of each agency (profile quality, fill rates, worker standard) informing the approved list. When things go wrong: concerns about an agency worker run through this service's incident and safeguarding procedures directly — investigation cooperation is required of the agency, the worker is stood down from the service pending resolution where risk requires, safeguarding referrals and regulator notifications are made by this service (never left to the agency), and the DBS referral interface is considered where the conditions could be met, coordinated between service and agency so the duty is discharged by the party legally holding it. The service's records — profiles, orientations, feedback, incidents — demonstrate that responsibility for suitability was never outsourced, because legally it cannot be." },
    ],
    appendices: [
      { title: "Agency Worker Profile Verification & First-Shift Checklist", type: "checklist", body:
"BEFORE FIRST SHIFT (profile verified by: ____ date: ____):\n[ ] Enhanced DBS + correct barred list, correct workforce — cert no: ____ date: ____\n[ ] Right to work confirmed by agency\n[ ] Identity photograph on profile\n[ ] Training in currency vs required list (mandatory + role-specific): ____\n[ ] Occupational health confirmation\n[ ] Registration (if professional): PIN ____ checked at source by service [ ]\n[ ] Restrictions/limits noted: ____\nIncomplete profile = unfilled shift. Do not accept degradation under pressure.\nON ARRIVAL:\n[ ] Identity matched to profile photo\n[ ] Signed in (fire roll call)\n[ ] Orientation: done previously (date ____) / delivered now (record below)\n[ ] Handover incl. restrictions & competence-gated tasks held back until confirmed\nEND OF SHIFT (first-time/flagged): feedback recorded → shift leader/agency" },
      { title: "Agency Orientation Record & Agency Review Log", type: "template", body:
"ORIENTATION (first shift at this setting): fire/evacuation & worker's role [ ] layout, keys/codes, security [ ] people supported tonight — care essentials & risks [ ] medication arrangements & this worker's limits [ ] recording expectations [ ] safeguarding recognition & OUR reporting routes [ ] shift leadership & escalation [ ]\nDelivered by/signed (both): ______  Time taken: ____\nRefresher (long absence/setting change): condensed re-orientation date: ____\nCONTINUITY CONTROLS: preferred workers requested by name [ ] block bookings used [ ] agency proportion cap per shift: ____ [ ] people informed of new faces where it matters [ ]\nAGENCY REVIEW (per agency, cycle: ____): profile quality/timeliness | fill rate | worker standard (feedback summary) | notification compliance | incidents & handling | decision (retain/improve/remove)\nWORKER CONCERN: incident/safeguarding refs | stood down pending [ ] | agency required to act (date) | OUR referrals/notifications made directly [ ] | DBS referral interface considered [ ]" },
    ],
  },
  "hr-012": {
    purpose: "This policy welcomes volunteers as a genuine enrichment of the service — companionship, activities, community connection, skills the rota cannot buy — while keeping the boundaries that protect everyone: volunteers are never a substitute for staff, never carry regulated activity the service is paid to provide, and are vetted, inducted and supported in proportion to what their role actually involves.",
    scope: "Covers all volunteers engaged by the service, from occasional activity helpers to regular befrienders, including trustees or community visitors where they take on volunteer roles with people we support. Covers role definition, recruitment and vetting, induction, boundaries, supervision, recognition, and ending arrangements.",
    responsibilities: [
      { role: "Registered Manager / Volunteer Coordinator", duties: [
        "Define every volunteer role in writing before recruitment: what it involves, what it must never involve, and the vetting the role's access justifies",
        "Vet proportionately but properly: DBS checks where the role is eligible, references for all regular roles, and honest assessment of suitability",
        "Deliver the induction and boundaries briefing before the volunteer works with people, and refresh it periodically",
        "Provide named supervision and support for every volunteer — someone they report to, learn from, and can raise concerns with",
        "Ensure volunteers never fill staff gaps, deliver personal or clinical care, or carry responsibilities the rota should hold" ] },
      { role: "Volunteers", duties: [
        "Work within the written role and its boundaries — and ask, rather than improvise, when a person requests something outside them",
        "Follow safeguarding, confidentiality, and health and safety expectations as inducted, and report concerns immediately to staff",
        "Accept no gifts, loans or bequests beyond the token level the policy allows, and never handle people's money or valuables unless the role explicitly, exceptionally provides for it with controls",
        "Sign in and out, wear identification, and take direction from staff during any emergency" ] },
      { role: "All Staff", duties: [
        "Support volunteers as colleagues within their role, never delegate staff tasks to them, and model the boundaries",
        "Report boundary drift early and kindly — most drift is goodwill, not misconduct, and early correction protects the volunteer too" ] },
    ],
    keyPoints: [
      "A written role comes first: no volunteer is recruited to 'help out generally' — the role description says what they do (activities, befriending, gardening, driving with controls, mealtime companionship short of feeding-risk support), what they never do (personal care, medication, clinical tasks, lone responsibility for anyone, money handling), and what vetting it requires",
      "Volunteers supplement, never substitute: a volunteer must not fill a staffing gap, be counted in staffing numbers, or hold responsibilities the rota should hold — if the service cannot run safely without its volunteers, the staffing establishment is wrong, and the fix is recruitment, not reliance",
      "Vetting is proportionate to access, and honest about eligibility: roles involving regular unsupervised contact with people at risk are assessed for DBS eligibility and checked at the level the role lawfully supports; references are taken for all regular roles; and roles designed to remain incidental and supervised are kept genuinely so — the design is not a device to dodge checks",
      "Induction is real: safeguarding recognition and reporting, confidentiality (what volunteers will inevitably see and must never share, including online), fire and emergency basics, infection control basics, the role's boundaries, and who supervises them — delivered before contact, recorded, refreshed annually",
      "Boundaries protect everyone: no gifts beyond token level, no loans or financial involvement, no wills or bequests solicited or knowingly accepted, no personal-contact-detail exchange or social media friendships outside the service's channels, no transporting people except in defined driver roles with licence, insurance and MOT verified — drift is corrected early and kindly, and serious breaches end the arrangement",
      "Supervision is named and regular: every volunteer has a named supervisor, an agreed check-in rhythm, and a route to raise concerns — including about staff, which is why volunteers are told about whistleblowing routes too; volunteers are often the fresh eyes that spot what familiarity has normalised",
      "Insurance and safety cover them: volunteers are covered by the service's liability insurance (confirmed, not assumed), included in fire roll calls via sign-in, risk-assessed where the role or the individual needs it, and their expenses reimbursed against receipts so no one pays to give their time — and expenses never become disguised wages that blur the legal status",
      "Endings are managed with the same care: volunteers leave with thanks and, where appropriate, a reference; where concerns end the arrangement, the ending is documented, safeguarding and (in the rare eligible cases) DBS referral duties are considered exactly as for staff, and the people the volunteer supported are told sensitively — a befriender's disappearance is a loss that deserves an explanation",
    ],
    legislation: [
      "Safeguarding Vulnerable Groups Act 2006 (regulated activity and eligibility)",
      "Rehabilitation of Offenders Act 1974 (Exceptions Order — volunteer eligibility)",
      "Health and Social Care Act 2008 (Regulated Activities) Regulations 2014 — Regulations 12, 13, 19 as applicable",
      "Health and Safety at Work etc. Act 1974 (duties to volunteers as non-employees)",
      "Data Protection Act 2018 / UK GDPR",
    ],
    sections: [
      { heading: "Roles and Recruitment", body: "Volunteering begins with design: the coordinator writes the role before seeking the person — purpose, activities, time commitment, location, supervision arrangements, the boundary list, and the vetting the role's access justifies. Roles are honest about their access: a weekly activities helper working alongside staff differs from a one-to-one befriender visiting rooms alone, and the vetting requirement tracks that difference rather than the label. Recruitment is welcoming but real: an application or expression of interest, an informal interview exploring motivation and expectations (and gently screening for the misplaced expectations that cause later drift — rescuing, over-attachment, evangelising), references for regular roles, DBS checks where the role is eligible at the level it supports, and a mutual trial period in which either side can step back easily. The service is candid at recruitment about what volunteers cannot do, because the commonest volunteer problem is not bad faith but generous people asked, by residents or by busy staff, to do a little more than the role allows — and the defence starts with clarity on day one." },
      { heading: "Induction and Boundaries", body: "Before working with people, every volunteer completes the induction: safeguarding — what abuse and neglect look like, and the absolute rule that concerns go to staff the same day, with the reporting route named; confidentiality — everything seen and heard stays inside the service, nothing identifiable is shared anywhere including social media, and photography follows the service's consent rules; fire and emergency basics including their own role (sign in, follow staff direction, assemble); infection control basics (hand hygiene, staying away when unwell); and the role's specific boundaries walked through with examples. The boundaries framework is explained as protection, not suspicion: token gifts only and declared; no loans, purchases on behalf, or financial involvement of any kind; no personal contact details or private social media contact; no transporting people outside defined driver roles (licence, insurance for volunteer use, MOT verified annually); no personal care — if a person needs the toilet, needs feeding support with any risk, needs medication or clinical attention, the volunteer fetches staff, every time; and no promises of visits, outings or advocacy the service has not agreed. The volunteer signs the agreement (Appendix A), takes identification, and knows their named supervisor before their first session." },
      { heading: "Supervision, Support and Recognition", body: "Every volunteer has a named supervisor and a rhythm of contact proportionate to the role — a brief word each session for group helpers, scheduled one-to-ones for befrienders working alone with individuals. Supervision is supportive in both directions: the volunteer's observations are actively sought (volunteers spot mood changes, environmental issues and practice drift that staff normalise), their questions answered, boundary pressures surfaced before they become breaches ('Mrs H keeps asking me to bring her sherry — what do I say?'), and their development supported with training where the role benefits (dementia awareness, communication, activity skills). Volunteers are told the whistleblowing route explicitly and that it protects them too. Recognition is deliberate — thanks, inclusion in service events, references on request, and small marks of appreciation within the gifts policy — because retention of good volunteers is a service asset, and feeling used rather than valued is the commonest reason they leave. Records are kept per volunteer: role, vetting, induction, agreement, supervision notes, training, incidents and recognition — proportionate in depth, professional in standard." },
      { heading: "Problems, Endings and the Staffing Boundary", body: "Boundary drift is corrected early, kindly and in supervision — most drift is goodwill, and a volunteer corrected with respect usually becomes the policy's best advocate. Serious concerns run through the service's real procedures: allegations against a volunteer follow the safeguarding-allegations route exactly as for staff (including LADO-equivalent referral where children are involved, and regulator notification where thresholds are met); investigation may suspend the volunteering meanwhile; and where a volunteer in an eligible role is removed because they harmed or posed a risk of harm, the DBS referral duty is considered exactly as it would be for an employee. Endings of every kind are managed: retiring volunteers leave with thanks and a reference where earned; the people they supported are told sensitively and, where a befriending relationship was significant, the loss is acknowledged and alternative connection offered rather than left as silent absence. Finally, the staffing boundary is audited: the coordinator and manager review periodically that no volunteer has drifted into the rota's work — covering shifts, being counted in numbers, doing personal care 'just this once' — because that drift is unfair to the volunteer, unlawful in regulated activity terms, and a signal that the staffing establishment needs fixing through the workforce plan, not through goodwill." },
    ],
    appendices: [
      { title: "Volunteer Role Description & Agreement", type: "form", body:
"Role title: ______  Purpose: ______  Activities included: ______\nNEVER included: personal care | medication/clinical tasks | lone responsibility for any person | money/valuables handling | transporting people (unless defined driver role — licence/insurance/MOT verified annually [ ]) | covering staff shifts or being counted in staffing numbers\nCommitment: days/times ____  Location(s): ____  Named supervisor: ____  Check-in rhythm: ____\nVETTING (per role access): DBS eligible? [ ] level: ____ (cert no/date: ____) | references (regular roles): ____ | trial period: ____\nINDUCTION completed (date): safeguarding & reporting route [ ] confidentiality incl. social media [ ] fire/emergency & sign-in [ ] infection control basics [ ] boundaries walked through with examples [ ]\nBOUNDARIES AGREED: token gifts only, declared | no loans/financial involvement | no private contact details/social media | no promises beyond the role | concerns to staff same day\nInsurance cover confirmed for this role [ ]  Expenses: reimbursed against receipts [ ]\nSigned (volunteer / coordinator / date): ______" },
      { title: "Volunteer Supervision & Ending Record", type: "template", body:
"SUPERVISION LOG: date | volunteer | matters raised by volunteer (observations, questions, boundary pressures) | guidance given | training/development agreed | next contact\nANNUAL REFRESH: induction themes refreshed (date) | agreement re-signed [ ] | DBS/vetting currency checked (eligible roles) [ ]\nSTAFFING-BOUNDARY AUDIT (periodic): any volunteer covering staff work / counted in numbers / personal care drift? findings & fix (workforce plan, not goodwill): ______\nCONCERN/ALLEGATION: ref | safeguarding-allegations route followed [ ] | volunteering suspended pending [ ] | outcome | DBS referral considered (eligible roles, harm/risk conditions) [ ] | regulator notification assessed [ ]\nENDING: date | reason (retirement/moved on/concerns) | exit conversation & thanks [ ] | reference given [ ] | people supported informed sensitively [ ] | significant befriending loss acknowledged & alternative connection offered [ ]" },
    ],
  },
};
