// Ziproh Compliance — 2026 Expansion Set F (Group 8: Primary Care, Clinics & Specialist Health)
// All content original. Written tailoring-ready (generic base terms adapt per care setting).

import type { Document, DocumentContent } from "./documents";

export const EXPANSION_2026F_DOCS: Document[] = [
  {
    id: "pc-001",
    title: "Clinical Governance Policy",
    category: "Well-Led", subcategory: "Primary Care & Clinics", keyQuestion: "Well-Led",
    serviceTypes: ["Primary Care", "Clinic", "All"], regulators: ["CQC", "CI", "CIW", "RQIA"],
    version: "1.0", lastUpdated: "2026-07-15", status: "updated", readTime: 13,
    tags: ["clinical governance", "clinical audit", "significant events", "clinical leadership", "quality improvement", "MHRA alerts"],
    summary: "The framework that makes clinical quality somebody's job and everybody's habit: named clinical leadership, the audit cycle that closes, significant event analysis without blame theatre, safety alerts actioned, clinical supervision and appraisal for the clinical team, and a governance rhythm that reads the right data monthly.",
  },
  {
    id: "pc-002",
    title: "Chaperone Policy",
    category: "Safe", subcategory: "Primary Care & Clinics", keyQuestion: "Safe",
    serviceTypes: ["Primary Care", "Clinic"], regulators: ["CQC", "CI", "CIW", "RQIA"],
    version: "1.0", lastUpdated: "2026-07-15", status: "updated", readTime: 10,
    tags: ["chaperone", "intimate examination", "consent", "dignity", "trained chaperones", "documentation"],
    summary: "Chaperoning done as protection for everyone: the offer made for every intimate examination and recorded whichever way it goes, trained chaperones (never the receptionist grabbed mid-task), the chaperone's active role during the examination, what happens when no chaperone is available, and the documentation that protects patient and clinician alike.",
  },
  {
    id: "pc-003",
    title: "Consent to Examination & Treatment Policy",
    category: "Effective", subcategory: "Primary Care & Clinics", keyQuestion: "Effective",
    serviceTypes: ["Primary Care", "Clinic"], regulators: ["CQC", "CI", "CIW", "RQIA"],
    version: "1.0", lastUpdated: "2026-07-15", status: "updated", readTime: 13,
    tags: ["consent", "material risks", "capacity", "Gillick", "implied consent", "shared decisions"],
    summary: "Consent as a conversation, not a signature: the material-risk standard (what THIS patient would want to know), proportionate consent from implied to written, capacity assessed decision-by-decision with the MCA machinery, children and Gillick competence, consent that can be withdrawn mid-procedure, and records that capture the dialogue rather than just the form.",
  },
  {
    id: "pc-004",
    title: "Patient Records Policy",
    category: "Well-Led", subcategory: "Primary Care & Clinics", keyQuestion: "Well-Led",
    serviceTypes: ["Primary Care", "Clinic"], regulators: ["CQC", "CI", "CIW", "RQIA"],
    version: "1.0", lastUpdated: "2026-07-15", status: "updated", readTime: 12,
    tags: ["patient records", "clinical coding", "contemporaneous", "amendments", "access", "summarisation"],
    summary: "Clinical records that serve the next clinician and the patient's whole story: contemporaneous, attributable entries with accurate coding, the amendment disciplines that never overwrite history, incoming correspondence workflows that don't bury red flags, patient online access managed safely, summarisation and record transfers, and audit that samples quality, not just presence.",
  },
  {
    id: "pc-005",
    title: "Referral Management Policy",
    category: "Effective", subcategory: "Primary Care & Clinics", keyQuestion: "Effective",
    serviceTypes: ["Primary Care", "Clinic"], regulators: ["CQC", "CI", "CIW", "RQIA"],
    version: "1.0", lastUpdated: "2026-07-15", status: "updated", readTime: 12,
    tags: ["referrals", "two-week wait", "urgent referrals", "tracking", "safety netting", "failed referrals"],
    summary: "The referral as a safety-critical handover: urgency graded right and never downgraded silently, urgent-suspected-cancer referrals tracked to first appointment, the tracking system that catches the lost referral before the patient's disease does, safety-netting the patient with what-to-expect-and-when, rejected and bounced referrals owned rather than filed, and audit of the whole pipeline.",
  },
];

export const EXPANSION_2026F_CONTENT: Record<string, DocumentContent> = {
  "pc-001": {
    purpose: "This policy makes clinical quality a system rather than a hope: named leadership carrying defined clinical responsibilities, an audit programme whose cycles actually close, significant events analysed for learning rather than blame, safety alerts landing on the right desk with deadlines, and a monthly governance rhythm that reads the clinical vital signs. Clinical services drift without governance the way ships drift without helms — gradually, then onto rocks.",
    scope: "Covers the clinical governance framework for services delivering clinical care: leadership roles, clinical audit, significant event analysis, safety alert handling (with saf-035's MHRA machinery), clinical supervision and appraisal interfaces, prescribing oversight where applicable, and the governance data rhythm. It sits above and connects the clinical policies rather than replacing them.",
    responsibilities: [
      { role: "Provider / Registered Manager", duties: [
        "Appoint the clinical lead with defined responsibilities, real authority and protected time — a title without hours is decoration",
        "Resource the governance machinery: audit time, meeting rhythm, the data infrastructure that surfaces the numbers",
        "Hold the interfaces: professional registration checks (hr-011/hr-027), indemnity verification for clinical staff, and the fit-and-proper duties",
        "Act on what governance finds: the audit that shows a problem funds its fix" ] },
      { role: "Clinical Lead", duties: [
        "Own the clinical audit programme: topics chosen by risk and evidence, cycles completed to re-audit, findings actioned",
        "Chair significant event analysis with the just-culture disciplines: systems first, individuals only where conduct genuinely diverged",
        "Receive and triage safety alerts (medicines, devices, national patient safety alerts) with actions evidenced by deadline",
        "Provide or arrange clinical supervision for the clinical team, and feed appraisal and revalidation processes for registered professionals",
        "Report the clinical picture to governance monthly: audits, events, alerts, prescribing signals, infection markers" ] },
      { role: "All Clinical Staff", duties: [
        "Work within their registration, competence and the service's clinical policies — and say so when asked to exceed any of the three",
        "Report significant events, near-misses and clinical concerns the same day, and engage with analysis as contributors, not defendants",
        "Participate in audit, supervision and CPD as the professional infrastructure it is",
        "Keep their registration, revalidation and indemnity current, and declare anything that changes their fitness to practise" ] },
    ],
    keyPoints: [
      "Leadership is named and resourced: a clinical lead (appropriate registration and seniority for the service's clinical scope) with written responsibilities, protected sessions for the governance work, deputising arrangements, and a direct line to the provider that bypasses operational hierarchy when patient safety demands it",
      "The audit programme is a wheel, not a shelf: an annual plan choosing topics by risk (high-volume, high-harm, alert-driven, complaint-driven and incident-driven candidates first), standards drawn from evidence (national guidance, the service's own policies), measurement, findings with owners and deadlines, change implemented, and the re-audit that proves the change worked — the cycle's closure rate is itself a governance metric, because audits that never re-audit are inspections of the past, not improvements of the future",
      "Significant events get analysis, not autopsy-by-blame: the SEA process (what happened, why — systems before individuals, what was good as well as what failed, what changes, who owns them, when reviewed) run on a just-culture footing where honest accounts are safe, with the conduct interface reserved for genuine divergence (recklessness, concealment) and the learning shared in forms that teach without shaming",
      "Safety alerts have a landing strip: national patient safety alerts, medicines recalls and MHRA device alerts (saf-035's machinery) arrive at a named inbox, are triaged by the clinical lead within the stated days, actioned against the service's actual stock/equipment/practice with evidence, and closed with a record — 'we saw it and it didn't apply' is a documented conclusion, not a silence",
      "Clinical supervision is structured and real: registered professionals receive clinical (not just managerial) supervision at a stated frequency — case discussion, decision review, professional development — with records kept, and the appraisal/revalidation interfaces (NMC, HCPC, GMC as applicable) supported by the service's data (audit participation, SEA involvement, CPD records)",
      "Prescribing and clinical practice oversight fits the service's scope: where prescribing happens, its signals are watched (antibiotic stewardship, high-risk drug monitoring per the medication policies' machinery, prescriber-level variation read with intelligence); where clinical procedures happen, competence runs through hr-027's gateways with clinical assessors",
      "The governance rhythm reads the right data monthly: audit progress, significant events and themes, alert status, complaint and incident clinical threads, infection markers, prescribing signals, registration/indemnity/revalidation currency, and the training matrix's clinical rows — one meeting, one dataset, minuted actions, and escalation lines to the provider that are used",
      "The patient's voice enters the clinical loop: complaints and feedback with clinical dimensions route into SEA and audit topic selection, patient-reported outcomes are gathered where the service's work suits them, and the governance meeting reads what patients said alongside what clinicians measured",
    ],
    legislation: [
      "Health and Social Care Act 2008 (Regulated Activities) Regulations 2014 — Regulations 12, 17, 19",
      "Health and Social Care Act 2008 — Code of Practice on IPC (clinical interfaces)",
      "Medical Act 1983 / Nursing and Midwifery Order 2001 (professional regulation interfaces)",
      "Health and Safety at Work etc. Act 1974",
      "NHS contract and national patient safety alert requirements (where commissioned)",
    ],
    sections: [
      { heading: "Leadership and Structure", body: "The clinical governance structure is small enough to work and defined enough to survive personnel change. The clinical lead role is written: registration and seniority matched to the service's clinical scope (the GP or senior nurse for primary care; the nurse lead for clinic services), responsibilities enumerated (audit programme, SEA chairing, alert triage, supervision arrangements, the monthly report), protected time quantified in sessions, a named deputy for absence, and the safety bypass stated — the clinical lead speaks to the provider directly on patient-safety matters without operational intermediation. Around the lead, the clinical team's professional infrastructure is maintained as a register: registrations checked at source on the cycle (hr-027's currency logic applied to professional registration), revalidation dates tracked with support offered ahead of them, indemnity confirmed annually and at change (the uninsured clinician is an uncommissionable risk), scope-of-practice statements per clinician (what each is trained and agreed to do here — the practice nurse's scope differs from the ANP's, and the document prevents drift in both directions), and the clinical rows of the training matrix (resuscitation at the service's required level, anaphylaxis, safeguarding levels per role) kept current with expiry management. The structure meets monthly as the clinical governance meeting — clinical lead, manager, and the roles the agenda needs — with the dataset (below) circulated before and the minutes carrying actions with owners and dates into the next meeting's first item." },
      { heading: "Audit That Closes Its Loop", body: "The annual audit plan balances the mandatory, the risky and the curious: infection control audits per the IPC code's expectations, medicines and prescribing audits where the service prescribes or administers (antibiotic choices against guidance, high-risk drug monitoring completion, MAR quality), record-quality audits (pc-004's sampling), clinical-topic audits chosen by risk signals (the complaint about wound care becomes a wound-documentation audit; the significant event about a missed result becomes pc-005/test-results pipeline audits), and re-audits scheduled as first-class citizens. Each audit is designed before it is counted: the standard stated with its source, the sample defined, the measurement honest (case-note audits done by peers with calibration, not self-marked homework), findings written with the gap quantified, actions owned and dated, and the re-audit booked at design time — because the re-audit booked later is the re-audit that never happens. Results flow two ways: into the governance meeting as progress-and-closure data, and back to the clinical team as learning (the audit presentation that names systems, not colleagues, teaches; the league table shames and corrupts the next sample). The programme's own health is audited annually: cycles closed versus opened, time-to-action, the balance of topics against the service's actual risk profile, and the honest question of whether any audit changed anything a patient would notice." },
      { heading: "Significant Events and Safety Alerts", body: "Significant event analysis is the service's clinical conscience, run to a rhythm and a temperament. What qualifies: actual harm events, near-misses with harm potential, process failures with clinical consequence (the lost referral, the unactioned result, the medication error per dc-012/saf-026's machinery), diagnostic surprises (the admission that reframes last month's presentations), deaths where the service's care preceded them, and the positive events worth decoding (the deterioration caught early — what worked?). The process: reported same-day through the incident route, triaged by the clinical lead (immediate-safety actions first — the today-problem fixed today), analysed at the SEA meeting with the structured questions (chronology, contributing factors — systems first: workload, process, communication, equipment, training; individual factors only where conduct genuinely diverged from what a reasonable peer would do), the duty of candour thresholds applied (gov-001's machinery — the patient or family told honestly where harm occurred), changes agreed with owners and review dates, and the learning distributed (team meetings, the anonymised learning note, the induction case library). The just-culture line is policed both ways: honest accounts are safe from punishment, and genuine misconduct is not laundered as 'systems learning'. Safety alerts run their landing strip in parallel: the named inbox checked on the stated rhythm, triage within days (applies / doesn't apply / applies with actions), actions evidenced (stock checked and quarantined, practice changed and communicated, equipment per saf-035), closure recorded, and the alert log reviewed at the governance meeting — with the annual test being an inspector's question the service can answer in one minute: show me the last five alerts and what you did." },
      { heading: "Supervision, Data and the Monthly Rhythm", body: "Clinical supervision is scheduled, structured and distinct from line management: registered clinicians receive case-based supervision at the stated frequency (the model fitting the service — one-to-one with the clinical lead, peer group formats, external supervision for isolated roles), covering caseload review, decision-making, professional development and the emotional weight of clinical work (hr-021's pathways available for the heavy cases), recorded in supervision notes that respect confidentiality while evidencing occurrence. Appraisal and revalidation are supported with the service's evidence: audit participation, SEA involvement, CPD time protected per the training policies, and the multi-source feedback the professional cycles require. The monthly governance dataset assembles the clinical vital signs: audit cycle status, significant events (count, themes, action closure), alert log status, clinical complaints and their threads, infection markers (per the IPC audit programme), prescribing signals where applicable, professional currency (registrations, revalidations, indemnity, clinical training rows), and the patient-voice digest. The meeting works the dataset with a standing agenda, minutes actions, and escalates on defined triggers: any red-rated finding, event themes recurring across months, currency lapses, and anything the clinical lead judges provider-level. Annually, the whole framework is reviewed against the year's evidence — did governance find its problems before patients did, and where it didn't, what does next year's programme change?" },
    ],
    appendices: [
      { title: "Clinical Governance Monthly Dataset & Meeting Agenda", type: "template", body:
"DATASET (circulated before): AUDIT — cycles open/closed, actions overdue, re-audits due | SEA — new events, themes, action closure %, candour compliance | ALERTS — received/triaged/actioned/closed (any overdue: RED) | COMPLAINTS/INCIDENTS — clinical threads | INFECTION — IPC audit markers | PRESCRIBING (if applicable) — stewardship & high-risk monitoring signals | CURRENCY — registrations/revalidation/indemnity/clinical training expiries (60-day horizon) | PATIENT VOICE — feedback digest\nAGENDA: 1. Last minutes' actions (owners report) 2. Red items & escalations 3. SEA learning review 4. Audit progress & closures 5. Alert log 6. Currency & workforce clinical items 7. Patient voice 8. Topics for next audit cycle 9. Provider escalations agreed\nESCALATION TRIGGERS (to provider, in writing): red findings | recurring event themes | currency lapse of any practising clinician | clinical lead's judgement — bypass line available always" },
      { title: "Significant Event Analysis Record", type: "form", body:
"EVENT: ref | date | reported by (same-day [ ]) | type (harm/near-miss/process failure/diagnostic surprise/death/positive learning)\nIMMEDIATE SAFETY ACTIONS (today-problem fixed today): ______\nCHRONOLOGY (factual, timed): ______\nCONTRIBUTING FACTORS — SYSTEMS FIRST: workload/staffing | process & protocol | communication & handover | equipment & IT | training & competence | environment || INDIVIDUAL factors ONLY where conduct genuinely diverged from reasonable peer practice: ______\nWHAT WENT WELL (name it — it teaches): ______\nDUTY OF CANDOUR: threshold met? [ ] → patient/family told (date, by, record ref): ______\nCHANGES: action | owner | date | review || LEARNING DISTRIBUTED: team meeting [ ] anonymised note [ ]\nJUST-CULTURE CHECK: honest accounts protected [ ] | genuine misconduct routed properly, not laundered [ ]\nRE-REVIEW DATE (did the changes hold?): ______  Chair (clinical lead): ______" },
    ],
  },
  "pc-002": {
    purpose: "This policy makes the chaperone a working protection rather than a poster in the waiting room. Intimate examinations create vulnerability in two directions — the patient exposed to potential misconduct or misunderstanding, the clinician exposed to allegation without witness — and a trained chaperone, properly offered and properly deployed, protects both. The policy's enemies are the unoffered chaperone, the untrained stand-in, and the undocumented decision.",
    scope: "Covers chaperoning for intimate examinations and procedures and for any consultation where patient or clinician requests one: the offer, trained chaperone requirements, the chaperone's role in the room, declines and unavailability, remote consultation dimensions, and documentation. It applies to all clinicians including visiting professionals working on the premises.",
    responsibilities: [
      { role: "Registered Manager / Clinical Lead", duties: [
        "Maintain a pool of trained chaperones sufficient for the clinic's pattern — enough that 'none available' is rare and never routine",
        "Ensure the offer is systematised: poster and leaflet visibility, clinician habit, and the record templates that prompt",
        "Train chaperones formally: the role, what to watch, positioning, speaking up, and documentation — with DBS checks appropriate to the role",
        "Audit chaperone practice: offer rates in intimate-examination records, decline documentation, and the availability failures" ] },
      { role: "Clinicians", duties: [
        "Offer a chaperone for every intimate examination — routinely, without the patient having to ask, and irrespective of the gender pairing (same-gender pairings do not waive the offer)",
        "Record the offer and its outcome every time: offered and accepted (chaperone's name), offered and declined (patient's decision noted), or examination deferred for chaperone availability",
        "Respect their own limits: a clinician may decline to proceed without a chaperone where they judge it unwise, rescheduling rather than risking — the clinician's protection matters too",
        "Explain the examination before and during: what, why, what the patient will feel — narration is consent's companion and the chaperone's context" ] },
      { role: "Chaperones", duties: [
        "Attend within the trained role: present and attentive throughout the intimate phase, positioned to observe the examination, not the ceiling",
        "Speak up in the moment if anything concerns them — the chaperone who saves concerns for later has misunderstood the role",
        "Protect dignity practically: curtains, covers, the patient's exposure minimised to the clinical necessity",
        "Keep absolute confidentiality about everything witnessed" ] },
    ],
    keyPoints: [
      "The offer is universal for intimate examinations: breast, genital and rectal examinations always; other examinations (chest auscultation requiring undressing, groin, procedures in sensitive areas) by the same logic; and any consultation where the patient or clinician wants a third person — with the offer made as routine professional practice ('I'll ask a chaperone to join us — or you're welcome to decline'), not as an awkward exception the anxious must request",
      "Same-gender pairing waives nothing: the offer is made regardless of the clinician-patient gender combination — allegation, misunderstanding and abuse respect no pairing, and the routine offer protects everyone equally",
      "Chaperones are trained, never conscripted: the role requires formal preparation (what intimate examinations involve, where to stand and look, what good practice looks like so deviation is recognisable, how to intervene, how to document) and appropriate checks — the receptionist pulled from the desk untrained is a witness in name only, and family members are companions, not chaperones (welcome additionally, but never substituting)",
      "The chaperone works during the examination: inside the curtain or positioned to observe the examination itself (a chaperone who cannot see cannot witness), attentive throughout the intimate phase, introduced by name and role, and empowered in terms — the training says explicitly that interrupting an examination is within the role",
      "Declines are the patient's right, recorded: a patient may decline the chaperone (their comfort, their choice) and the decline is documented; a clinician uncomfortable proceeding without one may defer and rebook with the reasons explained kindly — both positions are legitimate and the record shows the negotiation",
      "Unavailability defers non-urgent intimacy: where no trained chaperone is available, non-urgent intimate examinations are rebooked (with the clinical urgency honestly weighed — the genuinely urgent examination proceeds with the unavailability documented and the offer of a companion made); chronic unavailability is a staffing finding for governance, not a norm to document around",
      "Remote consultations carry their own rules: intimate images or examinations by video follow the service's remote-consultation protocols (clinical justification, consent explicit, no recording beyond the record's needs, chaperone considerations for both ends), and the policy's default is scepticism — most intimate assessment belongs in the room",
      "Documentation is the policy's spine: every intimate examination record shows the offer, the outcome, the chaperone's identity where present, and the clinical narrative — audited quarterly by sampling intimate-examination codes against chaperone documentation, because the undocumented offer didn't happen for any purpose that later matters",
    ],
    legislation: [
      "Health and Social Care Act 2008 (Regulated Activities) Regulations 2014 — Regulations 10, 12, 13",
      "Mental Capacity Act 2005 (consent interfaces)",
      "Safeguarding Vulnerable Groups Act 2006 (chaperone role checks)",
      "Human Rights Act 1998 (Article 8 — dignity and privacy)",
      "Professional regulator guidance (GMC/NMC intimate examination standards, as interpretive context)",
    ],
    sections: [
      { heading: "The Offer and the Decision", body: "The offer is engineered into the pathway: waiting-room and website visibility (the poster and leaflet in accessible formats stating that chaperones are available and welcome for any examination), the clinical record template prompting at intimate-examination entries, and the professional habit trained until it is unremarkable — the clinician's phrasing offered as script ('for this examination I'll ask one of our trained chaperones to join us — is that okay, or would you rather not?') so the offer lands as routine care rather than suspicion of anyone. The decision tree is honoured in all its branches. Accepted: the chaperone attends (by name, role explained), the examination proceeds, the record captures all of it. Declined by the patient: their choice, gently confirmed ('you're sure? it's no trouble'), documented with the decline, and the clinician then makes their own call — proceed (usually), or defer where their judgement says a witness matters (the history of misunderstanding, the examination's nature, the clinician's own protection), explained without accusation ('I'd rather we did this with a chaperone — can we rebook for Thursday?'). Requested beyond the intimate list: any patient may have a chaperone for anything, and any clinician may ask for one — both requests are honoured without interrogation. The companion distinction is kept clear: friends and family are welcome in the room at the patient's wish, and they are companions — support, comfort, translation of nerves — while the chaperone is the service's trained, impartial witness; the record never conflates the two." },
      { heading: "The Trained Role", body: "Chaperone training makes the role real: who may chaperone (staff who have completed the training, with checks appropriate to a role regularly present at intimate examinations), what the training covers — the examinations themselves (what a competent intimate examination involves, so the chaperone can recognise what doesn't belong), positioning (inside the curtain, sightline to the examination — the chaperone facing away 'for the patient's dignity' has confused the role with the curtain), the patient-facing craft (introduction by name and role, dignity practicalities: covers, exposure minimised and sequenced, warmth in the room in both senses), intervention (the trained sentence for the moment something seems wrong — 'could we pause a moment?' — and the absolute backing the service gives anyone who uses it), and documentation (name recorded in the clinical entry, and the chaperone's own concern route if anything troubled them: straight to the clinical lead or manager, same day, with the safeguarding machinery behind it). The pool is planned: enough trained chaperones across the working pattern (including the late clinic and the branch site) that availability is the norm, refresher touchpoints keep the role warm for those who chaperone rarely, and the role is respected in workload terms — the chaperone summoned is covered, not squeezed." },
      { heading: "Edge Cases and Remote Care", body: "The policy pre-decides the awkward cases. Urgent examination, no chaperone: the clinical need is weighed honestly (the acutely unwell patient is examined — documenting the urgency and unavailability — because a deferred emergency is a harm, not a courtesy), a companion is offered where present, and the event feeds the availability review. The patient who requests a specific gender of clinician or chaperone: accommodated where reasonably possible (rebooking offered), with the service's honest limits explained. The patient with impaired capacity: the consent machinery (pc-003) leads; a chaperone is good practice bordering on essential for intimate care of a person who cannot fully consent, and familiar supporters may serve alongside (never instead of) the trained chaperone. Children and young people: chaperoning intersects with Gillick competence and parental presence per pc-003's framework — the young person's own wishes about who is present are central, and safeguarding awareness runs through every decision. Remote consultations: intimate examination by video is exceptional, clinically justified, explicitly consented, never recorded beyond the record's legitimate needs, conducted with the same offer logic (who is present at each end is established and recorded), and generally converted to in-person care — the policy's stated default. Home visits (for services that make them): the chaperone question is asked at booking for foreseeable intimate examinations, and the dc-001/dc-007 community disciplines carry the conduct frame." },
      { heading: "Documentation, Audit and Culture", body: "The record standard is precise: every intimate examination entry shows the offer made, the outcome (accepted — chaperone named; declined — noted; deferred — reason), and sits within the clinical narrative that pc-004 requires (what was examined, why, findings, the consent conversation per pc-003). The audit closes the loop quarterly: intimate-examination entries sampled against the standard (offer documented? chaperone named? declines captured?), availability failures counted from deferral records, and the findings actioned — low offer-documentation rates trigger template fixes and habit refreshers; availability failures trigger pool expansion. The cultural layer is the policy's foundation: chaperoning is framed in induction and team teaching as mutual protection and ordinary professionalism (not an accusation machine), clinicians who routinely proceed without offering are corrected as a practice-standard issue before it becomes a defence problem, chaperones who raise concerns are backed visibly (the speak-up that turns out benign is thanked, not resented — the alternative culture silences the one that isn't), and any allegation arising from an examination — with or without a chaperone present — runs the safeguarding and HR machinery at full strength, with the chaperone's contemporaneous account bearing the weight the role exists to carry." },
    ],
    appendices: [
      { title: "Chaperone Documentation & Decision Card", type: "template", body:
"OFFER SCRIPT (routine, every intimate examination, any gender pairing): 'For this examination I'll ask one of our trained chaperones to join us — is that okay, or would you rather not?'\nRECORD EVERY TIME: offered [ ] → ACCEPTED (chaperone NAME: ____) / DECLINED (patient's choice noted) / DEFERRED (reason: clinician judgement / no chaperone available — non-urgent rebooked)\nURGENT + NO CHAPERONE: clinical need weighed honestly — examine if deferral harms | document urgency & unavailability | companion offered | feed availability review\nCOMPANION ≠ CHAPERONE: family/friends welcome AS companions | chaperone = trained impartial witness | record keeps them distinct\nCHAPERONE IN THE ROOM: introduced by name & role | inside curtain, SIGHTLINE TO THE EXAMINATION | attentive throughout intimate phase | dignity practicals (covers, minimal sequenced exposure) | INTERVENTION SENTENCE: 'Could we pause a moment?' — always backed\nCONCERN ROUTE: anything troubling → clinical lead/manager SAME DAY → safeguarding machinery behind it\nREMOTE: intimate examination by video = exceptional, justified, explicitly consented, never recorded beyond record needs, both ends' presence established — default is: bring it in person" },
      { title: "Chaperone Pool & Quarterly Audit Sheet", type: "template", body:
"POOL: trained chaperones (name | role | training date | refresher due | checks appropriate to role | sites/patterns covered) — coverage check: late clinics [ ] branch sites [ ] typical intimate-exam sessions [ ]\nTRAINING CONTENT: what competent intimate examinations involve | positioning & sightline | dignity craft | intervention & backing | documentation | concern route\nWORKLOAD RESPECT: summoned chaperone's task covered, not squeezed [ ]\nQUARTERLY AUDIT: intimate-exam entries sampled (n= ____) → offer documented % | chaperone named % | declines captured % | deferrals & reasons | availability failures (count, sessions) → ACTIONS: template fix / habit refresh / pool expansion: ______\nCULTURE CHECK: clinicians proceeding without offer → practice-standard correction | chaperone speak-ups thanked & outcomes fed back | allegations → safeguarding + HR machinery, chaperone account central" },
    ],
  },
  "pc-003": {
    purpose: "This policy makes consent what the law and decency both require: a genuine exchange in which the patient understands what is proposed, what it risks, what the alternatives are — including doing nothing — and freely agrees or declines. The signature is the receipt, not the transaction; the transaction is the conversation, and this policy governs its quality.",
    scope: "Covers consent to examination, treatment and procedures across the service's clinical work: the information standard, proportionate consent forms (implied to written), capacity and the MCA machinery, children and young people, withdrawal of consent, consent in special contexts (photography, teaching, remote care), and documentation. Care-and-support consent in non-clinical settings is cop-001's; this policy holds the clinical examination-and-treatment ground.",
    responsibilities: [
      { role: "Clinical Lead", duties: [
        "Set the consent standards per procedure type: which need written consent, which verbal-recorded, which proceed on properly-informed implied consent",
        "Ensure information materials support the conversations: procedure leaflets accurate and current, accessible formats available, interpreter arrangements real",
        "Audit consent quality: records sampled for the conversation's evidence, not just the form's presence",
        "Keep the team current: the material-risk standard, capacity law, Gillick — trained at induction and refreshed" ] },
      { role: "Clinicians", duties: [
        "Hold the conversation personally where they perform the procedure — consent delegated is consent diluted, and delegation happens only within competence and the service's rules",
        "Disclose to the material-risk standard: what a reasonable patient would want to know, plus what THIS patient clearly cares about — asked, not assumed",
        "Assess capacity decision-by-decision where doubt is genuine, applying the MCA's machinery and presumptions",
        "Record the conversation: risks discussed, questions asked and answered, decision reached — the dialogue, not just the outcome",
        "Honour withdrawal instantly: consent is continuous, and 'stop' means stop, mid-procedure included" ] },
    ],
    keyPoints: [
      "The information standard is material risk, patient-indexed: disclosure covers what a reasonable person in this patient's position would attach significance to AND what this particular patient demonstrably cares about — the driver's hand, the singer's throat, the question they asked twice — established by asking ('what matters most to you here?') rather than reciting a standard list at every patient equally",
      "Alternatives and nothing are part of the disclosure: reasonable alternative treatments (including those the service doesn't offer — the referral option is information the patient owns) and the consequences of declining are explained without salesmanship, because consent to the only option presented isn't choice",
      "Consent is proportionate in form, constant in substance: implied consent carries routine low-risk contact (the offered arm for blood pressure — with the narration that makes implication genuine); verbal consent, recorded in the notes, carries most examinations and minor procedures; written consent carries the service's defined list (invasive procedures, sedation, significant-risk interventions, minor surgery per pc-015's future territory, photography for records or teaching) — and in every form, the conversation's quality is the same requirement",
      "Capacity is presumed, assessed only on genuine doubt, and decision-specific: the MCA's presumption holds; unwise decisions are not incapacity; where doubt is real, the two-stage test is applied to THIS decision with support given first (formats, timing, the person's best hour, communication aids per dc-009's ladder logic); and incapacity for the decision routes to best interests — the least restrictive option, the person's wishes and values central, consultees engaged, and the clinical record carrying the reasoning",
      "Children and young people follow the established framework: 16-17-year-olds are presumed capable of consenting to treatment; under-16s may consent where Gillick-competent for the specific decision (understanding assessed honestly, confidentiality respected within safeguarding limits); parental responsibility fills what competence doesn't; and the young person's confidentiality and safeguarding interfaces (sexual health presentations above all) are handled per the established guidance with the safeguarding machinery engaged on its thresholds, not on reflex",
      "Consent is continuous and withdrawable: agreement at the start does not bind the middle — the patient who says stop is stopped (completing only what abandonment would make dangerous, explained in the moment), the withdrawal recorded without pique, and the conversation reopened when the patient wishes",
      "Pressure invalidates: consent extracted by coercion (the family's, a partner's, even the clinician's impatience) isn't consent — clinicians watch for the patient looking at someone else before answering, offer the private conversation as routine ('I always have a few minutes with the patient alone'), and treat suspected coercion through the safeguarding lens",
      "Special contexts have their own consent lines: photography and recording (specific consent for the image, its purpose and its audience — the wound photo for the record differs from the teaching slide, and each is consented separately per hr-024/hr-025's machinery), students and observers (the patient's explicit agreement before the consultation starts, declinable without consequence), remote consultations (identity, privacy at both ends, and the examination-conversion default per pc-002), and research or innovation (outside this policy — the formal research governance routes)",
    ],
    legislation: [
      "Mental Capacity Act 2005 (capacity, best interests)",
      "Montgomery v Lanarkshire Health Board [2015] (the material-risk standard, as interpretive frame)",
      "Family Law Reform Act 1969 s.8 (16-17 consent); Gillick competence (case law framework)",
      "Health and Social Care Act 2008 (Regulated Activities) Regulations 2014 — Regulation 11",
      "Human Rights Act 1998 (Article 8)",
    ],
    sections: [
      { heading: "The Conversation", body: "The consent conversation has a shape the service trains: what is proposed, in words this patient can use (jargon translated, drawings drawn, the leaflet as supplement never substitute); why — the clinical reasoning shared like the adult exchange it is; the material risks — the common-even-if-minor and the serious-even-if-rare, indexed to this patient's life by asking what matters to them; the alternatives, honestly including watchful waiting and the option other providers offer; the practicalities (what it feels like, how long, recovery, who does it); and the space for questions treated as the conversation's point rather than its overrun. The craft details are taught: checking understanding by teach-back ('just so I know I've explained it properly — what's your understanding of what we're doing?') rather than 'any questions?'; the pause that lets slow deciders decide (consent needn't conclude today — the think-about-it appointment is good practice for consequential choices); interpreters who are professionals, not family members, for consequential consent (the son translating his mother's gynaecology consult serves nobody well); accessible formats per the person's communication needs; and the private-conversation offer as standing routine, which both surfaces coercion and dignifies every patient with a moment that is only theirs." },
      { heading: "Capacity and Best Interests in Clinical Moments", body: "The MCA operates at clinic pace with its principles intact. The presumption holds until genuine doubt: eccentric choices, refusals the clinician disagrees with, and anxiety are not doubt; disorientation, the inability to hold the information long enough to weigh it, and the dementia diagnosis WITH observed decision-difficulty may be. Where doubt is genuine, support comes first — the quieter room, the later hour, the family member the patient wants (as supporter, not decider), the pictures, the second visit — because the Act's own sequence demands maximised capacity before assessed incapacity. The assessment, when needed, is decision-specific and recorded: the two-stage test applied to this examination or treatment, the finding with its reasons, and the route it opens. Best interests, where reached, runs the checklist with clinical honesty: the person's ascertainable wishes and values (past statements, patterns of choice, the family's knowledge of what she would have wanted), participation maximised (assent sought and distress heeded even where consent can't be given — the person who pulls away from the examination is communicating), consultees engaged (family, attorneys and deputies per their authorities, IMCA referral where the Act requires one for serious treatment without family), the least-restrictive and least-invasive option preferred, and the decision recorded with its reasoning. The urgent-necessity gateway is known and bounded: immediately necessary treatment to preserve life or prevent serious deterioration may proceed for the incapacitated patient without the fuller process — documented after, and never stretched to cover the merely convenient." },
      { heading: "Children, Young People and Families", body: "The service's paediatric consent practice follows the established legal architecture with its safeguarding senses on. Sixteen and seventeen: presumed competent to consent to examination and treatment (refusal territory is legally complex and escalated to the clinical lead and, where stakes are high, legal advice — the policy flags rather than resolves it). Under sixteen: Gillick competence assessed for the specific decision — the understanding, intelligence and maturity to grasp what is proposed, its risks and alternatives — generously where the decision is small, rigorously where it is large, recorded either way; the competent child's consent stands, and their confidentiality is respected within the safeguarding limits explained to them honestly at the start ('what you tell me stays between us unless I'm worried someone's hurting you — then I'd have to get help, and I'd tell you first'). Parental responsibility fills the gaps: identified accurately (mothers; fathers per the marriage/registration rules; adopters; special guardians; the local authority under orders — the family's own account verified where decisions are consequential), one holder's consent generally sufficing, disputes between holders escalated rather than refereed at reception. The safeguarding interfaces run throughout: the sexual-health presentation of the young teenager engages the established competence-and-safeguarding balance (treat competently, assess exploitation honestly, follow the guidance's thresholds), the examination a child resists is reconsidered rather than forced (necessity and proportionality, parental presence, the second appointment), and any consent scenario that smells of coercion, FGM risk, or exploitation routes to the safeguarding machinery at once." },
      { heading: "Records, Withdrawal and Audit", body: "Consent documentation matches the consent's weight: implied-consent contacts need no consent entry beyond the clinical record's ordinary narration; verbal consent for examinations and minor procedures is recorded in the entry ('procedure, risks including X and Y discussed, questions re Z answered, consented'); written consent uses the service's forms for the defined list — completed as the conversation's summary, not its replacement, with the risks actually discussed written in (the pre-printed form with no personalisation is weak evidence of a strong conversation, and strong evidence of a weak one); and capacity assessments, best-interests decisions and Gillick findings are recorded with reasoning per their frameworks. Withdrawal is honoured and documented: the stopped procedure, what was completed for safety, the conversation after, and the door left open. Refusals get the same respect as consents: the informed refusal recorded (information given, consequences explained, decision respected), the safety-netting attached (what to watch for, when to return — pc-005's discipline), and the relationship preserved for the patient who may choose differently later. The audit samples quality: quarterly, consent documentation is reviewed against the standards (conversation evidence, material-risk personalisation, capacity reasoning where engaged, the written-consent list honoured), findings feed training, and the deeper question is asked annually with pc-001's honesty — do our patients decide, or do they sign?" },
    ],
    appendices: [
      { title: "Consent Conversation & Documentation Standards", type: "template", body:
"THE CONVERSATION (every consequential consent): WHAT is proposed (their words, drawings, leaflet as supplement) | WHY (reasoning shared) | MATERIAL RISKS (common-even-minor + serious-even-rare + what THIS patient cares about — ASK: 'what matters most to you here?') | ALTERNATIVES incl. watchful waiting & elsewhere-options | PRACTICALITIES (feel, duration, recovery, who) | QUESTIONS (teach-back: 'what's your understanding of what we're doing?') | TIME (think-about-it appointment for big choices)\nCRAFT: professional interpreters for consequential consent (not family) | accessible formats | private-conversation offer as routine | watch for the glance-at-someone-before-answering (coercion → safeguarding lens)\nFORM PROPORTIONATE: implied (routine low-risk, narrated) | verbal-recorded (most exams/minor procedures — risks discussed named in entry) | WRITTEN (service list: invasive/sedation/significant-risk/minor surgery/photography-teaching) — form personalised with risks ACTUALLY discussed\nWITHDRAWAL: 'stop' = stop (complete only what abandonment makes dangerous, explained) | recorded without pique | door open\nREFUSAL: informed, recorded, respected + safety-netted (watch-fors, when to return)" },
      { title: "Capacity, Best Interests & Gillick Quick Reference", type: "template", body:
"PRESUME capacity | unwise ≠ incapable | doubt must be GENUINE (eccentricity/anxiety/disagreement are not doubt)\nSUPPORT FIRST (Act's own sequence): formats, timing, quiet room, their supporter, second visit — THEN assess if doubt remains\nASSESS (decision-specific, 2-stage, recorded with reasons): understand | retain | weigh | communicate — for THIS decision\nBEST INTERESTS (if incapacitous for this decision): wishes/values central (past statements, patterns, family knowledge) | participation & ASSENT sought (pulling away = communication) | consultees (family/LPA/deputy per authority; IMCA for serious treatment without family) | least restrictive & least invasive | reasoning recorded\nURGENT NECESSITY: immediately-necessary treatment may proceed — documented after, never stretched to 'convenient'\n16-17: presumed competent to consent (refusals → clinical lead + legal advice for high stakes)\nUNDER 16: Gillick per decision (understanding/maturity for THIS choice) — competent consent stands | confidentiality within safeguarding limits, explained honestly upfront | parental responsibility verified for consequential decisions | holder disputes escalated\nSAFEGUARDING THREADS: sexual-health presentations per established guidance | resisted examinations reconsidered not forced | coercion/FGM/exploitation → machinery at once" },
    ],
  },
  "pc-004": {
    purpose: "This policy makes the clinical record what the next decision depends on: contemporaneous, attributable, coded truthfully, and complete enough that a stranger-clinician at 2am can care for the patient safely from it. Records fail quietly — the unfiled letter, the miscoded diagnosis, the amendment that erased history — and every failure is a future consultation working from fiction.",
    scope: "Covers clinical record-keeping in primary care and clinic settings: entry standards, clinical coding, amendments and history integrity, incoming correspondence and document workflow, patient online access, summarisation and notes transfers, printing and portable records, and record-quality audit. The information governance architecture (retention, security, SARs, breaches) is the igr suite's; this policy holds the clinical craft.",
    responsibilities: [
      { role: "Clinical Lead / Manager", duties: [
        "Set and train the entry and coding standards, with the record system configured to support them (templates, problem lists, alerts used intelligently)",
        "Own the document workflow: incoming correspondence triaged clinically, actioned trackably, and filed coded — with the red-flag route that never queues",
        "Manage patient online access safely: default access per national arrangements, redaction and safeguarding screening where harm tests are met, and proxy access controlled",
        "Run the record-quality audit cycle and act on it",
        "Govern summarisation, transfers in and out, and the paper-record residue (scanning standards, originals handling)" ] },
      { role: "All Clinical Staff", duties: [
        "Record contemporaneously — in or immediately after the consultation, same session always: the reconstruction at day's end is where detail dies and error breeds",
        "Write for the next clinician and the patient's eyes both: findings, reasoning, plan and safety-netting in professional, respectful language (the record is increasingly read by its subject — write nothing you couldn't stand behind aloud)",
        "Code accurately: problems, diagnoses, allergies (the drug-allergy field sacred above all), procedures and key findings coded so searches, alerts, QOF-type queries and the next clinician's scan all find truth",
        "Amend by the rules: additions and corrections that preserve the original visibly, never deletion or overwriting — the record's history is part of the record",
        "File nothing unread: every result and letter carries a clinician's action decision before it reaches the record's shelf" ] },
    ],
    keyPoints: [
      "Entries carry the clinical minimum, every time: date and attribution (automatic in-system, enforced for imports), the presenting picture, relevant findings positive and negative (the examined-and-normal is recorded — absence of note is not evidence of absence of examination), the working assessment and its reasoning where non-obvious, the plan with drug decisions per prescribing standards, the safety-netting given (specific: what to watch, when to return, where to go — recorded because it was said, and said because it saves lives), and consent/capacity/chaperone entries per their policies",
      "Coding is clinical truth in searchable form: significant diagnoses coded to the right specificity (and re-coded when working diagnoses resolve into confirmed ones), the problem list curated (active problems current, resolved problems marked resolved — the fifteen-year problem list nobody prunes hides the three that matter), allergies and adverse reactions coded in the structured field with the reaction described (free-text allergies don't fire prescribing alerts — the policy names this as the lethal miss it is), and key procedures, values and family history coded where the system provides",
      "History is never erased: errors are corrected by visible addenda ('entered in error — see correction') with the original retained per the system's audit trail; entries are never deleted, backdated or altered to read as if contemporaneous; late entries declare themselves late; and requests to falsify (from anyone, at any seniority) are refused and reported — the record's integrity outranks every embarrassment it preserves",
      "The document workflow has clinical eyes and no black holes: incoming letters, results and reports are triaged on arrival (the trained workflow — administrative filing for the routine-normal per agreed protocols, clinician review for everything else, and the red-flag list that goes to a clinician today), every document carries its action decision (file / act / recall patient / task to owner) before filing, tasks are tracked to completion with aging alerts, and the workflow's queues are monitored daily — the fortnight-old unopened queue is a patient-safety incident in progress",
      "Patient online access is managed as the norm it now is: prospective record access per the national arrangements, with the screening disciplines for the harm exceptions (third-party information, safeguarding risks — the abusive partner with proxy access reading the disclosure is the scenario the screening exists for), redaction applied item-by-item with reasons recorded, proxy access verified and bounded (parents' access curtailed appropriately as children mature toward Gillick territory), and the writing culture adjusted service-wide to the reader (respectful, plain, abbreviations that don't insult)",
      "Transfers preserve the story: records requested promptly on registration and summarised to standard when they arrive (the trained summariser extracting significant history, medications reconciled per dc-012/medication machinery, allergies into the structured field, immunisations and key values coded — with clinician sign-off on the clinical judgements); records sent on departure or deduction complete and prompt; and the interim period (caring for a patient whose notes haven't arrived) managed with explicit provisional-information caution",
      "Paper and portable residues follow the rules: scanning to standard (legible, complete, correctly attached) with originals handled per the retention schedule, printouts minimised and destroyed confidentially after use, records carried for home visits per the community custody rules (dc-007's home records where relevant), and nothing patient-identifiable in cars overnight (dc-014's rule)",
      "Quality is audited, not presumed: the quarterly record audit samples entries against the standards (contemporaneity, attribution, safety-netting presence, coding accuracy, problem-list currency), peer-reviews with calibration (clinicians audit each other's notes to a shared rubric), feeds findings to training and system configuration, and reports to pc-001's governance rhythm — with the standing test being the stranger-clinician question: could someone who has never met this patient care for them safely from this record tonight?",
    ],
    legislation: [
      "Data Protection Act 2018 / UK GDPR (accuracy, integrity, access rights)",
      "Health and Social Care Act 2008 (Regulated Activities) Regulations 2014 — Regulation 17",
      "Access to Health Records Act 1990 (deceased patients)",
      "Records management code of practice for health and care (retention framework, via igr-005)",
      "Computer Misuse Act 1990 (access integrity)",
    ],
    sections: [
      { heading: "The Entry Standard", body: "The consultation record is written to serve three readers: the next clinician (who needs findings, reasoning and plan), the patient (who now reads it, and deserves respect and clarity), and the future reviewer (complaint, claim, SEA — who needs what happened, not what was hoped). The standards are concrete: contemporaneous means in-session or immediately after, same working session absolutely, with late entries flagged as such; attribution is the logged-in author (shared logins are banned; the registrar's entry countersigned per training arrangements); the narrative covers presentation, relevant positives AND negatives (the chest examined and clear is written, because unwritten examinations didn't happen for any later purpose), assessment with reasoning where the path isn't obvious ('viral URTI — no red flags: afebrile, no photophobia...' teaches the record to defend itself), the plan including prescriptions (per the prescribing standards), referrals (pc-005's machinery), investigations ordered, and the safety-netting verbatim-adjacent ('advised return if fever >5 days, immediate attention if rash non-blanching' — specific enough that the advice given can be known later); and the special entries per their policies: consent conversations (pc-003), chaperone documentation (pc-002), capacity reasoning, safeguarding concerns in the appropriate protected formats. Templates and structured data serve the standard without strangling it: the template that prompts completeness is configured; the template that generates identical fictional consultations is retired." },
      { heading: "Coding, Problem Lists and the Structured Truth", body: "Structured data is where the record works when nobody is reading it — firing interaction alerts, populating searches, driving recalls — so its accuracy is a safety system. The disciplines: significant diagnoses coded at the moment of confirmation (and the working-diagnosis code upgraded when the biopsy speaks — the patient coded 'suspected' forever is invisible to the disease register that would have recalled her), coding specificity matched to clinical truth (the code that says more than is known is as false as the one that says less), allergies and adverse drug reactions in the structured allergy field with reaction detail (the policy's loudest rule: free-text-only allergy recording is a named serious incident risk, because the prescribing system cannot read prose), and the high-value structured items maintained — immunisations, key results, family history where systems provide, alerts used sparingly enough to stay meaningful (the record with forty alerts has none). The problem list is curated as the record's front page: active problems current and honest, resolved problems marked resolved with dates, duplicates merged, and the list reviewed opportunistically at consultations and systematically at summarisation — because the problem list is what the stranger-clinician reads first, and its quality is the record's first impression and its fastest safety win." },
      { heading: "Documents, Results and the Workflow's Discipline", body: "Incoming information is a patient-safety pipeline run with pc-005/test-results rigour. Arrival: everything (letters, discharge summaries, results, reports, OOH notifications) enters the workflow same-day, triaged by trained staff against the written protocols — the administrative-filing list (routine-normal items agreed by the clinical lead as safe for direct coding and filing), the clinician-review default for everything else, and the red-flag list (urgent findings, safeguarding correspondence, two-week-wait outcomes, discharge summaries with medication changes) routed to a clinician the same day with confirmation of receipt. Action: every document carries a decision before filing — file, act (the medication change reconciled per dc-012's machinery, the follow-up booked), recall the patient, or task a named owner with a deadline — and the task system's aging is monitored (the unactioned task alert at the stated days, escalation at overdue). Filing: coded attachment to the right patient (the misfiled letter is a two-patient breach — wrong record polluted, right record starved — and the workflow double-checks identity on filing), with scanning standards for paper (complete, legible, oriented, original disposition per retention rules). Absences are covered: the workflow never depends on one person's inbox, clinician absence redirects their queues same-day, and the daily queue check is a named role — because the buried letter is the sector's recurring serious-event, and its cause is always the same: a queue nobody owned." },
      { heading: "Access, Transfers and Audit", body: "Patient online access is administered as a right with safety valves: prospective access per the national defaults, the screening habit at consultation (third-party information kept out of the shareable narrative or redacted with reason; safeguarding-sensitive content handled per the protected mechanisms — the domestic-abuse disclosure that a proxy-holding partner could read is the screening's reason for existing), redaction item-specific and recorded, proxy access verified (identity, authority, the child-access taper as young people approach and reach competence per pc-003's framework), and requests beyond online access (SARs, representatives, deceased-patient requests under the 1990 Act) routed through the igr machinery. Transfers keep the story whole: registrations trigger prompt record requests, arrivals are summarised to the trained standard with clinician oversight (significant history extracted and coded, medications reconciled formally, allergies structured, the problem list built), the not-yet-arrived interim is practised with declared caution (provisional records marked as such), and departures send complete records promptly by the proper routes. The audit cycle closes the policy: quarterly samples against the entry and coding standards with peer calibration, workflow performance metrics (queue ages, task completion, red-flag turnaround) reviewed monthly at pc-001's meeting, patient-access issues (redaction volumes, proxy problems) reviewed for pattern, and the annual whole-system question asked with the stranger-clinician test — pull ten records cold and ask whether tonight's locum could keep these ten patients safe from what's written." },
    ],
    appendices: [
      { title: "Clinical Entry & Coding Standards Card", type: "template", body:
"EVERY ENTRY: contemporaneous (in-session/immediately after; late entries declare themselves) | attributed (own login — shared logins banned) | presentation | relevant positives AND negatives (unwritten = didn't happen) | assessment + reasoning where non-obvious | plan (rx per prescribing standards, referrals per pc-005, investigations) | SAFETY-NETTING specific (what to watch, when to return, where to go) | consent/chaperone/capacity entries per policies\nWRITE FOR THREE READERS: next clinician | the patient (respectful, plain — stand behind it aloud) | future review\nCODING: diagnoses coded at confirmation (upgrade working→confirmed) | specificity = truth (no more, no less) | ALLERGIES: STRUCTURED FIELD ONLY with reaction detail (free-text-only = named serious risk — alerts can't read prose) | problem list curated (active current, resolved marked, duplicates merged)\nAMENDMENTS: visible addenda only ('entered in error — see correction') | never delete/backdate/alter | falsification requests refused & reported\nPORTABLE: printouts minimised & confidentially destroyed | nothing identifiable in cars overnight | scanning to standard, originals per retention" },
      { title: "Document Workflow & Record Audit Sheet", type: "template", body:
"WORKFLOW (no black holes): same-day entry & triage | admin-filing list (clinical-lead-agreed routine-normals) | clinician-review default | RED-FLAG LIST (urgent findings, safeguarding, 2WW outcomes, discharge med changes) → clinician TODAY with receipt confirmed\nEVERY DOCUMENT: decision before filing (file / act / recall / task with owner+deadline) | identity double-check on filing (misfiled = two-patient breach) | task aging alerts at ____ days, escalation at overdue | absence redirects queues same-day | daily queue check (named role: ____)\nONLINE ACCESS: prospective per national defaults | screening at consultation (third-party & safeguarding-sensitive content) | redactions item-specific with reasons | proxy verified + child-access taper toward competence | SARs → igr machinery\nTRANSFERS IN: prompt request | trained summarisation (history coded, MEDICATIONS RECONCILED formally, allergies structured, problem list built) | clinician sign-off | interim = declared caution\nQUARTERLY AUDIT (peer, calibrated): contemporaneity | attribution | safety-netting presence | coding accuracy | problem-list currency || MONTHLY (pc-001): queue ages, task completion, red-flag turnaround || ANNUAL: stranger-clinician test — 10 cold records: safe tonight?" },
    ],
  },
  "pc-005": {
    purpose: "This policy treats every referral as what it is: a patient's diagnosis or treatment travelling through a system with gaps it can fall into. The referral decided but never sent, sent but never received, received but downgraded, booked but never attended — each is a documented route to avoidable harm, and this policy builds the tracking, the safety-netting and the ownership that close the gaps.",
    scope: "Covers outgoing referrals from decision to first specialist contact: urgency grading, referral quality, sending and confirmation, tracking with escalating vigilance by urgency, urgent-suspected-cancer pathways, rejections and bounce-backs, patient communication and safety-netting, DNAs, and pipeline audit. Test-result handling is its sibling policy (pc-007 territory); internal referrals and admissions follow the same logic scaled.",
    responsibilities: [
      { role: "Clinical Lead", duties: [
        "Set the urgency framework and defend it: grading criteria per pathway, and the rule that nobody downgrades a clinician's urgency without a clinician-to-clinician conversation recorded",
        "Own the tracking system: every referral logged with its clock, the vigilance escalating with urgency, and the weekly sweep that catches the silent ones",
        "Review the failures: rejected referrals, lost referrals, breached timescales — as pipeline events with system causes, through pc-001's SEA machinery where harm threatened",
        "Audit the pipeline quarterly end-to-end" ] },
      { role: "Referring Clinicians", duties: [
        "Grade urgency clinically and communicate it unambiguously — the urgent-suspected-cancer referral on the designated pathway, never buried in routine correspondence",
        "Write referrals that work: the question asked plainly, the findings that justify it, the history and medications that the specialist needs, the patient's awareness and expectations recorded",
        "Safety-net the patient at the point of referral: what it's for (honestly — the cancer-exclusion conversation had with the kindness and clarity it deserves), what should happen and by when, and what to do if nothing does",
        "Respond to bounce-backs as re-decisions: the rejected referral is reconsidered, redirected or challenged — never silently filed" ] },
      { role: "Administrative Staff", duties: [
        "Send by the designated routes with confirmation captured, same-day for urgent gradings",
        "Log every referral into the tracker at sending, and work the tracker's alerts on their clocks",
        "Chase per the protocols — receipt, booking, appointment — and escalate to clinicians at the defined triggers, because chasing is a safety function wearing an admin badge" ] },
    ],
    keyPoints: [
      "Urgency is graded by the clinician and travels intact: the framework's categories (emergency — phone-and-send today; urgent including suspected-cancer pathways — designated routes with their timescales; soon — clinically expedited; routine) are assigned at decision, written on the referral unambiguously, and protected — any downgrade (by the receiving service, by internal review, by a booking process) triggers the clinician-to-clinician conversation, recorded, because silent downgrades are how urgent patients wait routinely",
      "The suspected-cancer pathway gets its own rails: designated referral routes used every time (the proforma completed fully — incomplete proformas bounce, and bounced urgent referrals bleed days), the patient told honestly what the referral is for and why speed matters (the euphemism that spares today's discomfort costs next week's DNA), the tracking clock set to the pathway's timescales (receipt within days, first appointment per the national expectation), and any breach chased same-day with escalation through the provider and commissioner routes — the service behaves as if the days matter, because they do",
      "Every referral enters the tracker at sending: patient, date decided, date sent, route, urgency, expected milestones (receipt confirmation, booking, appointment), and status — with the vigilance scaled to urgency: suspected-cancer and urgent referrals checked at short intervals (has it been received? booked? seen?), soon-grade at medium, routine swept weekly-to-fortnightly — and the tracker worked as a standing task, not consulted after complaints",
      "Silence is a finding: no receipt confirmation within the route's normal days means chase today; no booking within the urgency's window means chase and escalate; the patient reporting nothing heard is treated as tracker data, not reassured away — the lost referral announces itself only through the vigilance that goes looking",
      "Referral quality prevents the bounce: the letter carries the question ('please assess for X'), the justifying findings, relevant history and results (attached, not alluded to), current medications and allergies, the patient's context where it changes the plan (capacity, communication needs, transport realities per ch-010 where relevant), and what the patient has been told — because the specialist who must guess re-triages blind, and incomplete referrals return as delay",
      "Rejections and redirections are re-decisions, owned: the bounced referral returns to the referring clinician same-week (workflow-flagged, never just filed), who reconsiders — redirect (the right service identified), resubmit (the missing information supplied), challenge (the rejection that misreads urgency gets the clinician-to-clinician call), or change plan (with the patient told and the record showing the reasoning) — and rejection patterns (the service that bounces everything, the proforma that defeats everyone) feed the quarterly audit",
      "The patient is safety-netted at referral and kept informed through it: at the point of referral — what it's for, what should happen, by when, and the crucial instruction ('if you haven't heard within X weeks, contact us — don't assume it's fine'); through the wait — the service's answers when they call (the tracker makes 'let me check' a real answer), DNA follow-up proportionate to urgency (the missed suspected-cancer appointment is same-day contact and re-referral machinery, not a discharge letter accepted in silence), and the person who can't navigate the system (no phone, no transport, cognitive impairment) flagged at referral with the support planned (dc-015/ch-010 interfaces where the service supports them)",
      "The pipeline is audited end-to-end quarterly: volumes by urgency, time-to-send, receipt and booking intervals, breach counts and chase performance, rejection rates and reasons, DNA rates and follow-up compliance, and a sample walked from decision to outcome — with failures at any stage run through SEA where harm threatened, and the audit's summary question honest: did any patient wait longer than their disease could afford, and would we have known?",
    ],
    legislation: [
      "Health and Social Care Act 2008 (Regulated Activities) Regulations 2014 — Regulations 9, 12, 17",
      "NHS constitution and national cancer waiting time standards (where commissioned, as framework)",
      "Data Protection Act 2018 (referral information sharing)",
      "Mental Capacity Act 2005 (referral decisions and patient involvement)",
      "Equality Act 2010 (access support — the patient who cannot navigate)",
    ],
    sections: [
      { heading: "Deciding and Grading", body: "The referral moment carries decisions the policy structures. The clinical decision: referral question formulated ('what am I asking, of whom?'), the urgency graded against the framework (emergency / urgent incl. suspected-cancer / soon / routine) with the pathway criteria applied honestly in both directions — under-grading buys waiting-list months with a patient's disease; over-grading, done systemically, degrades the pathway for everyone, so the framework's criteria are trained and the edge cases discussed with colleagues rather than inflated by anxiety or deflated by optimism. The patient conversation: the referral explained honestly (what it's for — the suspected-cancer conversation held with clarity and kindness rather than euphemism, because patients who understand urgency attend urgently), expectations set (what should happen and by when), the safety-net instruction given explicitly and recorded ('if you've heard nothing in three weeks, ring us'), and the patient's own barriers surfaced (can they get there? open the letter? use the booking phone line? — with support flagged and planned where the answer is no). The record: pc-004's standards carry the referral decision — the reasoning, the grading, the conversation, the safety-netting — so the pipeline's later questions can be answered from the entry." },
      { heading: "Sending, Tracking and Chasing", body: "The mechanics run on same-day discipline and a tracker with clocks. Sending: urgent and suspected-cancer referrals go the same working day by the designated electronic routes with proformas complete (the completeness check before sending — the bounced proforma costs the days the pathway exists to save); routine referrals go within the stated days; every sending captures its confirmation (the electronic receipt, the fax-era practices retired); and the tracker entry is created at sending as a non-optional step — the referral that bypasses the tracker is invisible until it is a complaint. Tracking: the tracker holds patient, referral, urgency, sent date, and the milestone clocks (receipt expected by X, booking by Y, appointment by Z per urgency), with the working rhythm scaled — urgent/suspected-cancer lines checked at short intervals with same-day chasing of any silence, soon-grade weekly, routine swept fortnightly — and the chase protocols written (who to call, what to ask, when a chase becomes a clinician escalation). Escalation: breached milestones on urgent pathways escalate the same day (clinician informed, provider chased at the right level, the commissioner route used for systemic failures), and the patient is kept truthfully informed through it ('we're chasing this — here's what we know'). The tracker's own health is checked weekly: entries aging without status change, chases overdue, and the named owner's absence covered — because the tracker only catches what somebody works." },
      { heading: "Bounces, DNAs and the Patients Who Fall Through", body: "The pipeline's failure modes each get owned responses. Rejections and redirections: returned referrals route to the referring clinician within the week as flagged workflow (pc-004's document discipline), and the re-decision is recorded — resubmitted with the missing pieces, redirected to the right service, challenged clinician-to-clinician where the rejection misjudges urgency (the conversation documented; the pattern of unjustified bounces escalated through pc-001 to commissioner conversations), or the plan changed with the patient told. DNAs: the response is graded by urgency and framed by curiosity rather than discharge-by-default — the missed suspected-cancer appointment triggers same-day patient contact (is something wrong? transport failed? the letter never came? fear won?), re-referral machinery, and safeguarding thinking where the pattern fits (the adult whose appointments are always missed may be prevented from attending); routine DNAs get proportionate follow-up with the barriers asked about; and the receiving service's discharge-after-DNA letters are reviewed clinically, never auto-filed — the specialist's discharge does not discharge the underlying clinical question, which returns to the referrer to re-own. The navigation-support layer runs beneath: patients flagged at referral as needing support (cognition, communication, transport, no phone) get it planned — accessible-format letters requested, booking done with or for them, escorts arranged where the service's role includes them (ch-010), and the community teams informed where they hold the relationship (dc-015's coordination) — because pipelines built for confident navigators quietly select against the patients who need them most." },
      { heading: "Audit and the Pipeline's Conscience", body: "The quarterly pipeline audit walks the whole system: volumes and urgency mix (with grading sampled against criteria — is 'urgent' being used accurately in both directions?), time-to-send by urgency (the urgent referral that took four days to leave the building is a finding wherever it eventually arrived), receipt-and-booking interval performance with breach counts and chase-response times, rejection rates by destination with reasons (feeding the proforma fixes, the referral-quality teaching, and the provider conversations), DNA rates with follow-up compliance (was the suspected-cancer DNA chased same-day, every time?), and the end-to-end sample — a set of referrals walked from decision to specialist contact with every gap timed. Failures with harm potential run through pc-001's SEA machinery (the lost referral found late is a significant event whether or not harm crystallised — the system that lost it is the finding), themes feed the governance dataset monthly (tracker aging, chase performance, urgent-pathway breaches as standing lines), and the annual review asks the pipeline's conscience-questions: which patient waited longest this year and why; would we have detected their wait without their phone call; and what single change most shortens the distance between a clinician's worry and a specialist's eyes?" },
    ],
    appendices: [
      { title: "Referral Tracker & Chase Protocol", type: "template", body:
"TRACKER ENTRY (created AT SENDING — non-optional): patient | referral & destination | urgency (emergency/URGENT-suspected-cancer/urgent/soon/routine) | decided date | sent date & route | confirmation captured [ ] | MILESTONE CLOCKS: receipt by ____ / booking by ____ / appointment by ____ (per urgency) | status | navigation-support flag [ ] (support planned: ____)\nWORKING RHYTHM: suspected-cancer & urgent — checked every ____ days, SILENCE = CHASE TODAY | soon — weekly | routine — fortnightly sweep | tracker health check weekly (aging entries, overdue chases, owner cover)\nCHASE PROTOCOL: receipt not confirmed in route's normal days → chase today | booking absent within urgency window → chase + clinician informed | urgent-pathway breach → SAME-DAY escalation (clinician → provider at right level → commissioner route for systemic) | patient told truthfully throughout\nPATIENT SAFETY-NET (at referral, recorded): what it's for (honest — incl. the kind, clear suspected-cancer conversation) | what should happen & by when | 'if you've heard nothing in ____ weeks, RING US — don't assume it's fine'" },
      { title: "Bounce, DNA & Pipeline Audit Sheet", type: "template", body:
"REJECTED/REDIRECTED REFERRAL: to referring clinician within the week (flagged workflow, never auto-filed) → RE-DECISION recorded: resubmit (missing pieces) / redirect / CHALLENGE (clinician-to-clinician, documented) / change plan (patient told) | bounce patterns → quarterly audit → proforma fixes / teaching / provider-commissioner conversations\nDNA RESPONSE (curiosity, not discharge-by-default): suspected-cancer DNA → SAME-DAY patient contact (barrier? fear? letter never came?) + re-referral machinery + safeguarding thinking where pattern fits | routine DNA → proportionate follow-up, barriers asked | discharge-after-DNA letters reviewed CLINICALLY — the clinical question returns to the referrer\nQUARTERLY PIPELINE AUDIT: urgency-grading sample vs criteria | time-to-send by urgency | receipt/booking intervals, breaches, chase times | rejection rates & reasons | DNA rates & follow-up compliance | END-TO-END SAMPLE walked with every gap timed | harm-potential failures → SEA\nANNUAL CONSCIENCE: longest wait & why | would we have known without their call? | the single change that most shortens worry-to-specialist distance: ______" },
    ],
  },
};
