// Ziproh Compliance — Deepening Pass Batch 1 (Safeguarding & Regulatory Reporting cluster)
// All content original. Produced for Compliance Team review (tracked-changes pack issued in parallel).

import type { DocumentContent, PolicySection } from "./documents";

// ── saf-001 additions: three new procedure sections + full-bodied appendices ──

export const SAF001_ADDITIONAL_SECTIONS: PolicySection[] = [
  {
    heading: "19. Financial and Material Abuse — Recognition and Response in Depth",
    body: "Financial abuse is among the most common and least reported forms of abuse of adults at risk. It thrives on trust, gratitude and dependence, and its perpetrators are most often people the person knows: family members, friends, neighbours, informal helpers and, occasionally, staff. This section deepens the type-definition in Section 3 into working recognition and response.",
    steps: [
      "RECOGNISE THE PATTERNS — unexplained withdrawals or transfers; possessions or documents going missing; sudden changes to wills, benefits arrangements or property; a person's anxiety about money or reluctance to discuss it; bills unpaid despite adequate income; the visitor whose attendance tracks benefit payment days; a new 'friend', online contact or helper who rapidly becomes involved in the person's finances; carers or family treating the person's income as household money; pressure around gifts, loans or 'looking after' cards and PINs",
      "UNDERSTAND THE SERVICE'S OWN CONTROLS — where the service supports money in any form, the financial support and monies policies (ch-006, dc-011) are the primary prevention layer: transaction records, receipts, dual controls and audit. A concern arising from those records (a discrepancy, a pattern) is a safeguarding matter from the moment it cannot be innocently explained",
      "RESPOND WITHOUT TIPPING OFF — do not confront the suspected person, alert them to scrutiny, or 'investigate' by questioning the person at risk beyond immediate welfare needs. Preserve records (transaction logs, receipts, visitors' book entries, care notes) and report through the Section 5 procedure the same day",
      "REFER AND COORDINATE — financial abuse referrals follow Section 6. Where a crime is likely (theft, fraud, coercion), the police decision belongs in the strategy discussion; the service's records are frequently the core evidence. Where the person holds capacity and declines action, Making Safeguarding Personal applies (Section 7) — their wishes lead, alongside honest information about options and repeated gentle opportunities to change their mind, and a documented risk-management conversation",
      "CLOSE THE PREVENTION LOOP — every substantiated or likely financial abuse event triggers a review of the controls that let it happen: visiting arrangements (ch-008), money-handling arrangements, authority documentation (who holds POA/appointeeship and whether it was verified), and the online dimension (bb-004's scam-protection support where the route was digital",
    ],
    warningBox: "Scams reaching people directly — by phone, post, doorstep or online — are financial abuse by strangers. Treat a person's disclosure of a scam with the same seriousness as any other abuse disclosure: no blame, immediate protective steps (bank contacted, cards secured with the person's involvement), and referral where thresholds are met.",
  },
  {
    heading: "20. Self-Neglect and Hoarding",
    body: "Self-neglect is a formal safeguarding category under the Care Act framework, covering severe neglect of personal hygiene, health or surroundings, and behaviours such as hoarding. It is distinct from a capacitous lifestyle choice, and telling the two apart is a professional judgement this section structures. Self-neglect cases are among the most complex the service will handle, because the 'perpetrator' and the person at risk are the same person, and because rights to autonomy and duties of care pull in opposite directions.",
    steps: [
      "RECOGNISE THE GRADIENT — the home declining against its own baseline (dc-006's environment lens); a previously-kept person or household deteriorating; refusal of essential care, food, medication or services in a pattern that endangers; hoarding that blocks escape routes, prevents safe care delivery, or creates fire and infection risks; untreated wounds or conditions the person will not allow to be addressed",
      "DISTINGUISH CHOICE FROM SYMPTOM — a capacitous adult may live in ways others would not choose (dc-006's lifestyle line). The safeguarding questions are: does the person have capacity for the specific decisions creating the risk; is the refusal genuinely free (or shaped by depression, trauma, control by another, or an unmet treatable need); and is the risk to life or health serious. Capacity is assessed decision-by-decision, with the MCA machinery in Section 11",
      "ENGAGE RELATIONSHIP-FIRST — self-neglect responds to trust, not enforcement. The worker with the best relationship leads contact; goals are harm-reduction (safe escape routes, one safe cooking space, treatment for the worst wound) rather than transformation; and progress is measured in small consents",
      "REFER AT THRESHOLD — where health or safety is seriously compromised and engagement is not holding the risk, a safeguarding referral is made (with the person told, absent the narrow exceptions in Section 6). Serious cases warrant a multi-agency approach — adult social care, housing, fire and rescue (home safety visits and severe-hoarding protocols), environmental health, mental health services and the GP — with this service contributing its unique asset: regular access and the relationship",
      "NEVER FORCE THE FIX — blitz cleans and forced clearances without genuine consent are traumatising, breach the person's rights, and reliably fail (the hoard refills). Coordinated, consent-based, supported change is slower and works. Where the person lacks capacity for the relevant decisions, best-interests machinery governs — least restrictive, wishes central, properly recorded",
    ],
  },
  {
    heading: "21. Escalation and Professional Challenge",
    body: "Safeguarding systems fail most often not because nobody was worried, but because somebody's worry was not carried far enough. This section gives every member of staff, and the Registered Manager, a structured route when they believe a safeguarding response — internal or external — is inadequate.",
    steps: [
      "INTERNAL ESCALATION — any member of staff who believes their concern has not been acted on appropriately re-raises it: first with the safeguarding lead or Registered Manager, then with the provider/nominated individual, and in parallel through the whistleblowing routes (wl-004, hr-007) if they believe the concern is being suppressed. Raising a concern twice is never treated as insubordination; it is treated as the system working",
      "CHALLENGE TO THE LOCAL AUTHORITY — where the service disagrees with a local authority decision (a referral screened out, an enquiry closed while risk appears live), the service uses the local safeguarding partnership's professional-challenge/escalation procedure: the disagreement is put in writing, with evidence, to the named decision-maker and escalated through the published route where unresolved. The challenge, its response and the service's continuing risk-management are all recorded",
      "PROTECT MEANWHILE — escalation never suspends protection. While a challenge runs, the service continues every protective measure within its own control: increased monitoring, allocation changes, visiting arrangements per ch-008, recording at evidential standard",
      "GO WIDER WHERE NEEDED — the CQC can be told of safeguarding concerns at any time by anyone (staff included, with whistleblowing protection); the police remain available where crime is in question; and in an emergency, 999 outranks every procedure in this document",
      "LEARN FROM EVERY ESCALATION — cases requiring professional challenge feed the Section 16 quality-assurance review: what did the first response miss, and what does that teach the service's own thresholds",
    ],
  },
];

export const SAF001_FULL_APPENDICES = [
  { title: "Appendix A — Safeguarding Concern Record Form", type: "form", body:
"Complete within the same shift the concern arises. Facts, not opinions. The person's own words verbatim where a disclosure was made.\n\nDate & time of record: ______  Date/time/place of concern or disclosure: ______\nRecorded by (name, role, signature): ______\nPerson at risk: name ______  DOB/ID ______  Where they are now ______  Are they safe right now? YES / NO (if NO — action taken FIRST, then this form)\nWHAT HAPPENED / WHAT WAS OBSERVED (facts only — what you saw, heard, smelled; injuries described by size, site, colour — use the body map at Appendix D): ______\nDISCLOSURE (person's OWN WORDS, verbatim, with your questions shown — record what you asked and what they answered; do NOT probe beyond immediate safety): ______\nWho else was present or may have witnessed: ______\nAlleged source of harm (if indicated — name/relationship; do NOT alert or confront them): ______\nIMMEDIATE ACTIONS TAKEN: medical attention [ ] scene/evidence preserved [ ] person made safe (how) ______ others at risk considered [ ]\nREPORTED TO: safeguarding lead/manager (name, time) ______  Out of hours: on-call (name, time) ______\nPerson's wishes (what do THEY want to happen — Making Safeguarding Personal): ______\nNext steps agreed: referral to LA [ ] police [ ] CQC notification [ ] family informed (unless implicated/person objects) [ ] body map completed [ ]\nThis form is confidential and stored per the safeguarding records procedure (Section 14)." },
  { title: "Appendix B — Manager's Referral & Notification Checklist", type: "checklist", body:
"Run this checklist for every concern reaching the safeguarding lead/Registered Manager. Times matter — record them.\n\nWITHIN THE HOUR: [ ] concern record reviewed (Appendix A) [ ] immediate safety confirmed — person, others at risk, scene [ ] medical needs met (999/GP/111 as indicated) [ ] evidence preserved (nothing cleaned, moved, laundered where crime possible) [ ] alleged staff member? → saf-021 allegations procedure runs IN PARALLEL (duties adjusted pending)\nSAME DAY: [ ] LA safeguarding referral made where threshold met (three-stage test: care & support needs / experiencing or at risk of abuse or neglect / unable to protect themselves) — LA contact: ______ ref given: ______ [ ] person told a referral is being made (unless telling them increases risk — reason recorded) [ ] person's wishes recorded and communicated with the referral [ ] police informed where crime apparent — ref: ______ [ ] CQC notification submitted where required (abuse or allegation of abuse is notifiable) — ref: ______\nWITHIN 72 HOURS: [ ] family/representative informed (unless implicated or person with capacity objects) [ ] care plan interim measures recorded [ ] staff involved supported and reminded of confidentiality [ ] records completed to evidential standard\nONGOING: [ ] LA enquiry cooperated with — information shared per Section 12 [ ] internal review scheduled [ ] outcome recorded and fed to Section 16 quality assurance [ ] escalation route used if LA response inadequate (Section 21)" },
  { title: "Appendix C — Local Contacts Sheet (complete for your service)", type: "template", body:
"Keep current and displayed where staff can use it in a hurry. Review quarterly (Section 16).\n\nLocal Authority adult safeguarding team: ______  (out of hours emergency duty team: ______)\nOnline referral portal (if used): ______\nPolice: 999 emergency / 101 non-emergency  Local PPU/adult abuse investigation contact if known: ______\nCQC notifications: online portal / 03000 616161\nLocal Safeguarding Adults Board escalation/professional-challenge procedure location: ______\nAdvocacy service (independent advocacy under the Care Act): ______\nIMCA service: ______\nGP surgeries most used by people we support: ______\nDistrict nursing hub: ______\nOur safeguarding lead: ______  Deputy: ______  Provider/nominated individual: ______\nWhistleblowing external routes: CQC 03000 616161 | charity advice line (see wl-004/hr-007): ______" },
  { title: "Appendix D — Body Map and Injury Recording Guidance", type: "template", body:
"Use whenever a physical sign is observed. Complete at the time of observation; never from memory the next day.\n\nTHE STANDARD: record what you SEE, not what you conclude. 'Purple-red bruise, approx 3cm x 2cm, outer left forearm' — not 'grab mark'. Conclusions belong to the enquiry, not the first record.\nFOR EACH MARK: site (use the body map diagrams — anterior/posterior/lateral views); size (measure, do not estimate where a ruler is available); colour; type (bruise, laceration, abrasion, burn, pressure damage, swelling); the person's account in their words, if offered ('I fell', said quietly, looking away — record demeanour factually); your observations of pain, movement, distress.\nPATTERNS THAT RAISE CONCERN (record and report, do not diagnose): marks in the shape of objects or grips; symmetrical bruising (both upper arms); injuries in protected sites (inner thighs, soles, genitals, torso under clothing); multiple injuries of different ages; injuries inconsistent with the account or the person's mobility; repeated 'falls' without witnessed falls.\nPHOTOGRAPHY: only per the service's consent and clinical-image rules (work device, consent or best-interests basis, direct to record). Never on personal devices (hr-025).\nMEDICAL ATTENTION: any unexplained or concerning injury gets clinical review the same day — the record supports care first, evidence second.\nThe completed body map attaches to the Appendix A concern record." },
  { title: "Appendix E — Types of Abuse: Staff Quick Reference Card", type: "template", body:
"Display in staff areas. The ten Care Act categories with the signs staff most often see. ANY concern → Appendix A form + report same shift. You do not need to be sure. You need to report.\n\nPHYSICAL — unexplained injuries, patterned marks, over-medication, rough handling witnessed | DOMESTIC — abuse by partners/family incl. coercive control; the person who changes when a particular relative is present | SEXUAL — disclosures, fear of specific people, unexplained genital/breast/inner-thigh injuries, sexualised distress (see bb-005) | PSYCHOLOGICAL — belittling, threats, isolation from contact, the person who seems afraid of a carer | FINANCIAL — missing money/possessions, benefit-day visitors, pressured gifts/loans/wills, scams (Section 19) | MODERN SLAVERY — controlled movements/documents/wages, fear disproportionate to circumstances (Section 10) | DISCRIMINATORY — abuse targeting protected characteristics; harassment, slurs, degrading treatment | ORGANISATIONAL — poor care as a pattern: rigid routines for staff convenience, dignity failures, closed-culture signs (Section 18) | NEGLECT & ACTS OF OMISSION — pressure damage, malnutrition/dehydration, missed medication/care, ignored call bells | SELF-NEGLECT — severe decline in hygiene, health or surroundings; hoarding; refusals that endanger (Section 20)\nIN AN EMERGENCY: 999 FIRST. Then the manager. Then the form." },
];

// ── hr-007 full rebuild (was 463 words) ──
export const HR007_CONTENT_V2: DocumentContent = {
  title: "Whistleblowing and Speaking Up Policy",
  policyId: "HR-007",
  version: "2.0",
  reviewedBy: "Registered Manager / Freedom to Speak Up Lead",
  purpose: "This policy exists so that any worker who sees something wrong — unsafe care, abuse, dishonesty, cover-up, or risk to people we support, colleagues or the public — can raise it quickly, safely and effectively, and so the service hears about its problems from its own people first. It sits alongside wl-004 (the provider-level raising-concerns framework) and bb-015 (the beyond-statutory protection standard), and gives the day-to-day route map every worker should know by heart.",
  scope: "Applies to every person working in or with the service: employees, bank and agency workers, students, volunteers and contractors. It covers concerns about wrongdoing and risk — not personal employment grievances, which follow the Grievance Policy (hr-005/wl-011), though a concern may contain both, and staff are never penalised for choosing the 'wrong' route in good faith.",
  responsibilities: [
    { role: "Registered Manager / Freedom to Speak Up Lead", duties: [
      "Receive concerns with visible gratitude — the first response ('thank you, tell me more') is trained behaviour, not temperament",
      "Act on every concern: assess immediately for live risk, investigate proportionately, and feed back the outcome to the discloser every time, even when the finding is 'looked into, not substantiated, here is why'",
      "Protect the discloser: confidentiality by architecture (who-knows lists minimal), the detriment monitoring bb-015 specifies, and immediate intervention where any retaliation appears",
      "Publish and maintain the routes map (below) so no one must complain to the person they are worried about" ] },
    { role: "All Workers", duties: [
      "Raise concerns as soon as they arise — early concerns are small; suppressed ones grow",
      "Use any route on the map; going straight to external routes is protected identically",
      "Never victimise a colleague who speaks up — doing so is gross-misconduct territory (hr-020)",
      "Distinguish honestly between 'I believe something is wrong' (this policy — good faith is enough, proof is not required) and knowingly false allegations (a conduct matter, and rare)" ] },
  ],
  keyPoints: [
    "You do not need proof — reasonable belief in good faith is the whole test; investigation is the service's job, not yours",
    "You will not suffer for speaking up: the law protects qualifying disclosures, and this service protects further than the law (bb-015) — including for volunteers and others the statute misses",
    "You choose the route: line manager → any senior manager → the speak-up lead → the provider — or straight to external routes at any point",
    "External routes are always open and equally protected: CQC 03000 616161 (care concerns); the whistleblowing charity Protect for confidential advice (020 3117 2520); your professional body; the local authority safeguarding team for abuse concerns (saf-001 runs in parallel)",
    "Concerns about the most senior people go outside the line: to the provider directly, or externally — the map exists precisely so seniority cannot block a concern",
    "Anonymous concerns are accepted and investigated to the evidence's limit — with the honest caveat that anonymity limits feedback and individual protection; confidential-but-named is the strong default",
    "You will always hear back: acknowledgement, then outcome — the loop closes on every concern",
    "Safeguarding emergencies outrank process: a person in danger now means 999 and the safeguarding procedure (saf-001) immediately; this policy's routes carry the wider concern afterwards",
  ],
  legislation: [
    "Public Interest Disclosure Act 1998 / Employment Rights Act 1996 (protected disclosures)",
    "Health and Social Care Act 2008 (Regulated Activities) Regulations 2014 — Regulations 12, 13, 17, 20",
    "Care Act 2014 (safeguarding interfaces)",
    "Employment Rights Act 1996 s.47B (detriment protection)",
    "Regulator whistleblowing frameworks (CQC as prescribed person)",
  ],
  sections: [
    { title: "What to raise under this policy", body: "Raise anything you reasonably believe indicates: unsafe or poor care (understaffing creating danger, medication practice failures, neglect); abuse of any kind (raise via saf-001's procedure — this policy protects you while that one protects the person); dishonesty affecting care or funders (falsified records per pc-004's integrity rules, phantom visits per dc-004, fraud per pc-010); criminal offences; health and safety dangers to anyone; environmental damage; regulatory breaches; and the covering-up of any of these. If you are unsure whether something 'counts' — raise it. The policy's design assumption is that uncertain people stay silent, and silence is the only wrong choice.\n\nNot for this policy: personal employment disputes (your rota, your pay, your treatment as an individual) — those go to the Grievance Policy, where they get their own fair machinery. Where a situation is both (you are being mistreated AND care is unsafe), raise both, through either door; nobody will penalise the choice of door." },
    { title: "The routes map", body: "INTERNAL LADDER: 1) Your line manager — the default first step, skipped without explanation whenever the concern touches them. 2) Any senior manager or the Registered Manager. 3) The speak-up lead: ______ (name displayed on the staff notice board and in induction). 4) The provider/nominated individual: ______.\n\nEXTERNAL — equally protected, usable at ANY point: CQC (prescribed regulator for care concerns): 03000 616161 or online; Protect (independent whistleblowing charity, confidential legal-adjacent advice BEFORE you act — recommended): 020 3117 2520; the local authority safeguarding team (for abuse — with saf-001 running); your professional body (NMC and others for registrants); HSE for serious workplace-safety matters; police where crime is live.\n\nANONYMOUS: written concerns without a name are accepted through any route and investigated as far as the information allows. If you want protection and feedback, confidential-but-named is stronger: your identity travels only as far as investigation genuinely requires, and never to the subject of the concern without your knowledge (bb-015's architecture)." },
    { title: "What happens when you raise a concern", body: "Within one working day: acknowledgement (same-shift for anything with live risk — and immediate protective action where people are in danger). Assessment: the receiving manager checks first for current risk to anyone, then routes the concern — safeguarding machinery (saf-001), incident machinery, clinical review, HR processes or investigation as fits. Investigation: proportionate to the concern, by someone without conflicts, with the just-culture disciplines of pc-001 (systems examined before individuals; your motive irrelevant to whether the concern is true). Feedback: you are told the outcome and, within confidentiality limits, what changed — always. Protection: from the moment you raise a concern, bb-015's machinery applies: confidentiality architecture, twelve months of active detriment monitoring, and senior review of any process that touches you meanwhile.\n\nIf you believe the response is inadequate: escalate up the internal ladder, or go external — both protected. The service's own escalation-and-challenge culture (saf-001 Section 21) applies to speaking up about speaking up." },
    { title: "Common situations and what to do", body: "THE CONCERN ABOUT YOUR OWN MANAGER: skip them without explanation — go to any senior manager, the speak-up lead, the provider, or straight to the CQC. The ladder has no compulsory rungs.\n\nYOU RAISED IT VERBALLY AND NOTHING HAPPENED: raise it again, in writing this time (an email to the speak-up lead creates the record), or move up the ladder or outside. Re-raising is protected exactly as the first raising was, and a concern that needed raising twice is logged as a response failure, not a nuisance.\n\nYOU'RE NOT SURE IT'S 'SERIOUS ENOUGH': the threshold for raising is lower than you think — the near-miss, the shortcut becoming normal, the colleague who seems out of their depth. Small concerns are cheap to check and expensive to ignore. Raise it.\n\nYOU SAW IT AT ANOTHER PROVIDER (a hospital, another agency sharing the person's care): still raise it here — the service carries it through professional-to-professional routes (dc-015) and safeguarding channels; you are protected for disclosures about other organisations' practice too.\n\nA COLLEAGUE TELLS YOU THEY'RE AFRAID TO RAISE SOMETHING: you may raise it for them (their name stays out unless they agree), or support them to the speak-up lead. Witness-supporters are protected identically.\n\nYOU'RE AGENCY, BANK, A STUDENT OR A VOLUNTEER: every route in this policy is yours, with the same protections — this service's standard (bb-015) covers people the statute misses.\n\nYOU WANT ADVICE BEFORE DECIDING ANYTHING: call Protect (020 3117 2520) — independent, confidential, free, and calling them is itself protected. Nobody here will ever ask whether you did." },
    { title: "Culture, training and assurance", body: "Speaking up is inducted (this map, the assurances, the routes card), refreshed annually, and normalised at team meetings (the quarterly 'what nearly went wrong' conversation per pc-001's learning culture). Managers are trained in the receiving craft — gratitude first, defensiveness unlearned. The data is reviewed quarterly through governance with bb-015's silence-reading: volumes, routes, themes, outcomes, time-to-feedback, and the units whose silence sits alongside stress markers. The annual staff survey asks the two questions that audit this policy better than any register: 'Would you raise a concern here?' and 'What happened to the last person who did?' — and the answers go to the provider unfiltered." },
  ],
  appendices: [
    { title: "Speak-Up Routes Card (display + induction)", type: "template", body:
"WORRIED ABOUT SOMETHING? You need reasonable belief, not proof. Raising it is always right.\nDANGER NOW → 999, then the manager (safeguarding: saf-001 procedure).\nINTERNAL (any order that feels safe): line manager → any senior → speak-up lead ______ → provider ______\nEXTERNAL (equally protected, any time): CQC 03000 616161 | Protect (confidential advice first — recommended) 020 3117 2520 | LA safeguarding team ______ | your professional body | HSE | police\nANONYMOUS accepted through every route. Confidential-but-named = stronger protection + feedback.\nOUR PROMISES: thank you, not trouble | acknowledged within 1 working day | investigated fairly | outcome fed back ALWAYS | no detriment — actively monitored for 12 months (bb-015) | victimising a discloser = gross misconduct (hr-020)" },
  ],
  monitoring: "Speak-up activity reported quarterly to governance (volumes, routes, themes, outcomes, time-to-feedback, silence-reading per bb-015); annual survey questions reviewed by the provider; policy reviewed annually and after any significant disclosure event.",
  relatedDocuments: ["wl-004 — Whistleblowing (Raising Concerns) Policy", "bb-015 — Whistleblower Protection Beyond Statutory Policy", "saf-001 — Safeguarding Adults at Risk Policy", "hr-020 — Dignity at Work Policy", "pc-001 — Clinical Governance Policy (just culture)", "hr-005 — Grievance Policy and Procedure"],
};

// ── gov-005 full rebuild (was 782 words) ──
export const GOV005_CONTENT_V2: DocumentContent = {
  title: "CQC Notifications Policy and Procedure",
  policyId: "GOV-005",
  version: "2.0",
  reviewedBy: "Registered Manager / Nominated Individual",
  purpose: "This policy ensures every event the regulator must be told about is notified accurately, completely and on time — because notification is a statutory duty whose breach is itself an offence, because late or missing notifications are among the commonest findings against otherwise good services, and because the discipline of notifying well is inseparable from the discipline of responding well: a service that knows exactly what to tell the CQC by when is a service that has already gripped the event itself.",
  scope: "Applies to all notifiable events across the service's regulated activities, to the Registered Manager and any person acting in that capacity, and to the deputising arrangements that keep the duty alive during absence. Staff at every level contribute by reporting events internally at once — the notification clock runs from the event, not from the day the manager hears of it.",
  responsibilities: [
    { role: "Registered Manager", duties: [
      "Know the notifiable list cold and keep it displayed (Appendix A) — hesitation about whether something is notifiable is resolved by the guidance, the provider, or by notifying: over-notification is a conversation; under-notification is a breach",
      "Submit notifications through the CQC provider portal (or the prescribed forms where applicable) within the required timescales, with the deputising arrangement documented for absence",
      "Keep the notifications log (Appendix B): every notifiable event, the decision, the submission reference, and the cross-references to the incident, safeguarding and duty-of-candour machinery running in parallel",
      "Review the log monthly and reconcile against incident and safeguarding records — the audit that finds the event nobody notified" ] },
    { role: "All Staff", duties: [
      "Report events internally the same shift — deaths, serious injuries, abuse or allegations, police incidents, absconding, anything that feels regulator-serious — so the notification decision can be made in time",
      "Provide accurate factual accounts for notifications: what happened, when, who was involved, what was done",
      "Never assume someone else has reported — duplicate internal reports are free; a missed notification is not" ] },
    { role: "Provider / Nominated Individual", duties: [
      "Hold the provider-level notification duties (changes to the service, financial position where applicable) and support the manager's judgement calls",
      "Treat notification performance as governance data: timeliness and completeness reviewed at provider level" ] },
  ],
  keyPoints: [
    "The core notifiable events (adult social care) — deaths of people using the service (including where the death occurred elsewhere but care may be relevant); serious injuries (fractures other than as expected from a pre-existing condition, injuries requiring hospital treatment or causing lasting harm, pressure damage at the serious grades per current guidance); abuse or allegations of abuse (including allegations against staff and incidents between people using the service); events reported to or investigated by the police; deprivation of liberty — applications and their outcomes; unauthorised absence of a person detained or subject to DoLS where applicable; and events that stop or threaten the safe running of the service (loss of premises, utilities failure with care impact, staffing collapse)",
    "Timescales are short and absolute: 'without delay' is the governing standard for most events — in this service that means the same working day wherever possible and never later than the timescale the current guidance sets for the event type; the notification clock is managed like a clinical deadline, with the event escalated internally the same shift",
    "Notification never waits for the full picture: notify with the facts held, marked as initial where the investigation is live, and update the CQC as facts develop — the regulator expects early honesty over late completeness",
    "Parallel machinery runs simultaneously, not sequentially: the same event may require the safeguarding referral (saf-001/Appendix B checklist), the duty-of-candour conversation (gov-001), RIDDOR (saf-015), the coroner (via the GP/police for relevant deaths) and the commissioner's contract notification — the notifications log cross-references all of them so nothing waits on anything else",
    "Deaths have their own discipline: expected deaths in the service are notifiable per the current framework; unexpected deaths engage police/coroner processes the service supports without disturbing the scene; and in every case the family's needs and the staff debrief (hr-021) run alongside the paperwork, not after it",
    "Allegations against staff are notifiable as abuse allegations — the saf-021 machinery and the CQC notification run together, and the notification is not delayed pending the internal investigation's outcome",
    "Provider-level notifications are diarised, not remembered: changes requiring notification or application (manager changes, provider details, statement of purpose changes per gov-006) carry their own routes and timescales, tracked on the compliance calendar",
    "The log is the audit trail: every entry shows event → decision (notifiable or not, with reasoning for the borderline calls) → submission (date, time, portal reference) → parallel actions → updates sent — and the monthly reconciliation against incident and safeguarding records proves the net has no holes",
  ],
  legislation: [
    "Care Quality Commission (Registration) Regulations 2009 — Regulations 14-18 (notifications)",
    "Health and Social Care Act 2008 (Regulated Activities) Regulations 2014 — Regulations 12, 13, 17, 20",
    "Mental Capacity Act 2005 / DoLS (deprivation notifications)",
    "RIDDOR 2013 (parallel reporting duties)",
    "Coroners and Justice Act 2009 (death reporting interfaces)",
  ],
  sections: [
    { title: "The notification decision", body: "Every internally-reported event passes through the same three questions, the same day: Is it on the notifiable list (Appendix A)? If clearly yes — notify now. If borderline — check the current CQC guidance for the event type, consult the provider where time allows, and resolve doubt toward notifying: the service's standing posture is that over-notification costs a few minutes and under-notification is a regulatory breach with a finding attached. Is anything else triggered? The decision matrix (Appendix B) walks the parallel duties: safeguarding referral, duty of candour, RIDDOR, coroner, commissioner, police. Who does it? The Registered Manager, or the named deputy during absence — the deputising arrangement is written, the deputy is trained on the portal, and 'the manager was on leave' has never excused a late notification anywhere.\n\nThe borderline calls that recur are pre-decided in this policy's local annex as they arise: which pressure damage grades the service notifies (per current guidance), which medication errors reach the threshold (harm or hospital involvement generally does), which resident-to-resident incidents qualify (allegations of abuse do), and which service disruptions count (the test: could this stop the safe running of the service?). Each resolved borderline becomes a precedent line in the annex, so the same judgement is never made twice from scratch." },
    { title: "Submitting well", body: "Notifications go through the CQC provider portal as the default route, by the named account holders, with the submission reference captured into the log immediately — an unreferenced notification is unprovable. The content standard: facts (what, when, where, who — anonymised per the portal's conventions but identifiable internally), the immediate actions taken (safety, medical, safeguarding), the parallel referrals made, and what happens next. Where the picture is incomplete, the notification says so plainly and commits to an update — and the update is diarised and sent, because the open-ended 'investigation ongoing' that never concludes is its own adverse finding. Tone matters: notifications are factual and unspun; the regulator reads hundreds and recognises defensiveness instantly. The service's credibility asset is a notification history that reads like a service that grips events — fast, honest, complete." },
    { title: "The log and the monthly reconciliation", body: "The notifications log is the policy's memory: every event considered (including the borderline 'decided not notifiable' entries with their reasoning — these prove judgement rather than ignorance if questioned later), every submission with its reference and timestamps (event time → internal report time → notification time: the intervals are the performance data), the parallel-machinery cross-references, and the update trail. Monthly, the manager reconciles the log against the incident system, safeguarding records and deaths register: every incident-system entry that meets a notifiable description must appear in the log as notified or reasoned-out — any orphan is investigated immediately (and where a notification was genuinely missed, it is submitted late with an honest covering explanation: late is a breach, but concealed-late is far worse). Quarterly, notification performance goes to governance (pc-001's rhythm): volumes by type, timeliness intervals, reconciliation findings, and the borderline-annex additions — with the annual question asked plainly: would an inspector reading our notification history conclude we grip events, and does the reconciliation prove no event escaped?" },
  ],
  appendices: [
    { title: "Appendix A — Notifiable Events Quick Reference (display by the manager's desk)", type: "template", body:
"NOTIFY WITHOUT DELAY (same working day wherever possible):\nDEATH of any person using the service (incl. deaths elsewhere where our care may be relevant) — plus coroner/police routes where unexpected\nSERIOUS INJURY — fractures (other than expected pathological), hospital-treatment injuries, lasting-harm injuries, serious pressure damage per current guidance\nABUSE OR ALLEGATION OF ABUSE — any category (saf-001 Appendix E), incl. allegations against staff (saf-021 runs in parallel) and resident-to-resident incidents\nPOLICE INVOLVEMENT — events reported to or investigated by police\nDoLS — applications made and their outcomes; unauthorised absence of a person subject to authorisation\nSERVICE DISRUPTION — anything that stops or threatens safe running (premises, utilities with care impact, staffing collapse)\nDOUBT? → current CQC guidance → provider → RESOLVE TOWARD NOTIFYING.\nPARALLEL DUTIES CHECK (every event): safeguarding referral [ ] duty of candour [ ] RIDDOR [ ] coroner [ ] commissioner [ ] police [ ]\nPROVIDER-LEVEL (diarised): manager/provider detail changes | statement of purpose changes (gov-006) | other registration changes" },
    { title: "Appendix B — Notifications Log (per event)", type: "form", body:
"Event ref: ____  Event date/time: ____  Internally reported (date/time): ____\nWhat happened (facts): ______\nNOTIFIABLE? YES / NO — reasoning (esp. for borderline NO): ______  (borderline resolved → add precedent line to local annex [ ])\nSubmitted: date/time ____ | portal reference ____ | by (manager/named deputy) ____\nInterval event→notification: ____ (performance data)\nPARALLEL ACTIONS: safeguarding referral (ref) | DoC conversation (gov-001 ref) | RIDDOR (ref) | coroner via | commissioner told | police (ref)\nMarked initial? [ ] Update diarised (date) [ ] Update sent (date/ref) [ ]\nMONTHLY RECONCILIATION: incident system [ ] safeguarding records [ ] deaths register [ ] — orphans found: ______ (missed notification → submit late with honest covering note; never conceal)\n→ Quarterly to governance: volumes | timeliness intervals | reconciliation findings | annex additions" },
  ],
  monitoring: "Notifications log reconciled monthly against incident, safeguarding and deaths records; performance (timeliness intervals, reconciliation findings) reported quarterly through clinical/service governance; policy and local annex reviewed annually and on any change to CQC notification requirements.",
  relatedDocuments: ["saf-001 — Safeguarding Adults at Risk Policy", "saf-021 — Safeguarding Allegations Against Staff Policy", "gov-001 — Duty of Candour Policy", "saf-015 — Accident and Incident Reporting Policy", "gov-006 — Statement of Purpose Policy", "wl-020 — CQC Notifications (legacy reference — see this policy)"],
};
