// Ziproh Compliance — 2026 Expansion Set G (Beyond the Benchmark: Differentiator Topics)
// All content original. Written tailoring-ready (generic base terms adapt per care setting).

import type { Document, DocumentContent } from "./documents";

export const EXPANSION_2026G_DOCS: Document[] = [
  {
    id: "bb-001",
    title: "Tech-Enabled Care & Remote Monitoring Policy",
    category: "Effective", subcategory: "Digital & Innovation", keyQuestion: "Effective",
    serviceTypes: ["All"], regulators: ["CQC", "CI", "CIW", "RQIA"],
    version: "1.0", lastUpdated: "2026-07-15", status: "updated", readTime: 13,
    tags: ["telecare", "remote monitoring", "sensors", "falls detection", "alert response", "consent", "privacy"],
    summary: "Technology that watches over people without watching them: sensors and telecare chosen for the person's actual risks, consent and privacy worked through honestly (including for people who cannot consent), alert response that is staffed and timed rather than assumed, the data read for the person's benefit, and the standing rule that technology supplements human care and never quietly replaces it.",
  },
  {
    id: "bb-002",
    title: "AI & Digital Tools in Care Records Policy",
    category: "Well-Led", subcategory: "Digital & Innovation", keyQuestion: "Well-Led",
    serviceTypes: ["All"], regulators: ["CQC", "CI", "CIW", "RQIA"],
    version: "1.0", lastUpdated: "2026-07-15", status: "updated", readTime: 12,
    tags: ["artificial intelligence", "digital care records", "clinical judgement", "transparency", "data protection", "tool approval"],
    summary: "AI and digital tools adopted with eyes open: an approval gate before any tool touches care or records, the human-judgement rule (AI drafts and suggests — accountable humans decide and sign), transparency with the people whose data feeds the tools, the shadow-IT reality confronted (the worker pasting care notes into a free chatbot is a data breach in progress), and review that catches the tool drifting from helpful to trusted-beyond-its-competence.",
  },
  {
    id: "bb-003",
    title: "Cyber Incident Response Policy (Care Settings)",
    category: "Well-Led", subcategory: "Digital & Innovation", keyQuestion: "Well-Led",
    serviceTypes: ["All"], regulators: ["CQC", "CI", "CIW", "RQIA"],
    version: "1.0", lastUpdated: "2026-07-15", status: "updated", readTime: 12,
    tags: ["cyber incident", "ransomware", "phishing", "business continuity", "paper fallback", "ICO notification"],
    summary: "Cyber response built for services where the records ARE the care: the first-hour drill when ransomware or compromise strikes, care continuity on paper fallbacks that are printed and practised before they're needed, the notification map (ICO, regulator, commissioners, the people whose data left), recovery without paying trust away, and the prevention basics — phishing habits, patching, backups tested by restoring — that make most incidents somebody else's story.",
  },
  {
    id: "bb-004",
    title: "Digital Inclusion Policy (People We Support)",
    category: "Caring", subcategory: "Digital & Innovation", keyQuestion: "Caring",
    serviceTypes: ["All"], regulators: ["CQC", "CI", "CIW", "RQIA"],
    version: "1.0", lastUpdated: "2026-07-15", status: "updated", readTime: 11,
    tags: ["digital inclusion", "online access", "video calls", "online safety", "scam protection", "digital choice"],
    summary: "The digital world opened to the people care usually leaves offline: connection as a care outcome (the video call, the online shop, the streamed service from a childhood faith), support and equipment matched to ability, online-safety support that protects without paternalism (scams and exploitation watched, choices respected), the offline right defended equally, and the service's own digital-by-default systems checked for who they exclude.",
  },
  {
    id: "bb-005",
    title: "Sexual Safety in Care Settings Policy",
    category: "Safe", subcategory: "Safeguarding & Rights", keyQuestion: "Safe",
    serviceTypes: ["All"], regulators: ["CQC", "CI", "CIW", "RQIA"],
    version: "1.0", lastUpdated: "2026-07-15", status: "updated", readTime: 13,
    tags: ["sexual safety", "sexualised behaviour", "consent and capacity", "resident-to-resident", "reporting culture", "dignity"],
    summary: "The subject services avoid until an incident forces it: sexual safety named and managed in the open — incidents between residents handled with capacity honesty (two people with dementia may both be unable to consent), staff-to-patient boundaries absolute with the grooming patterns trained, sexualised behaviour understood before it is punished, intimate care delivered to sexual-safety standards, and a reporting culture where the awkward observation is voiced the same day.",
  },
];

export const EXPANSION_2026G_CONTENT: Record<string, DocumentContent> = {
  "bb-001": {
    purpose: "This policy governs the sensors, alarms and monitoring systems that increasingly share the work of watching over people — falls detectors, door sensors, epilepsy monitors, GPS devices, acoustic monitoring, vital-signs telemetry. Used well, they buy earlier help and lighter-touch independence; used carelessly, they become surveillance that erodes privacy while a staffing model quietly hollows out behind them. The policy keeps both truths in view.",
    scope: "Covers all technology-enabled care: selection and assessment per person, consent and the privacy balance, installation and testing, alert response arrangements, data use and retention, review and removal, and the technology-versus-staffing honesty. Telecare interfaces with dc-003's response ladders and the lone-working machinery; the devices themselves ride saf-035's medical-device rules where they qualify.",
    responsibilities: [
      { role: "Registered Manager", duties: [
        "Ensure every deployment starts from a person's assessed need, not a product catalogue: the technology answers a named risk or goal in the care plan",
        "Own the consent and privacy work: capacity-appropriate consent, best-interests machinery where needed, and the least-intrusive-option discipline",
        "Staff the response: every alert type has a named responder and a timescale, tested — an unanswered alert is worse than no alert, because someone believed it was covered",
        "Review deployments on a cycle: still needed, still proportionate, still working, still wanted",
        "Hold the line on substitution: technology supplements care hours, and any proposal that trades staff presence for sensors is a provider-level decision made openly with commissioners and families" ] },
      { role: "Care Staff", duties: [
        "Know each person's technology: what is installed, what it alerts on, what the response plan says, and how to check it is working",
        "Respond to alerts per the plan and log the response — the alert answered informally and unrecorded teaches the system's data to lie",
        "Report faults, false-alarm patterns and the person's own reactions (distress, tampering, requests for removal) the same day",
        "Never improvise additions: the family's camera, the worker's smart speaker suggestion — every device enters through the assessment gate" ] },
    ],
    keyPoints: [
      "Deployment follows need: the assessment names the risk or goal (falls at night, seizure detection, wandering with road danger, medication prompts, loneliness and contact), considers the human alternatives honestly, selects the least intrusive technology that meets the need, and writes the deployment into the care plan with its response arrangements — technology fitted because it came with the flat, or because the catalogue was persuasive, fails the gate",
      "Consent is worked, not assumed: the person consents where they have capacity for this decision (explained in their communication style — what it senses, who sees the data, when it alerts, how to turn it off), and refusals stand; where capacity is absent, best-interests machinery runs with the privacy intrusion weighed explicitly (dc-009's least-restrictive discipline), family consultation, and the deployment recorded as the restrictive-practice-adjacent decision it can be — with DoLS/LPS interfaces considered where monitoring contributes to continuous supervision and control",
      "Privacy is engineered by mode: sensor types chosen for minimal intrusion (the door sensor before the camera, the acoustic threshold before the open microphone, the wearable the person controls before the room that watches), cameras in private spaces treated as exceptional with the strongest justification and review, visitors and staff informed where monitoring reaches them, and the data minimised — the system that records everything 'in case' fails data protection's first principle",
      "Alerts have owners and clocks: every alert type maps to a responder (on-site staff, the monitoring centre, dc-013's on-call, family per agreement) with a response time matched to the risk — and the map is tested end-to-end at installation and on the drill cycle (the test alert that takes forty minutes to reach a human is a finding that pre-empts a death), with dc-003's criticality logic applied to technology-flagged needs",
      "False alarms are managed, not endured: patterns reviewed monthly (the sensor that cries nightly gets recalibrated or replaced), because alarm fatigue is the failure mode — the hundredth false alert teaches responders the alarm means nothing, on exactly the night it doesn't",
      "The data serves the person first: monitoring data is read for care improvement (the night-walking pattern that redesigns the evening routine, the bathroom frequency that prompts the UTI check), retained per the records schedule and no longer, access-limited, and never repurposed for staff surveillance or convenience without its own lawful basis and transparency",
      "Devices are equipment with lifecycles: installation tested, batteries and connectivity on maintenance schedules (the dead pendant worn faithfully for a fortnight is the sector's recurring tragedy — battery checks are rostered, not remembered), faults escalated same-day with interim cover arranged (the human checks that resume until the sensor returns), and saf-035's machinery applied where devices are medical devices",
      "The substitution line is bright: technology extends care between human contact; it does not thin the contact — staffing models are never quietly rebalanced against sensor coverage, any genuine reconfiguration is decided at provider level with commissioners, families and the people themselves told plainly, and the review asks the question yearly: has anyone's human time shrunk since the technology arrived, and who decided that?",
    ],
    legislation: [
      "Data Protection Act 2018 / UK GDPR (monitoring data, minimisation, transparency)",
      "Human Rights Act 1998 (Article 8 — private life under observation)",
      "Mental Capacity Act 2005 and DoLS/LPS (consent, best interests, continuous supervision interfaces)",
      "Health and Social Care Act 2008 (Regulated Activities) Regulations 2014 — Regulations 9, 10, 12, 17",
      "Medical Devices Regulations 2002 (qualifying devices, via saf-035)",
    ],
    sections: [
      { heading: "The Deployment Gate", body: "Technology enters a person's life through the same gate as any care intervention: assessed need, considered options, proportionate answer. The assessment names what the technology is for — the specific risk (night falls between checks, seizures in sleep, the road at the end of the unlocked drive) or the specific goal (independence from hourly checks the person hates, contact with the daughter abroad) — and considers the alternatives honestly, including the human ones (the repositioned bedroom, the evening routine change, the extra check) and the nothing option (some risks are the person's to keep, per dc-009's positive-risk machinery). Selection then applies the least-intrusive ladder: the technology that senses the least while meeting the need wins — the bed-exit sensor before the room camera, the GPS watch the person wears and controls before the tracker they don't know about (covert deployment is not a care decision; where genuinely contemplated it runs the full best-interests and legal machinery with the presumption against), the alert threshold before the continuous feed. The deployment writes into the care plan: what is installed and where, what it senses and alerts on, the response map, the consent basis, the review date — and the installation itself is tested live (the triggered alert followed to its human) before anyone relies on it." },
      { heading: "Consent, Capacity and the Watched Life", body: "The consent conversation treats monitoring as the intimate thing it is: what the device senses (movement, sound, location, the body's signals), who sees the data and when (the alert-only model versus the reviewable log), what it will and won't do (the pendant that only works when worn and pressed — its limits stated so consent is informed), and the person's controls (pause, remove, refuse). Capacity is assessed for this decision where doubt is genuine, in the person's best hour with the demonstration that beats description — and the capacitous refusal ends the deployment conversation (revisited kindly as circumstances change, never worn down). Where capacity is absent: best interests with the intrusion weighed explicitly against the benefit (the analysis writes down what is being traded — a watched bedroom for unbroken sleep instead of hourly door-openings may be a good trade; the analysis proves someone thought so), consultation per the MCA's machinery, the least-restrictive alternative genuinely tried or reasoned away, the DoLS/LPS question asked where monitoring joins other measures in continuous supervision, and review dates that mean re-decision, not renewal-by-default. The household's other people are remembered: flat-mates in shared supported living, visiting family, and staff themselves are told what monitoring operates where they go (hr-026/dc-004's transparency logic), and shared spaces carry the higher justification bar." },
      { heading: "Response, Reliability and the Data's Duty", body: "An alert is a promise, and the policy funds it. The response map per person and alert type: who is alerted (on-site staff, monitoring centre, on-call, family per the agreed arrangement), by what channel, with what response time by risk (the seizure alert and the fridge-door alert do not share a clock), and what the responder does (attend, call, escalate through dc-003's ladders). The map is tested at installation end-to-end and on the drill cycle thereafter, response performance is logged and sampled, and the monitoring-centre contracts (where used) carry the response standards in writing with their performance reviewed. Reliability is maintained as a duty of care: battery and connectivity checks rostered (the daily worn-device check folded into care routines; the signal check after the router change), fault response same-day with interim human cover explicitly arranged and recorded, false-alarm patterns reviewed monthly with recalibration or replacement decisions, and the alarm-fatigue question asked directly in review: do responders still believe this alert? The data's governance closes the loop: minimised at design (alert events, not continuous archives, wherever the need allows), retained per schedule, access role-limited and logged, read for the person's benefit on a rhythm (the patterns that improve care plans), shared per igr-002's disciplines, and the repurposing line held — monitoring installed for falls does not become evidence-gathering about staff or visitors without its own lawful, transparent basis." },
      { heading: "Review, Removal and the Staffing Truth", body: "Deployments are reviewed on the care-plan cycle and on triggers (the person's request, distress or tampering, changed needs, repeated false alarms, a fault history): still needed (the risk may have passed — the post-surgical falls period ends), still proportionate (needs may have eased or the person's tolerance changed), still working (the reliability record read), still wanted (the person's current view sought in their communication style, with tampering and removal read as communication per dc-009's logic — the pulled-off pendant is a vote). Removal is a care decision made properly: the risk reassessed, the alternatives arranged, the family told, the plan updated — technology is retired deliberately, not left broadcasting to nobody. And the policy ends on its bright line, made auditable: the annual review compares human contact hours before and after technology deployments (per person and per service), any reduction is surfaced as a provider-level question with commissioners and families in the room, and the framing is fixed — the sensor that lets a person sleep unwatched is care improved; the sensor that lets a rota drop the night check without telling anyone is care withdrawn with the lights left on. The service commits to knowing, always, which one it is running." },
    ],
    appendices: [
      { title: "Technology Deployment Record (per person, per device)", type: "form", body:
"PERSON: ______  Device/system: ______  Installed: ______  Review due: ______\nNEED (named risk/goal from care plan): ______ | human alternatives considered: ______ | least-intrusive ladder applied (what less-intrusive options were rejected & why): ______\nSENSES: movement/sound/location/vitals/other: ____ | alert-only or reviewable log? ____ | private space? (higher bar, strongest justification): ____\nCONSENT: capacitous — informed consent (demonstrated, limits stated, controls explained; refusal STANDS) [ ] | lacks capacity — best interests (intrusion vs benefit written down, consultees, least restrictive, DoLS/LPS question asked) ref: ____ | COVERT: presumption against — full legal/BI machinery only: ____\nOTHERS AFFECTED: flat-mates/visitors/staff informed [ ]\nRESPONSE MAP: alert type → responder → channel → response time (by risk) → action | TESTED end-to-end at install (date) + drill cycle: ____\nRELIABILITY: battery/connectivity checks rostered (who/when): ____ | fault → same-day escalation + INTERIM HUMAN COVER arranged: ____\nDATA: minimised at design [ ] retention ____ | access-limited [ ] | read for the person's benefit (rhythm): ____ | repurposing line held [ ]" },
      { title: "Alert Response Test & Substitution Audit Sheet", type: "template", body:
"ALERT TESTS (install + cycle): device | test alert time | human-response time | vs standard | monitoring-centre performance (contract standards in writing) | findings & fixes\nFALSE-ALARM REVIEW (monthly): device | pattern | recalibrate/replace decision | ALARM-FATIGUE question asked: do responders still believe this alert?\nPERSON'S SIGNALS: distress/tampering/removal read as COMMUNICATION (the pulled-off pendant is a vote) → review triggered\nREMOVAL: risk reassessed | alternatives arranged | family told | plan updated — retired deliberately, never left broadcasting to nobody\nSUBSTITUTION AUDIT (annual, provider-level): human contact hours before/after deployment (per person & service) | any reduction surfaced openly (commissioners & families in the room) | THE FRAMING: sleep unwatched = care improved; night check dropped silently = care withdrawn with the lights left on — know which one we are running" },
    ],
  },
  "bb-002": {
    purpose: "This policy lets the service use AI and digital tools for what they genuinely offer — drafting, summarising, pattern-spotting, admin relief — while holding the lines that care cannot cede: accountable human judgement on every decision that touches a person, honesty with the people whose data feeds the machines, and the discipline that stops convenient tools becoming unexamined authorities.",
    scope: "Covers AI and algorithmic tools touching care delivery, records or the people supported: the approval gate, permitted and prohibited uses, the human-judgement rule, data protection and transparency, shadow-IT management, output quality and review, and staff training. General digital systems (care records platforms, rostering) ride their own governance; this policy engages wherever automation drafts, decides, predicts or summarises.",
    responsibilities: [
      { role: "Provider / Registered Manager", duties: [
        "Operate the approval gate: no AI or algorithmic tool touches care work, records or personal data until assessed and approved — including the free ones, especially the free ones",
        "Maintain the approved-tools register with each tool's permitted uses, data boundaries and review dates",
        "Complete the data protection work per tool: DPIAs where processing warrants, transparency information updated, processor arrangements verified (where does the pasted text go, and who trains on it?)",
        "Confront shadow IT with realism: workers use what helps — provide approved tools that help, and make the prohibition on unapproved ones specific and explained" ] },
      { role: "Clinical / Care Leads", duties: [
        "Own output quality in their domains: AI-drafted notes and plans sampled against reality, the error patterns of the tools learned and taught",
        "Enforce the human-judgement rule: every AI-assisted record entry, plan or decision carries an accountable human who has actually read it — the signature means verification, not throughput",
        "Watch the drift: the tool trusted beyond its competence (risk scores treated as verdicts, summaries replacing source-reading in decisions that need the source) is named and corrected" ] },
      { role: "All Staff", duties: [
        "Use only approved tools for anything touching people's information — no care notes, names, or identifiable details into unapproved chatbots, translators or apps, ever: the pasted paragraph is a disclosure to an unknown processor",
        "Verify before signing: AI-drafted content is read, corrected and owned — 'the system wrote it' is not an account any tribunal, inspector or family will accept from the person who signed it",
        "Report tool errors and oddities: the hallucinated medication in a draft note, the summary that inverted a meaning — same-day, because tool errors are systematic and the next draft carries them too" ] },
    ],
    keyPoints: [
      "The approval gate is universal: any tool that drafts, summarises, translates, transcribes, predicts or decides — commercial platforms, embedded features in existing systems (the care-records vendor's new 'AI summaries' toggle counts), and free public tools — is assessed before use for data protection (where data goes, retention, training use, processor status), clinical safety (error modes, the stakes of its mistakes), and fit (what it is approved FOR, stated narrowly)",
      "Permitted uses are named per tool: the register states what each tool may do (draft routine correspondence, transcribe with verification, summarise documents the human then checks against source, suggest care-plan wording the author owns) and what it may not (autonomous clinical decisions, unreviewed record entries, identifiable data into tools without processor agreements) — and 'approved' never means 'approved for everything'",
      "The human-judgement rule is absolute: AI assists; accountable humans decide — every record entry, assessment, plan and communication carries a named human author who has verified the content, clinical and care decisions rest on human judgement with AI input weighted as the fallible aid it is, and the rule's teeth are cultural: signing unread AI output is treated as the record falsification it functionally is (pc-004's integrity machinery)",
      "Transparency reaches the people whose data flows: privacy information updated to name AI processing in plain terms, the people supported (and families per the involvement plans) told where tools touch their records or care in ways that matter, and objections handled per data-protection rights rather than smoothed past",
      "Shadow IT is managed with realism and teeth: the prohibition on unapproved tools is specific (named examples — the free chatbot, the personal translation app, the transcription site) and explained (the pasted care note is a data breach to an unknown processor, possibly training tomorrow's model on Mrs H's continence needs), while the pull is answered honestly — where workers reach for unapproved tools because approved ones don't exist, the finding is a provisioning gap for the register's next review, not just a conduct note",
      "Bias and equity are watched where tools predict: any tool scoring risk, prioritising cases or predicting outcomes is reviewed for whose data trained it and who it misreads (falls scores validated on populations unlike ours, speech tools that fail accents, triage aids that under-weight the quiet), with the review recurring — bias is a maintenance issue, not an installation checkbox",
      "Outputs are quality-sampled on a rhythm: AI-assisted notes, summaries and translations sampled against source and reality monthly in each domain, error patterns logged and taught (each tool's characteristic failures — invented specifics, inverted negations, confident wrongness — become training content), and the tool whose error rate or drift outgrows its value is retired from the register as deliberately as it entered",
      "Incidents run the established machinery: identifiable data into an unapproved tool is a data-breach event (igr-003's clocks), an AI-influenced error reaching a person is an incident with SEA-grade review (pc-001 where clinical), and the tool's role is named honestly in both — the point is not to hide the machine but to learn where the human-machine seam failed",
    ],
    legislation: [
      "Data Protection Act 2018 / UK GDPR (automated processing, DPIAs, processor duties, transparency)",
      "Health and Social Care Act 2008 (Regulated Activities) Regulations 2014 — Regulations 12, 17",
      "Equality Act 2010 (algorithmic bias and discrimination)",
      "Common law confidentiality (disclosure to processors)",
      "Professional record-keeping and accountability standards (via pc-004)",
    ],
    sections: [
      { heading: "The Gate and the Register", body: "The approval gate is a proportionate process with a fixed sequence: proposal (what tool, for what use, by whom — including the embedded features vendors switch on inside existing systems, which are caught by the standing rule that vendors' new AI features are OFF until assessed), data-protection assessment (what data the use involves, where it travels, the processor's terms read for retention and training use, the DPIA where processing meets its thresholds, and the hard question for free tools — if the product is free, the data is the price, and care data is not the service's to spend), safety assessment (the error modes and their stakes: the tool that mis-drafts a newsletter differs from the tool that mis-summarises a hospital discharge), and the approval decision recording permitted uses narrowly, prohibited uses explicitly, the transparency actions required, and the review date. The register is the living output: every approved tool with its scope, owner, data boundaries and review date; visible to staff (knowing what IS approved is half of stopping what isn't); reviewed on the cycle and on triggers (the vendor's terms change, the error pattern emerges, the better tool arrives). Retirement is part of the lifecycle: tools leave the register deliberately, with the workflow that depended on them re-provisioned rather than left to shadow solutions." },
      { heading: "The Human-Judgement Rule in Practice", body: "The rule is stated once and applied everywhere: AI drafts, suggests, summarises and flags; accountable humans read, verify, decide and sign. In records: AI-assisted entries (transcribed consultations, drafted daily notes, summarised histories) are read and corrected by the human who signs them, with the signature carrying pc-004's full meaning — the author attests the content, and the characteristic AI failures (invented specifics that sound plausible, negations inverted, the confident filling of gaps the source left empty) are trained so verification knows what it is looking for. In decisions: care plans, risk assessments, clinical judgements and safeguarding decisions rest on human reasoning with AI input weighted as one fallible source — the risk score informs the falls assessment, it does not conclude it; the summary orients the reader toward the source, it does not replace source-reading where the decision's stakes demand the source (the safeguarding referral is written from the records, not from the summary of the records). In communication: AI-drafted letters and messages to people, families and professionals are owned by their human sender with tone and truth verified — the empathetic-sounding paragraph the sender never read is a small fraud on the relationship. The rule's enforcement is cultural and procedural: verification time is budgeted in workload honestly (the tool that saves ten minutes of drafting but needs five of checking still saves five — pretending it needs zero is where the harm lives), spot-checks compare signed content against source, and the signed-but-unread pattern is treated with pc-004's falsification seriousness." },
      { heading: "Data, Transparency and Shadow IT", body: "Data protection work is done per tool, not per policy: the processing mapped (what personal data, whose, where it flows, how long it lives), processor arrangements verified in writing (the terms read for the training-use clause that turns care notes into model fodder), DPIAs completed where thresholds bite (most tools touching health data will), privacy notices updated in plain language ('we use software that helps draft care notes; a person always checks and signs them; here is where the data goes'), and the objection and rights machinery ready. Transparency is honoured at the human level too: the people supported are told about tools that touch their care in terms that respect them (dc-009's communication machinery), families per the involvement plans, and staff about tools that process their data (dc-004's monitoring-transparency logic extended). Shadow IT is confronted as the workforce reality it is: the induction and refresher training names the specific prohibited patterns — care information into free chatbots, photos of records to personal apps 'to translate for the family', the transcription website for the meeting recording — and explains each as the data breach it is; the reporting route for accidental use is blame-calibrated (the worker who self-reports the pasted paragraph gets the igr-003 breach machinery and thanks for the honesty; concealment is the conduct issue); and the provisioning answer runs alongside — the register review asks quarterly what workers are reaching for and why, and closes the gaps with approved tools, because a workforce given good tools polices the perimeter itself, and one denied them dissolves it." },
      { heading: "Quality, Bias and the Long Watch", body: "Tool performance is managed like any care-critical system. Quality sampling: each domain's lead samples AI-assisted outputs monthly against source and reality — the transcribed consultation against the clinician's memory and the patient's account, the summarised discharge against the letter, the drafted plan against the person — with error patterns logged per tool, taught in team refreshers, and escalated where they cross safety lines. Bias review: predictive and prioritising tools are examined at approval and on the cycle for training-population fit, differential error rates (the speech tool's accent performance, the risk score's age calibration), and the equity question in deployment (who gets flagged, who gets missed, and does that pattern track protected characteristics) — with Equality Act exposure named where it exists and the tool constrained or retired where bias cannot be managed. Drift watch: the annual review asks the trust question per tool — has this moved from aid to authority (the score nobody overrides, the summary nobody checks anymore), and does its actual use still match its approved scope? Incidents close the loop: data into unapproved tools runs igr-003's breach clocks; AI-influenced errors reaching people run the incident and SEA machinery with the human-machine seam examined honestly (was the output wrong, or the verification skipped, or the time for verification never budgeted?); and the learning feeds the register, the training and the workload models — because the policy's end state is not a service that fears its tools, but one that knows them: what each is for, what each gets wrong, and whose name stands behind every word that reaches a person's life." },
    ],
    appendices: [
      { title: "AI Tool Approval & Register Entry", type: "form", body:
"TOOL: ______ (incl. embedded vendor features — new AI toggles are OFF until assessed)  Proposed by/for: ______\nDATA ASSESSMENT: personal data involved | where it flows | processor terms READ (retention? TRAINING USE?) | DPIA needed/done (ref: ____) | free-tool question answered (if free, data is the price — is it ours to spend?)\nSAFETY ASSESSMENT: error modes | stakes of mistakes (newsletter ≠ discharge summary) | characteristic failures to train (invented specifics / inverted negations / confident gap-filling)\nAPPROVAL: permitted uses (NARROW): ____ | prohibited uses (EXPLICIT): ____ | transparency actions (privacy notice, people/families/staff told): ____ | verification time budgeted in workload: ____ | REVIEW DATE: ____\nBIAS (predictive/prioritising tools): training-population fit | differential error rates | deployment equity (who's flagged, who's missed, protected-characteristic tracking) | recurring review\nRETIREMENT: workflow re-provisioned (never left to shadow solutions)" },
      { title: "Human-Judgement Rule & Shadow-IT Card", type: "template", body:
"THE RULE: AI drafts, suggests, summarises, flags — ACCOUNTABLE HUMANS read, verify, decide, sign.\nSIGNING = VERIFICATION: your signature attests the content (pc-004's full meaning) | signed-but-unread = functional falsification | decisions rest on human reasoning (the score informs the assessment, never concludes it; high-stakes decisions read the SOURCE, not the summary)\nNEVER (each = data breach to an unknown processor): care notes/names/identifiable details into unapproved chatbots | record photos into personal apps 'to translate' | meeting audio into transcription sites\nACCIDENTAL USE: self-report same day → igr-003 machinery + thanks for honesty | concealment is the conduct issue\nREACHING FOR UNAPPROVED TOOLS because approved ones don't exist? Say so — that's a provisioning gap for the quarterly register review, and the fix is a better tool, not a quieter workaround\nREPORT TOOL ERRORS same-day (hallucinated medication, inverted meaning) — tool errors are SYSTEMATIC; the next draft carries them too\nMONTHLY: outputs sampled vs source | error patterns taught | ANNUAL trust question per tool: aid or unexamined authority?" },
    ],
  },
  "bb-003": {
    purpose: "This policy prepares the service for the day its systems turn hostile or dark — the ransomware note where the care records were, the compromised email quietly forwarding referrals, the payroll diverted by a convincing invoice. Care services are soft targets holding hard-to-replace data, and the difference between a bad week and an existential event is decided before the incident: by backups that restore, paper that is ready, and people who know their first hour.",
    scope: "Covers cyber incident preparedness and response: prevention basics, detection and the first-hour drill, care continuity on manual fallbacks, the notification map, recovery and the ransom question, and post-incident learning. It extends the business continuity policy (wl-007/gov-007) into the cyber domain and runs igr-003's breach machinery where personal data is involved.",
    responsibilities: [
      { role: "Provider / Registered Manager", duties: [
        "Own preparedness: the prevention basics funded and verified, backups tested by actual restoration, the paper fallback packs printed and current, the response plan drilled",
        "Lead incident response: the first-hour decisions (isolate, preserve, activate fallbacks), the notification map worked on its clocks, and the ransom question decided at provider level with advice — never by a manager alone at midnight",
        "Hold the external relationships before they're needed: IT support with incident-response capability, cyber insurance where held (with its notification duties known), and the reporting routes (Action Fraud/NCSC-style channels, ICO, regulator, commissioners)" ] },
      { role: "All Staff", duties: [
        "Practise the prevention habits: phishing suspicion as reflex (the unexpected attachment, the urgent payment change, the login page that isn't), passwords and MFA per the standards, devices locked and updated",
        "Report the weird immediately: the odd email, the system behaving strangely, the login that failed twice then worked — early reports are how incidents stay small, and the reporter of a clicked link is thanked for the report, not punished for the click",
        "Know the fallback: where the paper packs live, how care runs without the system, and that care never stops for a screen" ] },
    ],
    keyPoints: [
      "Prevention is the cheap nine-tenths: MFA on everything that matters (email, records, remote access), patching current with the update rhythm owned, backups on the tested 3-2-1 pattern (with at least one copy offline or immutable — ransomware encrypts the backups it can reach), access per role with leavers revoked day-one (hr interfaces), phishing training that uses real examples and praised reporting, and the basics audited annually because they decay",
      "Backups are tested by restoring: the backup that has never been restored is a hope, not a plan — restoration tested on the cycle (a real records sample recovered to a clean environment, timed), the recovery-time reality known and matched against the care continuity plan's assumptions, and the backup scope verified against what care actually needs (the records, the MARs, the rosters, the contact lists)",
      "The first hour is drilled: suspect compromise → isolate (affected machines off the network — not powered off where forensics matter, the plan states which), preserve (nothing wiped, nothing 'tidied', the screenshot taken), activate (paper fallbacks out, care continuity first), escalate (IT support and the provider on the incident line, the log started with times) — laminated, practised, and known by the weekend shift as well as the office",
      "Care continuity cannot wait for IT: the paper fallback packs — current medication lists and MARs, care plan essentials, contact lists, blank recording sheets — printed or exported on a rhythm (a stale fallback is a different incident), stored accessibly per site, and the manual operating mode practised in the annual drill (dc-004's ECM fallback logic extended to everything): visits happen, medication is given and recorded, on-call runs, all on paper, for as long as it takes",
      "The notification map runs on clocks: ICO within 72 hours where personal data breach thresholds are met (igr-003's machinery — and a care-records compromise almost always meets them), the regulator per notification duties, commissioners per contract, the people whose data is affected when thresholds require (told honestly, with what it means for them and what the service is doing), cyber insurance within its policy windows, police/Action Fraud for the crime, and the log recording every notification's time and content",
      "The ransom question is pre-decided in posture: payment is a provider-level decision taken with specialist and legal advice and law-enforcement engagement — the policy's stated posture is against payment (it funds the attacker, marks the service as a payer, and buys no guarantee), while acknowledging the decision belongs to the moment's facts; what is absolute is that no manager negotiates alone and no payment happens outside sanctions checks",
      "Recovery is verification, not just restoration: systems rebuilt or cleaned to the IT responder's standard, credentials rotated wholesale, the entry route found and closed before reconnection (restoring into the same hole re-runs the incident), data integrity checked (what changed while the attacker had access — the tampered record is rarer than the stolen one but worse), and the paper-period's records reconciled back into the systems",
      "The post-incident review is candid: timeline against the drill's assumptions, what the fallbacks actually delivered, notification performance against clocks, the entry route and its lesson (the unpatched box, the clicked link — with the just-culture framing that trains rather than shames), and the findings funded — the review that recommends MFA again, annually, unfunded, is the service documenting its own negligence in advance",
    ],
    legislation: [
      "Data Protection Act 2018 / UK GDPR (breach notification, security duties)",
      "Health and Social Care Act 2008 (Regulated Activities) Regulations 2014 — Regulations 12, 17 (and 18 notifications)",
      "Computer Misuse Act 1990 (the crime's frame)",
      "Network and Information Systems Regulations (where in scope)",
      "Sanctions regulations (ransom payment interfaces)",
    ],
    sections: [
      { heading: "Prevention and the Tested Backup", body: "The prevention baseline is specified, funded and audited: multi-factor authentication on email, records systems, remote access and admin accounts (the single control that defeats most credential attacks); patching owned as a rhythm (operating systems and applications current, the end-of-life system inventory known and retired on a plan — the unsupported machine is a standing invitation); access hygiene (role-based permissions, shared logins banned per pc-004, leaver revocation on the last day, dormant accounts swept quarterly); email defences configured (filtering, external-sender flagging, the payment-change verification rule: any change to payee details is verified by phone on a known number, always — invoice fraud is the sector's commonest loss); device standards (encryption on portables, locking habits, the community workforce's devices per dc-004's custody logic); and the human layer trained with realism — phishing examples from the sector's actual attacks, reporting praised in the same breath as clicking is forgiven (the culture where clicking is shameful is the culture where clicks go unreported for six hours, which is the whole game). Backups carry the recovery: the 3-2-1 pattern with an offline or immutable copy, scope verified against care's real needs, and restoration TESTED on the cycle — a timed exercise recovering real data to a clean environment, with the result compared against the continuity plan's assumptions and the gap (if the restore takes three days and the plan assumed one) surfaced to the provider as the funding question it is." },
      { heading: "The First Hour and the Paper Bridge", body: "Detection is democratised: anyone can notice (the strange login, the encrypted files, the colleague's odd email 'from' the manager, the system crawling), the report route is one call (manager/on-call, who holds the drill card), and early reporting is culturally protected. The first-hour drill then runs its card: ISOLATE — affected devices disconnected from the network (cable out, wifi off; powered off only where the plan says, because memory forensics die with the power); PRESERVE — nothing deleted, reset or tidied, the ransom note photographed, the log started (times, observations, actions); ACTIVATE — the paper fallback packs deployed and care continuity declared (below); ESCALATE — IT incident support engaged (the contract with response times, agreed before), the provider informed, and the incident lead named (dc-013's on-call holds the role out of hours until relieved). The paper bridge is the policy's care heart: fallback packs per site/service — current medication lists and MAR-equivalents, care plan essentials (the criticality flags, allergies, key risks per person), contact chains (staff, families, GPs, pharmacies, on-call), rosters and visit lists, blank recording stationery — refreshed on the stated rhythm (weekly exports where systems allow; a fallback pack three months stale mis-medicates), stored where the weekend shift can find them, and drilled annually as a real exercise: a session run entirely on paper, timed and debriefed, because the first time care runs manual cannot be the night it matters." },
      { heading: "Notification, Ransom and Recovery", body: "The notification map runs in parallel with response, on its clocks: the ICO assessment within igr-003's machinery (the 72-hour clock started at awareness — and a care-records compromise almost always crosses the threshold; the assessment is documented either way), regulator notification per the notifications policy where thresholds bite (service disruption affecting care usually does), commissioners per contract terms, affected people and families told where the risk to them requires it — honestly, in plain language, with what happened, what it means for them (the fraud-watch advice where identities or finances are exposed) and what the service is doing — cyber insurance notified within policy windows (late notification voids cover), and police/Action Fraud engaged for the crime with reference numbers logged. The ransom posture is pre-stated: against payment, for the reasons the policy names (funding attackers, painting a target, no guarantee — and the sanctions-law exposure where attackers are listed entities), with the final decision reserved to provider level, taken only with specialist incident-response and legal advice and law-enforcement engagement, and never by anyone alone. Recovery is disciplined: the entry route identified and closed before anything reconnects, systems cleaned or rebuilt to the responder's standard, credentials rotated wholesale (every password, every token — the attacker kept copies), MFA verified everywhere, data integrity reviewed (exfiltration assessed for the notification map; tampering checked where the attacker had write access — the medication record that might have been altered is clinically reviewed), and the paper period reconciled back into the systems with pc-004's integrity rules (entries dated as made, the gap documented)." },
      { heading: "Learning and the Standing Posture", body: "The post-incident review runs SEA-grade (pc-001's temperament): the timeline reconstructed against the drill's assumptions (where did the first hour actually go), detection-to-isolation and awareness-to-notification intervals measured, the fallbacks' real performance recorded (what the paper packs lacked becomes next quarter's refresh list), the entry route's lesson taught with just-culture framing (the clicked link trains the next phishing example; the unpatched server indicts the patching rhythm, not the intern), and the findings costed and funded with provider sign-off — the review's recommendations enter the risk register with owners and dates, because the un-actioned cyber lesson is tomorrow's repeat incident with better documentation. The standing posture is maintained between incidents: the annual drill (tabletop minimum, live paper exercise where the service can), the prevention audit (MFA coverage, patch status, backup restoration test, leaver-revocation sample, phishing-simulation results where used — run with the same praised-reporting culture), the supplier picture reviewed (the care-records platform's own resilience and breach duties, the IT contract's response times), and the horizon watched through the sector's alert channels — because care's cyber threat model changes, and the service that treated this policy as a 2026 document will meet a 2029 attack with 2026 defences. The closing frame is the continuity one: the service's promise through any cyber event is that care continues, visibly unchanged from the outside — medication on time, visits made, families answered — while the systems fight their fight behind the paper bridge." },
    ],
    appendices: [
      { title: "First-Hour Drill Card & Paper Fallback Pack Contents", type: "template", body:
"SUSPECT COMPROMISE (encrypted files / ransom note / odd 'from-the-manager' emails / strange logins / system crawling) → ONE CALL: manager/on-call\nFIRST HOUR:\n1. ISOLATE — network cable OUT, wifi OFF (power off ONLY where plan says — forensics die with power)\n2. PRESERVE — delete nothing, reset nothing, photograph the note, START THE LOG (times/observations/actions)\n3. ACTIVATE — paper packs OUT, care continuity declared: care never stops for a screen\n4. ESCALATE — IT incident support (contract: ____, response time: ____) | provider | incident lead named (on-call holds OOH)\nPAPER PACK (per site — refreshed ____; stale packs mis-medicate): current med lists & MAR-equivalents | care plan essentials (criticality flags, allergies, key risks) | contact chains (staff/families/GPs/pharmacies/on-call) | rosters & visit lists | blank recording stationery | this card\nREPORTING CULTURE: the reporter of a clicked link is THANKED for the report — shame buys six silent hours, which is the whole game\nPAYMENT-CHANGE RULE (standing): any payee-detail change verified by phone on a KNOWN number, always" },
      { title: "Notification Map & Prevention Audit Sheet", type: "template", body:
"NOTIFICATION CLOCKS (parallel with response, all logged): ICO — 72h from awareness where thresholds met (records compromise almost always does; assessment documented either way, igr-003) | regulator (per notifications policy — care-affecting disruption usually qualifies) | commissioners (per contract) | affected people/families (honest, plain, what-it-means + fraud-watch advice where exposed) | cyber insurance (within policy window — late voids) | police/Action Fraud (crime ref logged)\nRANSOM POSTURE: against payment (funds attackers, paints target, no guarantee, sanctions exposure) | final decision PROVIDER-LEVEL ONLY with specialist + legal + law-enforcement | nobody negotiates alone\nRECOVERY GATE: entry route found & closed BEFORE reconnection | rebuild/clean to responder standard | credentials rotated WHOLESALE | integrity reviewed (tampering → clinical review of touched records) | paper period reconciled (pc-004 integrity)\nANNUAL PREVENTION AUDIT: MFA coverage | patch status & EOL inventory | backup RESTORATION test (timed, vs continuity assumptions) | leaver-revocation sample | dormant-account sweep | phishing-sim results (praised-reporting culture) | drill done (tabletop min., live paper exercise where possible) | findings FUNDED (unfunded recommendations = negligence documented in advance)" },
    ],
  },
  "bb-004": {
    purpose: "This policy opens the digital world to the people care most often leaves outside it. The video call that dissolves distance, the online shop that restores choice, the streamed service from a childhood faith, the game that fills an empty afternoon — these are wellbeing outcomes with a router in the middle. Digital exclusion in care is not a technology gap; it is a life gap, and the policy treats connection as care.",
    scope: "Covers digital inclusion for the people supported: assessment of digital wishes and abilities, equipment and connectivity, support and skill-building, online safety with autonomy respected, the offline right, and the service's own digital-by-default systems audited for exclusion. Staff digital tools ride their own policies; bb-001 covers monitoring technology; this policy is about the person's own digital life.",
    responsibilities: [
      { role: "Registered Manager", duties: [
        "Build digital into assessment and care planning: wishes, history and abilities asked about like any other domain — the person who ran a business on email did not lose the skill at the care home door",
        "Provide the infrastructure the setting owes: wifi that reaches bedrooms and works (the residents' wifi that fails in the east wing is a connection denied by architecture), shared devices where personal ones don't exist, and support time rostered rather than squeezed",
        "Balance safety and autonomy per person through the established machinery (capacity, positive risk, dc-009's doctrine) — protection from scams without confiscation of the internet",
        "Audit the service's own digital-by-default: what does the service now do only online (menus, feedback, family updates, booking), and who does that structurally exclude?" ] },
      { role: "Care & Support Staff", duties: [
        "Support digital life as care work: the video call set up with the same reliability as the meal, the person's device charged and working, the new skill taught patiently at the person's pace",
        "Watch for the harms without becoming the censor: the scam patterns reported (dc-011's recognition extended online), the distressing content noticed, the exploitation flags raised — through the proper machinery, not through quiet confiscation",
        "Respect the person's digital privacy: their messages, browsing and calls are theirs — support is not surveillance, and the screen glanced at uninvited is a drawer opened without asking (dc-007's rules extended)" ] },
    ],
    keyPoints: [
      "Digital wishes are assessed like nutrition: at admission or service start, the conversation asks the digital history (what did you use, what did you love, what do you miss), current wishes (the daughter on video, the football scores, the online bridge club, banking kept in their own hands), abilities and barriers (vision, dexterity, memory, confidence — each with its adaptive answers), and the answer 'nothing, thank you' respected as fully as any other (the offline right is a right, revisited kindly, never pathologised)",
      "Equipment and connection are provided or brokered: reliable wifi throughout residential settings as infrastructure (tested where people actually sit, not at the office router), shared tablets with simplified launchers where personal devices don't exist, support for the person's own devices (the family-bought tablet set up properly, dc-012-style custody respect for the person's property per ch-009), adaptive hardware where bodies need it (large-key keyboards, switch access, voice control), and the community services' version — support to get online at home, the social-tariff broadband conversation (dc-011's benefits-maximisation logic extended to connectivity poverty)",
      "Skills are taught at life pace: the one-thing-at-a-time approach (this week the video call answers itself; next month maybe photos), repetition without impatience, written or pictorial crib cards in the person's format, family enlisted as coaches where relationships suit, peer teaching celebrated (the resident who shows others is contributing per dc-010's belonging logic), and failure treated as the technology's fault first (it usually is — the interface designed for twenty-five-year-olds is the barrier, not the eighty-year-old)",
      "Online safety runs the positive-risk machinery: the risks are real (romance and prize scams targeting exactly this population, phishing, the 'grandson' needing urgent transfer money, exploitative contacts, distressing content) and the responses are graded — education first (the scam patterns taught conversationally, the check-with-someone habit built), technical measures by agreement (filters and limits the person chooses or best-interests machinery justifies, never imposed on capacitous adults by staff prudence), vigilance through relationship (the worker who notices the new online 'friend' at benefits time reports through dc-011/safeguarding routes), and confiscation named as the failure it is — the capacitous person's right to be scammed is real (documented, minimised at the edges, revisited), exactly as dc-009 holds for every other risk",
      "Video contact is a care standard, not a treat: the family call supported reliably (scheduled where wanted, the device charged, the room private, the staff hands available for the tech but out of the conversation), end-of-life and hospital separations bridged by screen as standing practice (saf-045/046's lesson kept), and the failed call treated as a missed visit — rearranged same-day with the family told why",
      "Digital life includes the whole life: faith streamed from the childhood tradition (dc-010's faith geography extended online), culture and language content in the person's own tongue (the radio station from home dissolving fifty years of distance), online communities for the interests the local area can't serve, creativity (the photo archive project, the life story recorded), and practical agency (online shopping restoring choice, banking kept in the person's hands with dc-011's support-not-control disciplines)",
      "The service's own systems are audited for exclusion: everything the service has made digital-by-default (menus by QR code, feedback by portal, family updates by app, GP access by phone app) is listed annually with the question 'who cannot use this, and what is their equal route?' — the paper menu, the spoken survey, the printed photos for the family without smartphones — because a service celebrating residents' digital inclusion while its own systems exclude them has automated its irony",
      "Privacy holds online: the person's accounts, messages and browsing are theirs (support with consent, never covert monitoring of a capacitous adult's digital life; incapacity-context monitoring through best-interests machinery with bb-001's proportionality), passwords supported through proper arrangements (the password book in the person's control, dc-011's PIN logic extended — staff never hold credentials informally), and hr-024's staff boundaries respected in reverse (staff don't friend, follow or surveil the people they support)",
    ],
    legislation: [
      "Care Act 2014 (wellbeing domains — relationships, recreation, control over daily life)",
      "Mental Capacity Act 2005 (online decisions, positive risk)",
      "Human Rights Act 1998 (Article 8 — correspondence and private life; Article 10 — receiving information)",
      "Equality Act 2010 (reasonable adjustments in digital provision)",
      "Data Protection Act 2018 (the person's own data and accounts)",
    ],
    sections: [
      { heading: "Assessment: The Digital Life History", body: "The digital conversation enters assessment alongside food, faith and family: what the person used and loved (the emailer, the online bridge player, the eBay seller, the never-touched-it-and-proud), what they miss (the grandchildren's photos arrive somewhere they can no longer see), what they want now (named concretely — 'video calls with Susan on Sundays' plans better than 'digital inclusion'), and what stands between (vision, hearing, dexterity, memory, confidence, money, and the fear of breaking something — each barrier with its adaptive answer, from font sizes to switch access to the reassurance that nothing they press can break it). The assessment writes into the care plan like any other domain: goals, supports, equipment, the safety picture, review dates. Two honesty rules govern it: capability is presumed and history respected (the person who managed spreadsheets manages a tablet with the right on-ramp — the care setting's low expectations are the first barrier), and the offline choice is honoured completely (the 'no thank you' recorded, revisited kindly at reviews because circumstances and curiosity change, and never treated as a deficit — a life fully lived offline is not a gap in the service's statistics)." },
      { heading: "Provision: Wifi, Devices and Hands That Help", body: "Infrastructure is the setting's duty: residential wifi that works where people live (tested in bedrooms and lounges quarterly, the dead zones fixed — connectivity that stops at the office door is a service for staff wearing residents' clothes), guest access for visiting families, and bandwidth planned for evening video-call peaks. Devices follow a ladder: the person's own first (set up properly, cased and labelled per ch-009's property care, charged as a care-routine item, repaired through the family or the service's brokering), shared devices where personal ones don't exist (tablets with simplified launchers, cleaned between users per IPC sense, booked fairly), and adaptive equipment where standard hardware excludes (large-print keyboards, styluses for tremor, voice assistants configured for the person's accent and wishes, switch access for the least mobile — OT input brokered where complexity warrants). Community settings translate the duty: support to assess home connectivity, the social-tariff broadband conversation held (connectivity poverty is fuel poverty's younger sibling — dc-011's signposting extended), the person's devices supported within visit scopes, and the library and community-hub options mapped (dc-010's community geography including its free wifi and its digital-inclusion classes). Support time is rostered honestly: teaching and troubleshooting are care tasks in the plan with minutes attached, not favours squeezed from handover margins — the video call that needs ten staff minutes to happen is commissioned care, and pretending otherwise is how digital inclusion dies of goodwill." },
      { heading: "Safety With Autonomy: The Online Positive-Risk Frame", body: "Online risk runs the same machinery as every other risk in the service — dc-009's positive-risk doctrine, dc-011's financial-abuse vigilance, saf-001's safeguarding thresholds — applied to the digital terrain. Education first: scam literacy built conversationally (the patterns taught with real examples — the prize that needs a fee, the romance that needs a transfer, the 'grandson' in trouble needing urgent quiet help, the bank that never asks for the full password), the check-with-someone-first habit cultivated as strength not dependence, and the family enlisted in consistent messaging. Technical measures by agreement: filters, spending limits, contact controls and simplified modes are tools the person chooses (or best-interests machinery justifies for those who cannot) — never imposed on capacitous adults by institutional prudence, because the capacitous person's right to unwise clicks is dc-009's unwise-decision principle wearing a browser. Vigilance through relationship: the workers who support digital life notice its weather — the new online friend, the anxiety after screen time, the requests for cash or cards that follow a pattern (dc-011's benefits-day logic online), the content that distresses — and report through the established routes rather than investigating or confiscating solo. Escalation when thresholds bite: exploitation, grooming and financial abuse run the safeguarding machinery at full strength with the digital evidence preserved (screenshots per hr-024's craft), and the response protects the person's digital life while removing the abuser from it — the goal is the scammer blocked, not the tablet confiscated, because punishing the victim with disconnection teaches the lesson nobody meant." },
      { heading: "The Connected Life, and the Service's Own Mirror", body: "Digital inclusion earns its place by what it delivers: contact (video calls as reliable care standard — scheduled, supported, private, with the failed call treated as the missed visit it is; messaging and photo-sharing with the family flow the person wants; the isolation data from ch-008's visitor audit answered partly here, because the man nobody visits may have a brother in Australia one setup away), meaning (faith streamed from the person's own tradition, the hometown radio station, films and music of their language and era, the online communities that serve interests the postcode cannot — dc-010's belonging logic extended into the wireless world), agency (online shopping restoring the choices institutional supply removed, banking kept in the person's own hands with dc-011's support-not-control rails, the person's own appointments booked by the person where systems and capacity allow), and joy (games, puzzles, the photo archive scanned together, the life story recorded — activities staff time already funds, upgraded by connection). The service's annual mirror closes the policy: the digital-by-default audit lists everything the service or its ecosystem now assumes online (menus, surveys, family apps, GP portals, benefit claims per dc-011) and answers, per item, who is excluded and what their equal-value route is — with the finding owned that any service whose own front doors have quietly gone digital owes its offline people either a bridge or a genuinely equal path, and the review question asked in dc-010's spirit: is each person's world larger than it was last year, by their own measure — and where the answer is no, was the router, the fear, or our rostering the reason?" },
    ],
    appendices: [
      { title: "Digital Life Assessment & Support Plan (per person)", type: "form", body:
"PERSON: ______\nDIGITAL HISTORY: used & loved: ____ | misses: ____ | never-and-happy [ ] (offline right honoured, revisited kindly, never pathologised)\nWISHES (concrete): e.g. 'video calls with ____ on ____' | shopping | banking (own hands, dc-011 rails) | faith/culture content (tradition/language: ____) | interests & communities | games/creative: ____\nBARRIERS & ADAPTATIONS: vision (fonts/contrast/voice) | dexterity (keyboards/stylus/switch — OT brokered?) | memory (crib cards in their format, one-thing-at-a-time) | confidence ('nothing you press can break it') | money (social-tariff conversation)\nEQUIPMENT: own device (set up, cased, labelled, CHARGED as care routine) | shared device (simplified launcher, cleaned, booked fairly) | adaptive: ____\nSUPPORT TIME (rostered, minutes attached — not goodwill): ____\nSAFETY (positive-risk frame): scam literacy taught (patterns: fee-for-prize / romance transfer / urgent 'grandson' / bank-asks-password) | check-with-someone habit | technical measures BY AGREEMENT (capacitous choice / BI machinery): ____ | PRIVACY: accounts & messages THEIRS; no informal credential-holding; support ≠ surveillance\nREVIEW: is their world larger this year, by their measure? ____" },
      { title: "Video Contact Standard & Digital-by-Default Audit", type: "template", body:
"VIDEO CONTACT (care standard, not treat): scheduled where wanted | device charged & tested BEFORE | room private | staff hands for tech, OUT of the conversation | failed call = missed visit → rearranged same-day, family told why | EOL & hospital separations bridged by screen as standing practice\nWIFI: tested where people SIT (bedrooms/lounges) quarterly | dead zones fixed | guest access for families | evening bandwidth planned\nONLINE SAFEGUARDING ESCALATION: exploitation/grooming/financial abuse → full machinery | evidence preserved (screenshots) | goal = scammer blocked, NOT tablet confiscated (disconnection punishes the victim)\nDIGITAL-BY-DEFAULT AUDIT (annual — the service's own mirror): list everything assumed online (menus/QR | feedback portals | family apps | GP portals | benefit claims) → per item: WHO IS EXCLUDED + their equal-value route (paper menu / spoken survey / printed photos): ____\nISOLATION CROSS-CHECK: ch-008's nobody-visits list read against digital options (the brother in Australia one setup away)" },
    ],
  },
  "bb-005": {
    purpose: "This policy names what care settings historically managed by silence: sexual safety. People in care are sexually assaulted — by other residents, occasionally by staff, sometimes by visitors — at rates every national review confirms and most local cultures leave undiscussed until an incident forces the subject. The policy's premise is that safety follows candour: the service that can talk about sexual safety in a team meeting can protect people; the one that cannot, cannot.",
    scope: "Covers sexual safety across the service: the open-culture foundation, incidents between people supported (with the capacity honesty they demand), staff-to-person boundaries and grooming patterns, visitors and third parties, sexualised behaviour understood behaviourally, intimate care standards, reporting and response, and the interfaces with car-004 (relationships and sexuality — the rights side of this coin), saf-001 (safeguarding), saf-021 (allegations against staff) and pc-002 (chaperones).",
    responsibilities: [
      { role: "Provider / Registered Manager", duties: [
        "Build the culture where the subject is speakable: sexual safety on the team-meeting agenda, the training done, the language provided — because staff who lack words report late",
        "Respond to every incident and concern through the machinery: safeguarding referrals at threshold, police involvement for apparent crimes (preserving evidence and the person's choices where capacity allows), regulator notifications, and the honest internal review",
        "Hold the dual duty in resident-to-resident incidents: both people are the service's to protect — the person harmed, and the person whose dementia removed their own understanding of what they did",
        "Apply saf-021's allegations machinery at full strength where staff are implicated, with the grooming-pattern awareness that catches the pre-incident behaviours" ] },
      { role: "All Staff", duties: [
        "Report the same day what feels wrong: the observation that is awkward to voice (the resident in the wrong room at night, the colleague's over-attention, the visitor whose affection reads oddly) — the policy's standing assurance is that voicing an unease that proves innocent costs nothing, and swallowing one that proves founded costs everything",
        "Deliver intimate care to the sexual-safety standard: the narrated, consented, dignified practice that protects the person from harm and the worker from misunderstanding",
        "Understand before labelling: sexualised behaviour from people with dementia or brain injury is assessed behaviourally (unmet need, disinhibition, misidentification) while the people around them are protected — both, simultaneously",
        "Respect the rights side absolutely: consensual relationships and sexuality are supported per car-004 — this policy polices harm, never intimacy itself" ] },
    ],
    keyPoints: [
      "The culture is the control: sexual safety appears in induction and annual training with scenario-based content (the words to use, the reporting routes, the both-things-true framing), on the team-meeting agenda at least quarterly (normalising the subject before an incident demands it), and in supervision where intimate care and its discomforts can be voiced — because the service's real defence is a workforce that can say the awkward sentence early",
      "Resident-to-resident incidents get capacity honesty: sexual contact between people supported is assessed for consent and capacity on both sides (capacity to consent to sexual relations assessed per its established legal test — and two people with advanced dementia may both lack it, making 'they seem happy' insufficient), with incidents involving incapacity treated as safeguarding events (referral, protection planning, family involvement handled with enormous care) while the rights of capacitous consenting adults are protected per car-004 — the policy's discipline is refusing to blur the two",
      "The dual duty is held without flinching: where a person who lacks understanding harms another, both are protected — the person harmed receives the full response (safety, health needs including sexual health, trauma support, family candour, justice routes per their capacity and wishes), and the person who acted receives behavioural assessment, care-plan response and protection from criminalisation their capacity makes unjust, while the practical separation and supervision that prevents recurrence is arranged — hard, resource-heavy, and non-optional",
      "Staff boundaries are absolute and the approach behaviours are trained: no sexual or romantic contact between staff and the people supported, ever, regardless of apparent consent (the power differential vitiates it — hr-003's boundaries at their brightest line), and the grooming patterns taught so colleagues recognise the pre-incident shape: the over-attention to one person, the engineered lone time, the gift and secret cultivation, the boundary-testing 'jokes', the volunteering for particular intimate care — each reportable as a pattern-concern without accusing anyone of anything but the pattern",
      "Visitors and third parties are inside the policy: the visiting 'befriender' whose attention concentrates oddly, the family member whose contact the person shrinks from, the contractor's behaviour — watched through ch-008's visiting machinery and dc-015's boundary lenses, with the person's own signals (fear, withdrawal, distress around specific people) read as data and the restriction machinery (ch-008's individual, evidenced, reviewed) available where protection requires",
      "Sexualised behaviour is assessed, not just sanctioned: behaviour from people with dementia, brain injury or learning disability (public masturbation, sexual approaches, disinhibited talk) is understood behaviourally — unmet intimacy needs, disinhibition, misidentification (the resident who believes another is their spouse), discomfort or infection, environmental triggers — with the response built from understanding (privacy for legitimate needs, redirection, clinical review, care-plan strategies) while everyone exposed to the behaviour is protected and staff subjected to it are supported (sexualised behaviour toward staff is a violence-and-aggression matter per saf-011, not a joke or a job hazard)",
      "Intimate care carries the standard: consent or best-interests basis per task, narration as practice ('I'm going to help you wash now — is that alright?'), the person's dignity engineered (covers, doors, curtains), same-gender care honoured where requested and feasible, two-worker arrangements where assessed (protection in both directions), and pc-002's chaperone logic available for clinical intimate procedures — with any deviation from a person's intimate-care plan treated as reportable",
      "Response runs the full machinery with trauma competence: immediate safety and health needs (including emergency contraception and STI care pathways where relevant, forensic considerations where police may be involved — the early call that preserves options), safeguarding referral at threshold, police for apparent crimes (the capacitous person's choices about police involvement respected and supported; incapacity handled through best-interests with safeguarding partners), regulator notification, family candour per the involvement plans and the person's wishes, trauma-informed support for the person (and hr-021's pathway for staff), and the review that asks the culture question: what did anyone almost-notice earlier, and why was it hard to say?",
    ],
    legislation: [
      "Sexual Offences Act 2003 (offences; capacity to consent; care-worker offences sections)",
      "Care Act 2014 (safeguarding)",
      "Mental Capacity Act 2005 (capacity to consent to sexual relations — the established legal test)",
      "Health and Social Care Act 2008 (Regulated Activities) Regulations 2014 — Regulations 12, 13, 20",
      "Human Rights Act 1998 (Articles 3 and 8 — protection and private life, both engaged)",
    ],
    sections: [
      { heading: "Making It Speakable", body: "The policy's foundation is linguistic and cultural, because the audit trail of most care-setting sexual-safety failures runs through sentences nobody said: the night worker who noticed the wandering resident's destination pattern and mentioned it to no one, the colleague's over-attention that several people found odd and no one named, the resident's flinch that got recorded as 'unsettled'. The service builds speakability deliberately: training that rehearses the actual sentences ('I want to flag something that might be nothing — I've noticed...'), the pattern-concern route that lets staff report shapes without accusing people (the concern about over-attention is a request for senior eyes, not an allegation), the team-meeting normalisation (sexual safety as a standing quarterly item — incidents elsewhere in the sector discussed as learning, the policy's scenarios walked), supervision that makes intimate-care discomfort discussable (the worker uneasy about a colleague's practice, or their own reactions, has a place to say so), and leadership modelling (the manager who says 'sexual safety' in plain words licenses everyone else to). The standing assurances are explicit and kept: the unease voiced early that proves innocent is thanked, never mocked; the report against a popular colleague is protected from the social punishment that silences wards; and the person who reports late out of fear is helped to report now, because late is the second-best time." },
      { heading: "Between the People We Support", body: "Resident-to-resident sexual contact is where the policy's honesty matters most, because it sits at the crossing of two duties: protecting people from harm and protecting adults' rights to intimacy (car-004's territory — and the two policies are read together always). The framework: any sexual contact involving a person whose capacity to consent to sexual relations is doubtful triggers assessment per the established legal test (understanding the nature of the act, its risks, and the ability to refuse — decision-specific, properly done, recorded), and the honest outcomes are honestly handled — two capacitous consenting adults are supported with privacy and dignity (whatever staff or families feel about it); capacity on one side only is a safeguarding event full stop (the capacitous party's behaviour addressed through the machinery its own capacity attracts); and incapacity on both sides (the advanced-dementia pairing that 'seems mutual') is managed as the safeguarding-and-care-planning challenge it is: neither can consent, so the contact cannot be simply permitted, yet neither is culpable, so the response is protective rather than punitive — separation and supervision calibrated to the least restriction that actually protects, behavioural understanding of what each person is seeking (companionship, touch, a remembered marriage), needs met in safe forms, families involved with candour and care, and the arrangements reviewed because dementia moves. Incidents run the full response: immediate safety, health needs addressed (examination, sexual health, the forensic-preservation call made early where police involvement is possible), safeguarding referral, notifications, family candour, and trauma-informed support for the person harmed — with their account believed as the starting position and their capacity-appropriate wishes steering the justice questions." },
      { heading: "Staff, Visitors and the Patterns Before Incidents", body: "The staff boundary is stated without qualification: sexual or romantic contact between staff and people supported is prohibited absolutely — consent does not cure it (the law agrees: care-worker sexual activity with people in their care is criminalised in wide circumstances, and the power differential vitiates apparent willingness in all of them), and the prohibition survives discharge and role-change per hr-003's boundary machinery. Around the bright line, the approach patterns are trained as the early-warning system: grooming of adults in care follows recognisable shapes — the concentration of attention on one person, the engineering of lone time (swaps to particular shifts, volunteering for particular intimate care), gifts and secrets ('don't tell the others I brought you this'), progressive boundary-testing (the 'joke', the lingering touch, the personal disclosure that invites reciprocity), and the isolation of the target from other staff's care — and each is reportable as a pattern-concern through the route that requests senior eyes without laying charges. saf-021's allegations machinery runs at full strength when concerns crystallise: protection first (duties adjusted pending), the parallel referrals (police where apparent crime, LADO-equivalent, DBS per hr-008's conditions, professional bodies), the investigation done properly, and the historical review (the previous placements' patterns asked about — mobile predators depend on references that omit). Visitors and third parties are watched through the existing lenses with sexual safety named among the things they watch for: ch-008's visiting machinery (the individual restriction tools where evidence requires), dc-015's boundary framework, the person's own signals treated as first-class data (fear or withdrawal around a specific person is a finding to decode, never mere 'behaviour'), and the chaperoned or supervised arrangements available where protection and contact must coexist." },
      { heading: "Behaviour, Intimate Care and the Response That Repairs", body: "Sexualised behaviour from people with cognitive impairment is met with assessment before judgement: the behavioural lens asks what the behaviour communicates (unmet need for intimacy or touch in lives stripped of both, disinhibition from the dementia or injury itself, misidentification — the resident who genuinely believes another is their spouse of fifty years, discomfort, infection, medication effects, environmental triggers), the clinical review runs (the new behaviour is a change like any other — eff-023's lens), and the care-plan response builds from understanding: privacy enabled for legitimate needs (the door that closes, the time alone — car-004's dignity), redirection and environmental design, identity-confusion handled with compassion for everyone (including the spouse who visits and grieves), and specialist input brokered where complexity warrants. Simultaneously and without contradiction, everyone exposed is protected: other residents shielded from behaviour they cannot consent to witness or receive, staff subjected to sexualised behaviour or touch supported as saf-011 requires (it is workplace violence, not a job hazard to absorb with a laugh — reported, patterned, planned around), and the both-things-true framing held in every discussion. Intimate care carries its engineering: per-task consent or best-interests basis, narration as standard practice, dignity mechanics (exposure minimised and sequenced, doors and curtains, the cover that moves as the wash does), gender preferences honoured where requested and staffing feasibly allows (and the gap escalated where it doesn't), two-worker arrangements where the assessment concludes protection in either direction needs them, and deviations from the intimate-care plan reportable by anyone. And when the worst happens anyway, the response repairs: the machinery runs (safety, health, forensics-preserving early calls, referrals, notifications, candour), the person harmed receives trauma-informed support with their own pace and choices centred, staff receive hr-021's care (the worker who found the incident carries it home), and the review closes with this policy's founding question asked without defensiveness: what was almost said earlier — and what, in our culture, made it hard to say?" },
    ],
    appendices: [
      { title: "Sexual Safety Concern & Incident Response Card", type: "template", body:
"SPEAK THE SENTENCE (same day, any unease): 'I want to flag something that might be nothing — I've noticed ____.' Pattern-concerns request SENIOR EYES, they don't lay charges. Innocent-proving uneases are THANKED. Late reporting is helped, not shamed.\nPATTERNS WORTH VOICING: attention concentrating on one person | engineered lone time (shift swaps, volunteering for particular intimate care) | gifts & secrets | boundary-testing 'jokes'/touch | target isolated from other staff | resident's fear/withdrawal around a specific person | night-time room patterns\nINCIDENT RESPONSE (in order): 1. SAFETY now (separate, supervise, calm) 2. HEALTH needs (examination, sexual health, emergency contraception where relevant) — make the EARLY CALL that preserves forensic options where police may be involved (don't wash items/areas, note everything, times) 3. SAFEGUARDING referral at threshold 4. POLICE for apparent crimes (capacitous person's choices respected & supported; incapacity via BI + safeguarding partners) 5. NOTIFICATIONS (regulator; family candour per wishes/plans) 6. TRAUMA-INFORMED support (person's pace; hr-021 for staff) 7. REVIEW: what was almost-said earlier, and why was it hard?\nCAPACITY HONESTY (resident-to-resident): consent capacity assessed BOTH sides (established legal test, decision-specific) | capacitous+capacitous = car-004 rights (privacy, dignity) | one-sided capacity = safeguarding, full stop | neither (advanced dementia pairing): protective not punitive — least-restrictive separation/supervision, needs understood & met safely, families involved with care, reviewed as dementia moves\nSTAFF LINE (absolute): no sexual/romantic contact with people supported — consent does not cure it; the law criminalises it; report the pattern before the incident" },
      { title: "Intimate Care Standard & Culture Audit", type: "template", body:
"INTIMATE CARE STANDARD (every task): consent or BI basis per task | NARRATED ('I'm going to help you wash now — alright?') | dignity mechanics: exposure minimised & sequenced, doors/curtains, moving cover | gender preference honoured where requested (staffing gap → escalated, not shrugged) | two-worker where assessed (protection both directions) | deviations from the plan reportable by ANYONE | clinical intimate procedures → pc-002 chaperone logic\nSEXUALISED BEHAVIOUR (cognitive impairment): ASSESS before judging — communicates what? (unmet intimacy/touch need | disinhibition | misidentification (the remembered spouse) | discomfort/infection | meds | environment) → clinical review (new behaviour = change) → plan from understanding (privacy for legitimate needs, redirection, compassion for all incl. the grieving visiting spouse, specialist input)\nBOTH THINGS TRUE: the person understood AND everyone protected | staff subjected to it = saf-011 workplace violence (reported, patterned, planned around — never a laugh line)\nCULTURE AUDIT (annual): sexual safety on quarterly team agendas [ ] | scenario training done (the actual sentences rehearsed) [ ] | supervision makes intimate-care discomfort discussable [ ] | pattern-concern route used this year (if zero: is that safety, or silence?) | reporters protected from social punishment [ ] | leadership says the words plainly [ ]" },
    ],
  },
};
